import type { RestaurantLocale, RestaurantSearch } from "../services/shida/restaurants-client";
import { restaurantQuery } from "../services/shida/restaurants-client";

export const restaurantLocales = ["en", "fr", "ln", "sw"] as const;
export function isRestaurantLocale(value: string): value is RestaurantLocale { return restaurantLocales.includes(value as RestaurantLocale); }
export function restaurantPath(locale: RestaurantLocale, suffix = "") { return `${locale === "en" ? "" : `/${locale}`}/shida/restaurants${suffix}`; }
export function businessPath(locale: RestaurantLocale, id: string) { return `${locale === "en" ? "" : `/${locale}`}/shida/businesses/${encodeURIComponent(id)}`; }
export function restaurantReturn(raw: RestaurantSearch) {
  const candidate = Array.isArray(raw.back) ? raw.back[0] : raw.back;
  return restaurantQuery(Object.fromEntries(new URLSearchParams(candidate?.slice(0, 2000) ?? ""))).toString();
}
export const restaurantCopy = {
  en: {
    title: "Restaurants & Malewa", intro: "Explore public establishments, menus and opening information. Continue on SHIDA for personal actions.", search: "Search", name: "Establishment name", city: "City", area: "Commune or neighbourhood", dish: "Dish", type: "Establishment type", mode: "Service mode", all: "All", openOnly: "Open now — confirmed schedules only", reset: "Clear filters", empty: "No establishments match these filters. Try another search or explore SHIDA.", error: "Restaurants are temporarily unavailable. Please try again.", unavailable: "This establishment is unavailable.", retry: "Try again", back: "Back to results", menu: "Menu", noMenu: "No public menu items are available. An establishment may publish information without a menu.", details: "View establishment", previous: "Previous", next: "Next", page: "Page", results: "results", open: "Open", closed: "Closed", unknown: "Opening hours unknown", hours: "Opening hours", timezone: "Local timezone", closures: "Exceptional closures", evaluated: "Information checked at", information: "Opening information is informational; SHIDA supplies the current status.", owner: "Owning Business", activities: "Public activities", noActivities: "No eligible public activities are available.", business: "Business", noBusiness: "This establishment has no linked public Business profile.", photo: "No photo available", save: "Save in SHIDA", follow: "Follow in SHIDA", whatsapp: "Open this establishment on WhatsApp", menuWhatsapp: "Open this menu on WhatsApp", report: "To report this establishment, open it on WhatsApp and select Report. Saving and following require your explicit confirmation in SHIDA.", actionsUnavailable: "SHIDA continuation is currently unavailable.", unit: "Unit price", amounts: "Available monetary amounts", minimum: "Minimum amount", unknownPrice: "Price not specified", fixed: "Fixed dish", component: "Component", available: "Available", sold_out: "Sold out", temporarily_unavailable: "Temporarily unavailable", dated: "Current dated offering", until: "to", loading: "Loading Restaurants & Malewa…", breadcrumb: "Breadcrumb", language: "Restaurant language", services: "Services", wenze: "Wenze", jobs: "Jobs", restaurant: "Restaurant", malewa: "Malewa", cafe: "Café", fast_food: "Fast food", catering: "Catering", days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  },
  fr: {
    title: "Restaurants & Malewa", intro: "Découvrez les établissements publics, leurs menus et leurs horaires. Continuez sur SHIDA pour vos actions personnelles.", search: "Rechercher", name: "Nom de l’établissement", city: "Ville", area: "Commune ou quartier", dish: "Plat", type: "Type d’établissement", mode: "Mode de service", all: "Tous", openOnly: "Ouvert maintenant — horaires confirmés uniquement", reset: "Effacer les filtres", empty: "Aucun établissement ne correspond à ces filtres. Essayez une autre recherche ou explorez SHIDA.", error: "Les restaurants sont temporairement indisponibles. Veuillez réessayer.", unavailable: "Cet établissement est indisponible.", retry: "Réessayer", back: "Retour aux résultats", menu: "Menu", noMenu: "Aucun élément de menu public n’est disponible. Un établissement peut publier ses informations sans menu.", details: "Voir l’établissement", previous: "Précédent", next: "Suivant", page: "Page", results: "résultats", open: "Ouvert", closed: "Fermé", unknown: "Horaires inconnus", hours: "Horaires d’ouverture", timezone: "Fuseau horaire local", closures: "Fermetures exceptionnelles", evaluated: "Informations vérifiées le", information: "Les horaires sont informatifs ; SHIDA fournit le statut actuel.", owner: "Entreprise propriétaire", activities: "Activités publiques", noActivities: "Aucune activité publique éligible n’est disponible.", business: "Entreprise", noBusiness: "Cet établissement n’a pas de profil d’entreprise public lié.", photo: "Aucune photo disponible", save: "Enregistrer dans SHIDA", follow: "Suivre dans SHIDA", whatsapp: "Ouvrir cet établissement sur WhatsApp", menuWhatsapp: "Ouvrir ce menu sur WhatsApp", report: "Pour signaler cet établissement, ouvrez-le sur WhatsApp puis choisissez Signaler. L’enregistrement et le suivi nécessitent votre confirmation explicite dans SHIDA.", actionsUnavailable: "La continuation vers SHIDA est actuellement indisponible.", unit: "Prix unitaire", amounts: "Montants proposés", minimum: "Montant minimum", unknownPrice: "Prix non précisé", fixed: "Plat fixe", component: "Composant", available: "Disponible", sold_out: "Épuisé", temporarily_unavailable: "Temporairement indisponible", dated: "Offre datée en cours", until: "au", loading: "Chargement des Restaurants & Malewa…", breadcrumb: "Fil d’Ariane", language: "Langue des restaurants", services: "Services", wenze: "Wenze", jobs: "Emplois", restaurant: "Restaurant", malewa: "Malewa", cafe: "Café", fast_food: "Restauration rapide", catering: "Traiteur", days: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"],
  },
  ln: {
    title: "Restaurants & Malewa", intro: "Tala bisika ya kolya, menu mpe ngonga ya kofungola. Koba na SHIDA mpo na makambo na yo.", search: "Luka", name: "Nkombo ya esika", city: "Engumba", area: "Commune to quartier", dish: "Bilei", type: "Lolenge ya esika", mode: "Lolenge ya service", all: "Nyonso", openOnly: "Efungwami sikoyo — ngonga oyo endimami kaka", reset: "Longola bapɔni", empty: "Esika moko te ekokani na boluki oyo. Luka lisusu to tala SHIDA.", error: "Restaurants ezali sikoyo te. Meka lisusu.", unavailable: "Esika oyo ezali te.", retry: "Meka lisusu", back: "Zonga na boluki", menu: "Menu", noMenu: "Bilei ya menu ezali polele te. Esika ekoki kobimisa makambo na yango ata menu ezali te.", details: "Tala esika", previous: "Ya liboso", next: "Ya nsima", page: "Lokasa", results: "bimano", open: "Efungwami", closed: "Ekangami", unknown: "Ngonga eyebani te", hours: "Ngonga ya kofungola", timezone: "Fuseau horaire ya esika", closures: "Bokangami ya sipesiale", evaluated: "Makambo etalelami na", information: "Ngonga ezali mpo na koyebisa; SHIDA epesaka ezalela ya sikoyo.", owner: "Business ya esika", activities: "Misala ya polele", noActivities: "Mosala ya polele oyo endimami ezali te.", business: "Business", noBusiness: "Esika oyo ezali na profil ya Business ya polele te.", photo: "Fɔtɔ ezali te", save: "Bomba na SHIDA", follow: "Landa na SHIDA", whatsapp: "Fungola esika oyo na WhatsApp", menuWhatsapp: "Fungola menu oyo na WhatsApp", report: "Mpo na kofunda esika oyo, fungola yango na WhatsApp mpe pona Kofunda. Osengeli kondima polele mpo na kobomba to kolanda na SHIDA.", actionsUnavailable: "Kokoba na SHIDA ekoki kosalema sikoyo te.", unit: "Ntalo ya unité", amounts: "Montant oyo ezali", minimum: "Montant ya moke", unknownPrice: "Ntalo eyebani te", fixed: "Bilei ebongisami", component: "Eteni", available: "Ezali", sold_out: "Esili", temporarily_unavailable: "Ezali sikoyo te", dated: "Offre ya dati oyo ezali sikoyo", until: "kino", loading: "Restaurants & Malewa ezali koya…", breadcrumb: "Nzela ya lokasa", language: "Lokota ya restaurants", services: "Misala", wenze: "Wenze", jobs: "Misala ya mosala", restaurant: "Restaurant", malewa: "Malewa", cafe: "Café", fast_food: "Bilei ya mbangu", catering: "Traiteur", days: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"],
  },
  sw: {
    title: "Restaurants & Malewa", intro: "Tazama sehemu za chakula, menyu na saa za kufungua. Endelea kwenye SHIDA kwa hatua binafsi.", search: "Tafuta", name: "Jina la sehemu", city: "Mji", area: "Manispaa au mtaa", dish: "Chakula", type: "Aina ya sehemu", mode: "Njia ya huduma", all: "Zote", openOnly: "Wazi sasa — ratiba zilizothibitishwa pekee", reset: "Futa vichujio", empty: "Hakuna sehemu inayolingana na vichujio hivi. Tafuta tena au tazama SHIDA.", error: "Migahawa haipatikani kwa sasa. Tafadhali jaribu tena.", unavailable: "Sehemu hii haipatikani.", retry: "Jaribu tena", back: "Rudi kwenye matokeo", menu: "Menyu", noMenu: "Hakuna vyakula vya menyu ya umma vinavyopatikana. Sehemu inaweza kuchapisha taarifa bila menyu.", details: "Tazama sehemu", previous: "Iliyotangulia", next: "Inayofuata", page: "Ukurasa", results: "matokeo", open: "Wazi", closed: "Imefungwa", unknown: "Saa hazijulikani", hours: "Saa za kufungua", timezone: "Ukanda wa saa wa eneo", closures: "Kufungwa kwa kipekee", evaluated: "Taarifa zimekaguliwa", information: "Saa ni za taarifa; SHIDA hutoa hali ya sasa.", owner: "Biashara inayomiliki", activities: "Shughuli za umma", noActivities: "Hakuna shughuli za umma zinazostahiki.", business: "Biashara", noBusiness: "Sehemu hii haina wasifu wa biashara ya umma uliounganishwa.", photo: "Hakuna picha", save: "Hifadhi kwenye SHIDA", follow: "Fuata kwenye SHIDA", whatsapp: "Fungua sehemu hii kwenye WhatsApp", menuWhatsapp: "Fungua menyu hii kwenye WhatsApp", report: "Kuripoti sehemu hii, ifungue kwenye WhatsApp kisha uchague Ripoti. Kuhifadhi na kufuata kunahitaji uthibitisho wako wa wazi kwenye SHIDA.", actionsUnavailable: "Kuendelea kwenye SHIDA hakupatikani kwa sasa.", unit: "Bei kwa kipimo", amounts: "Kiasi cha fedha kinachopatikana", minimum: "Kiasi cha chini", unknownPrice: "Bei haijatajwa", fixed: "Chakula kamili", component: "Kipengele", available: "Inapatikana", sold_out: "Imeisha", temporarily_unavailable: "Haipatikani kwa sasa", dated: "Toleo la sasa lenye tarehe", until: "hadi", loading: "Inapakia Restaurants & Malewa…", breadcrumb: "Njia ya ukurasa", language: "Lugha ya migahawa", services: "Huduma", wenze: "Wenze", jobs: "Kazi", restaurant: "Mgahawa", malewa: "Malewa", cafe: "Kahawa", fast_food: "Chakula cha haraka", catering: "Upishi", days: ["Jumatatu", "Jumanne", "Jumatano", "Alhamisi", "Ijumaa", "Jumamosi", "Jumapili"],
  },
};
