import type { Locale } from "./i18n";

type Story = {
  label: string; title: string; body: string[]; steps: string[];
  aside: string; person: string; role: string; alt: string; action: string;
};
type ShidaCopy = {
  title: string; intro: string; continuation: string; start: string; whatsapp: string;
  storiesLabel: string; scenarios: string; stories: Story[];
  connectsLabel: string; connectsTitle: string; connectsBody: string; connectionSteps: string[];
  directTitle: string; directBody: string; ready: string; finalTitle: string; finalBody: string;
  open: string; explore: string; heroAlt: string; closingAlt: string; businessNote: string;
};

export const shidaCopy: Record<Locale, ShidaCopy> = {
  en: {
    title: "One platform\nfor everyday\nopportunities.",
    intro: "SHIDA connects people to jobs, services, shops, housing, hotels, restaurants and transport — through NIHILOBA Web and WhatsApp.",
    continuation: "Discover opportunities on the web, then continue with SHIDA in a familiar WhatsApp experience.",
    start: "Get started with SHIDA", whatsapp: "Open on WhatsApp",
    storiesLabel: "Everyday life, connected", scenarios: "Illustrated scenarios showing how SHIDA can help.",
    stories: [
      { label: "Employment", person: "Christian", role: "Job seeker", title: "Christian is looking\nfor his first serious job.", body: ["After finishing his studies, Christian wants to start his career without spending hours searching across disconnected sources.", "On SHIDA, he can discover job opportunities, use his employment profile, apply through a guided journey and follow what happens next."], steps: ["Discover", "Open", "Apply", "Follow"], aside: "A clearer path to the next opportunity.", alt: "Illustration of Christian searching for work on his laptop, overlooking the city.", action: "Explore jobs" },
      { label: "Services", person: "Grâce", role: "Client", title: "Grâce needs someone\nshe can trust.", body: ["Grâce needs a hairstylist for an important event.", "With SHIDA, she can discover service providers, understand what they offer, send a request and continue the conversation through WhatsApp."], steps: ["Find", "Choose", "Request", "Confirm"], aside: "The right service starts with a conversation.", alt: "Illustration of a hairstylist braiding a client’s hair in a welcoming salon.", action: "Find a service" },
      { label: "Wenze", person: "Mireille", role: "Vendor", title: "Mireille wants to grow\nher clothing business.", body: ["Mireille already sells clothes and fabrics locally. She does not need a complicated e-commerce website to become more visible.", "With SHIDA, she can present her products, make her shop easier to discover and connect with customers through a familiar digital journey."], steps: ["Show", "Present products", "Receive interest", "Sell"], aside: "A local shop. New possibilities.", alt: "Illustration of Mireille presenting colourful fabrics to a customer in her clothing shop.", action: "Explore Wenze" },
      { label: "Housing", person: "Patrick", role: "Home seeker", title: "Patrick needs\na place to live.", body: ["Patrick is moving to another part of the city and needs a suitable apartment.", "SHIDA helps him browse listings, understand location and price, compare options and request a visit without exposing private information too early."], steps: ["Browse", "Compare", "Request visit", "Continue"], aside: "Space for the next chapter.", alt: "Illustration of an apartment building with balconies on a palm-lined city street.", action: "Browse housing" },
      { label: "Hotels", person: "Sarah", role: "Traveller", title: "Sarah is visiting\nKinshasa for a few days.", body: ["Sarah needs a comfortable place to stay without calling several hotels individually.", "With SHIDA, she can discover hotels, understand available room options and continue her booking request through WhatsApp."], steps: ["Find", "Check", "Request", "Confirm"], aside: "A simpler start to the stay.", alt: "Illustration of Sarah arriving with her suitcase at a hotel entrance.", action: "Discover hotels" },
      { label: "Restaurants", person: "Jean", role: "Customer", title: "Jean and his family want\nsomewhere good to eat.", body: ["Jean wants to take his family somewhere they can enjoy a good meal together.", "Instead of searching across scattered recommendations, SHIDA helps them discover restaurants and understand what is available."], steps: ["Discover", "Explore", "Get in touch", "Enjoy"], aside: "Good food. Time together.", alt: "Illustration of a family sharing a meal at a lively restaurant with other diners.", action: "Explore restaurants" },
      { label: "Transport", person: "David", role: "Commuter", title: "David needs\nto get there.", body: ["David needs a practical way to move across the city.", "SHIDA helps connect the transport journey to a familiar digital flow so that requests and communication can happen more clearly."], steps: ["Find", "Choose", "Request", "Continue"], aside: "The next journey starts here.", alt: "Illustration of a passenger and driver discussing a trip beside a car.", action: "Ask SHIDA about transport" },
      { label: "For professionals", person: "Mireille", role: "Business owner", title: "Mireille runs\na small business.", body: ["Getting customers is only one part of running a business. Mireille also needs to organise her activity and keep track of requests.", "SHIDA is designed to connect discovery with practical business management."], steps: ["Be visible", "Manage", "Understand", "Grow"], aside: "More time for the work that matters.", alt: "Illustration of a business owner working on a laptop beside a lake and green hills.", action: "Talk about your business" },
    ],
    businessNote: "Further business management tools are in development.",
    connectsLabel: "How it all connects", connectsTitle: "Start where the opportunity is.\nContinue with SHIDA.",
    connectsBody: "A SHIDA journey can begin on NIHILOBA Web, from a shared link or through a direct entry point. From there, WhatsApp guides you through the relevant next steps in a familiar environment.",
    connectionSteps: ["Discover on NIHILOBA Web", "Continue on WhatsApp", "Take the next step"],
    directTitle: "One direct path\nto the right SHIDA journey.", directBody: "Jobs, services, shops, properties and hotels can use direct links or QR codes to open the relevant journey. Opening a link does not automatically share personal information.",
    ready: "Ready to get started?", finalTitle: "SHIDA is here\nfor everyday life.", finalBody: "Find opportunities. Grow your activity. Continue through tools people already know.", open: "Open SHIDA on WhatsApp", explore: "Explore SHIDA",
    heroAlt: "Illustration of everyday city life: people, local shops and transport on a sunny African street.", closingAlt: "Illustrated panorama of a suspension bridge over the river, with palm trees and a city at sunset.",
  },
  fr: {
    title: "Une plateforme\npour les opportunités\ndu quotidien.", intro: "SHIDA relie les personnes aux emplois, services, boutiques, logements, hôtels, restaurants et transports grâce à NIHILOBA Web et WhatsApp.", continuation: "Découvrez les opportunités sur le web, puis poursuivez simplement votre démarche avec SHIDA sur WhatsApp.", start: "Commencer avec SHIDA", whatsapp: "Ouvrir sur WhatsApp",
    storiesLabel: "Le quotidien, connecté", scenarios: "Des situations illustrées pour découvrir comment SHIDA peut vous aider.",
    stories: [
      { label: "Emploi", person: "Christian", role: "Candidat", title: "Christian cherche\nson premier emploi sérieux.", body: ["Après ses études, Christian veut commencer sa carrière sans passer des heures à chercher parmi des sources dispersées.", "Avec SHIDA, il peut découvrir des offres, utiliser son profil emploi, postuler dans un parcours guidé et suivre la suite de sa candidature."], steps: ["Découvrir", "Ouvrir", "Postuler", "Suivre"], aside: "Un chemin plus clair vers la prochaine opportunité.", alt: "Illustration de Christian recherchant un emploi sur son ordinateur, avec vue sur la ville.", action: "Explorer les emplois" },
      { label: "Services", person: "Grâce", role: "Cliente", title: "Grâce cherche quelqu’un\nen qui elle peut avoir confiance.", body: ["Grâce a besoin d’une coiffeuse pour un événement important.", "Avec SHIDA, elle peut découvrir des prestataires, comprendre leurs services, envoyer une demande et poursuivre l’échange sur WhatsApp."], steps: ["Trouver", "Choisir", "Demander", "Confirmer"], aside: "Le bon service commence par un échange.", alt: "Illustration d’une coiffeuse tressant les cheveux d’une cliente dans un salon accueillant.", action: "Trouver un service" },
      { label: "Wenze", person: "Mireille", role: "Commerçante", title: "Mireille veut développer\nson commerce de vêtements.", body: ["Mireille vend déjà des vêtements et des tissus localement. Elle n’a pas besoin de créer un site e-commerce complexe pour devenir plus visible.", "Avec SHIDA, elle peut présenter ses produits, rendre sa boutique plus facile à découvrir et entrer en contact avec de nouveaux clients."], steps: ["Présenter", "Montrer les produits", "Susciter l’intérêt", "Vendre"], aside: "Une boutique de quartier. De nouvelles possibilités.", alt: "Illustration de Mireille présentant des tissus colorés à une cliente dans sa boutique de vêtements.", action: "Explorer Wenze" },
      { label: "Logements", person: "Patrick", role: "À la recherche d’un logement", title: "Patrick cherche\nun endroit où vivre.", body: ["Patrick déménage dans une autre partie de la ville et cherche un logement adapté.", "SHIDA lui permet de parcourir les annonces, comparer les quartiers et les prix, puis demander une visite sans exposer trop tôt les informations privées."], steps: ["Parcourir", "Comparer", "Demander une visite", "Continuer"], aside: "Un lieu pour un nouveau départ.", alt: "Illustration d’un immeuble avec balcons dans une rue bordée de palmiers.", action: "Parcourir les logements" },
      { label: "Hôtels", person: "Sarah", role: "Voyageuse", title: "Sarah passe quelques jours\nà Kinshasa.", body: ["Sarah cherche un endroit confortable où séjourner sans devoir appeler plusieurs hôtels.", "Avec SHIDA, elle peut découvrir des établissements, consulter les options de chambres et poursuivre sa demande de réservation sur WhatsApp."], steps: ["Trouver", "Consulter", "Demander", "Confirmer"], aside: "Un séjour qui commence simplement.", alt: "Illustration de Sarah arrivant avec sa valise à l’entrée d’un hôtel.", action: "Découvrir les hôtels" },
      { label: "Restaurants", person: "Jean", role: "Client", title: "Jean veut trouver un bon\nrestaurant pour sa famille.", body: ["Jean souhaite passer un bon moment avec sa famille autour d’un repas.", "SHIDA les aide à découvrir des restaurants et à comprendre ce qui est disponible sans dépendre uniquement de recommandations dispersées."], steps: ["Découvrir", "Explorer", "Prendre contact", "Profiter"], aside: "Un bon repas. Un moment ensemble.", alt: "Illustration d’une famille partageant un repas dans un restaurant animé, entourée d’autres clients.", action: "Explorer les restaurants" },
      { label: "Transport", person: "David", role: "Passager", title: "David doit\nse déplacer.", body: ["David cherche une manière pratique d’organiser son trajet.", "SHIDA permet de relier cette démarche à un parcours numérique simple et familier pour faciliter la demande et la communication."], steps: ["Trouver", "Choisir", "Demander", "Continuer"], aside: "Le prochain trajet commence ici.", alt: "Illustration d’une passagère et d’un chauffeur discutant d’un trajet près d’une voiture.", action: "Parler transport avec SHIDA" },
      { label: "Pour les professionnels", person: "Mireille", role: "Entrepreneuse", title: "Mireille gère\nune petite entreprise.", body: ["Trouver des clients n’est qu’une partie de la gestion d’une activité. Mireille doit également organiser ses demandes et suivre son activité.", "SHIDA est conçu pour relier la découverte à la gestion pratique de l’activité."], steps: ["Être visible", "Gérer", "Comprendre", "Développer"], aside: "Plus de temps pour l’essentiel.", alt: "Illustration d’une entrepreneuse travaillant sur un ordinateur près d’un lac entouré de collines.", action: "Parlons de votre activité" },
    ],
    businessNote: "D’autres outils de gestion sont en développement.", connectsLabel: "Comment tout se connecte", connectsTitle: "Commencez là où se trouve l’opportunité.\nContinuez avec SHIDA.", connectsBody: "Un parcours SHIDA peut commencer sur NIHILOBA Web, depuis un lien partagé ou via un accès direct. WhatsApp vous guide ensuite vers les prochaines étapes pertinentes dans un environnement déjà familier.", connectionSteps: ["Découvrir sur NIHILOBA Web", "Continuer sur WhatsApp", "Passer à l’action"], directTitle: "Un accès direct\nau bon parcours SHIDA.", directBody: "Les emplois, services, boutiques, logements et hôtels peuvent utiliser des liens directs ou des QR codes pour ouvrir le parcours adapté. Ouvrir un lien ne partage pas automatiquement vos informations personnelles.", ready: "Prêt à commencer ?", finalTitle: "SHIDA accompagne\nle quotidien.", finalBody: "Trouvez des opportunités. Développez votre activité. Continuez avec des outils que vous connaissez déjà.", open: "Ouvrir SHIDA sur WhatsApp", explore: "Explorer SHIDA", heroAlt: "Illustration du quotidien dans une rue africaine ensoleillée, entre commerces, passants et transports.", closingAlt: "Panorama illustré d’un pont suspendu au-dessus du fleuve, avec palmiers et ville au coucher du soleil.",
  },
};
