import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
import {preparationCopy} from '../../app/lib/restaurant-preparation-copy';
test.skip(process.env.RESTAURANT_PREPARATION_BACKEND!=='1','Requires isolated real Backend');
const backend='https://localhost:3443',prep=(page:Page)=>page.locator('section.rst-preparation').last();
async function control(api:APIRequestContext,path:string){const r=await api.post(backend+'/__preparation/'+path);expect(r.ok(),await r.text()).toBe(true);return r.json();}
async function serviceControl(api:APIRequestContext,path:string){const r=await api.post(backend+'/__service/'+path);expect(r.ok(),await r.text()).toBe(true);return r.json();}
async function open(page:Page,name:string){await page.goto('/shida/seller/restaurants');await page.locator('.rst-grid .rst-card').filter({hasText:name}).first().getByRole('button',{name:'Edit',exact:true}).click();}
test('real Personal Pro preparation and Free station resolution/recovery, original legacy work and phone layout',async({page,context,request})=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());const data=await control(request,'seed/personal');const {token}=await serviceControl(request,'session/personal');await context.addCookies([{name:'nihiloba_personal_session',value:token,domain:'localhost',path:'/api/shida',secure:true,httpOnly:true,sameSite:'Lax'}]);await page.setViewportSize({width:390,height:844});await open(page,data.name);
 await page.getByRole('button',{name:'Kitchen',exact:true}).first().click();await prep(page).getByRole('button',{name:data.mixed}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Fufu');await expect(prep(page).locator('.rst-station-detail')).toContainText('Pondu');await expect(prep(page).locator('.rst-station-detail')).not.toContainText('Original mango drink');await expect(prep(page).getByRole('button',{name:data.bar_only})).toHaveCount(0);
 await prep(page).getByRole('button',{name:'Start preparation'}).click();await prep(page).getByRole('button',{name:'Mark ready'}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Whole order: Preparing');await expect(prep(page).locator('.rst-station-detail')).toContainText(preparationCopy.en.mixed);
 await page.locator('.rst-preparation-owner').getByRole('button',{name:preparationCopy.en.bar,exact:true}).click();await prep(page).getByRole('button',{name:data.mixed}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Original mango drink');await expect(prep(page).locator('.rst-station-detail')).not.toContainText('Pondu');await prep(page).getByRole('button',{name:'Start preparation'}).click();await prep(page).getByRole('button',{name:'Mark ready'}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Whole order: Ready');
 await prep(page).getByRole('button',{name:data.bar_only}).click();await prep(page).getByRole('button',{name:'Start preparation'}).click();await prep(page).getByRole('button',{name:'Mark ready'}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Whole order: Ready');await page.screenshot({path:'.s3a-local/rm-v11-10f2/personal-bar-390.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('.rst-preparation-owner').getByRole('button',{name:'Kitchen',exact:true}).click();await prep(page).getByRole('button',{name:data.legacy}).click();await expect(prep(page).getByText('Legacy whole-order Kitchen')).toBeVisible();await prep(page).getByRole('button',{name:'Start preparation'}).click();await prep(page).getByRole('button',{name:'Mark ready'}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Whole order: Ready');
 await serviceControl(request,'personal/paid/off');await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect(prep(page).getByText(preparationCopy.en.lost)).toBeVisible();await page.locator('.rst-preparation-owner').getByRole('button',{name:'Free orders'}).click();await page.getByRole('combobox',{name:'Orders',exact:true}).selectOption('active');const orderCard=page.locator('.rst-order-layout .rst-card').filter({has:page.getByRole('heading',{name:data.recovery,exact:true})}).first();await orderCard.getByRole('button',{name:'Review',exact:true}).click();await expect(prep(page).getByText(/Food preference: Original preference/)).toBeVisible();
 const paidReads:string[]=[];page.on('request',r=>{if(/\/preparation\/(kitchen|bar)\/(orders|feed)\/?(?:\?|$)/.test(r.url()))paidReads.push(r.url());});
 // A lost committed recovery retains confirmation/reason and exact station envelope.
 let original='',tries=0;await page.route('**/orders/*/preparation/kitchen/recover/',async route=>{tries++;if(tries===1){original=route.request().postData()!;await route.fetch();return route.abort();}expect(route.request().postData()).toBe(original);await route.continue();});await expect(prep(page).getByRole('button',{name:'Confirm station ready'})).toBeDisabled();await prep(page).getByRole('checkbox',{name:preparationCopy.en.confirm}).check();await prep(page).getByRole('combobox',{name:'Reason'}).selectOption('cannot_fulfill');await prep(page).getByRole('button',{name:'Confirm station ready'}).click();await expect(prep(page).getByRole('button',{name:'Retry the same action'})).toBeEnabled();expect(tries).toBe(1);await prep(page).getByRole('button',{name:'Retry the same action'}).click();await expect(prep(page).getByRole('button',{name:'Retry the same action'})).toHaveCount(0);expect(tries).toBe(2);expect(JSON.parse(original)).toMatchObject({confirm:true,reason:'cannot_fulfill'});await expect(prep(page).locator('.rst-station-detail')).toContainText('Whole order: Preparing');
 await page.locator('.rst-preparation-owner').getByRole('button',{name:preparationCopy.en.bar,exact:true}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Original mango drink');await prep(page).getByRole('checkbox',{name:preparationCopy.en.confirm}).check();await prep(page).getByRole('combobox',{name:'Reason'}).selectOption('other');await prep(page).getByRole('button',{name:'Confirm station ready'}).click();await expect(prep(page).locator('.rst-station-detail')).toContainText('Whole order: Ready');expect(paidReads).toEqual([]);
 await page.setViewportSize({width:320,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.s3a-local/rm-v11-10f2/personal-free-320.png',fullPage:true});const storage=await page.evaluate(()=>Object.values(localStorage).concat(Object.values(sessionStorage)).join(' '));expect(storage).not.toContain('Original preference');expect(storage).not.toContain('operation_key');await page.getByRole('button',{name:'Sign out / change account'}).click();await expect(page.getByText(/Food preference: Original preference/)).toHaveCount(0);
});
