services:
  - type: web
    runtime: node
    name: nihiloba-website
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: SHIDA_API_BASE_URL
        value: https://api.nihiloba.com
