import { afterEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { POST as externalAction } from "../app/api/shida/public-jobs/[job]/external-action/route";
import { POST as analyticsEvent } from "../app/api/shida/public-jobs/[job]/[event]/route";

afterEach(()=>vi.unstubAllGlobals());

describe("external job server action boundary",()=>{
  it("keeps anonymous save state out of browser storage and session-deduplicates views",()=>{const source=readFileSync("app/components/shida/job-public-actions.tsx","utf8");expect(source).not.toContain("localStorage");expect(source).toContain("sessionStorage.getItem(key)");expect(source).toContain('event:\"view\"|\"share\"');});
  it("posts only the public job reference and expected redirect action to Backend",async()=>{const backend=vi.fn().mockResolvedValue(new Response(JSON.stringify({mode:"redirect",redirect_url:"https://careers.example/apply/42"})));vi.stubGlobal("fetch",backend);const request=new Request("https://nihiloba.com/api/shida/public-jobs/JOB_airtel/external-action",{method:"POST",headers:{origin:"https://nihiloba.com","Content-Type":"application/json"},body:JSON.stringify({action:"redirect",idempotency_key:"cta-test"})});const response=await externalAction(request,{params:Promise.resolve({job:"JOB_airtel"})});expect(response.status).toBe(200);expect(await response.json()).toEqual({mode:"redirect",redirect_url:"https://careers.example/apply/42"});expect(backend.mock.calls[0][0]).toBe("https://api.nihiloba.com/api/public/shida/jobs/JOB_airtel/external-action");expect(JSON.parse(backend.mock.calls[0][1].body)).toEqual({action:"redirect",idempotency_key:"cta-test"});});

  it("passes verified instructions but rejects unsafe redirect destinations",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({mode:"instructions",instructions:"Complete the employer form."}))).mockResolvedValueOnce(new Response(JSON.stringify({mode:"redirect",redirect_url:"javascript:alert(1)"}))));const make=(action:string)=>new Request("https://nihiloba.com/api/shida/public-jobs/JOB_airtel/external-action",{method:"POST",headers:{origin:"https://nihiloba.com","Content-Type":"application/json"},body:JSON.stringify({action})});const instructions=await externalAction(make("instructions"),{params:Promise.resolve({job:"JOB_airtel"})});expect(await instructions.json()).toEqual({mode:"instructions",instructions:"Complete the employer form."});const unsafe=await externalAction(make("redirect"),{params:Promise.resolve({job:"JOB_airtel"})});expect(unsafe.status).toBe(503);expect(JSON.stringify(await unsafe.json())).not.toContain("javascript");});

  it("maps stale backend rejection to a safe public state",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("{}",{status:409})));const request=new Request("https://nihiloba.com/api/shida/public-jobs/JOB_airtel/external-action",{method:"POST",headers:{origin:"https://nihiloba.com","Content-Type":"application/json"},body:JSON.stringify({action:"redirect"})});const response=await externalAction(request,{params:Promise.resolve({job:"JOB_airtel"})});expect(response.status).toBe(409);expect(await response.json()).toEqual({error:"job_unavailable"});});

  it("forwards only explicit view/share events and rejects unknown events",async()=>{const backend=vi.fn().mockResolvedValue(new Response(null,{status:204}));vi.stubGlobal("fetch",backend);const request=new Request("https://nihiloba.com/api/shida/public-jobs/JOB_airtel/share",{method:"POST",headers:{origin:"https://nihiloba.com"}});expect((await analyticsEvent(request,{params:Promise.resolve({job:"JOB_airtel",event:"share"})})).status).toBe(204);expect(backend).toHaveBeenCalledOnce();expect((await analyticsEvent(request,{params:Promise.resolve({job:"JOB_airtel",event:"open"})})).status).toBe(403);expect(backend).toHaveBeenCalledOnce();});
});
