import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { afterEach, describe, expect, it, vi } from "vitest";
import { JobCard, JobCollectionPage, JobDetailPage, jobMetadata } from "../app/components/shida/jobs";
import { JobPromotionLabel } from "../app/components/shida/job-promotion-label";
import { ExternalJobAction } from "../app/components/shida/job-public-actions";
import type { PublicJob, PublicJobSummary } from "../app/types/shida-public";

const employer={public_ref:"EMP_rawbank",slug:"rawbank",name:"RAWBANK",profile_image:{url:"https://res.cloudinary.com/dbrxpvmzp/image/upload/shida/jobs/rawbank.png",alt:"RAWBANK"},city:"Kinshasa",area:"Gombe",identity_type:"shida_employer" as const};
const professional:PublicJobSummary={public_ref:"JOB_support",slug:"it-support-rawbank",title:"IT Support Engineer",offer_type:"enterprise",origin:"direct",capabilities:[],professional_category:"it_telecommunications",vacancies:2,contract_type:"full_time",seniority:"mid_level",work_mode:"hybrid",work_schedule:"Monday to Friday",application_deadline:"2027-12-31",employer,location:{country_code:"CD",city:"Kinshasa",area:"Gombe",commune:"Gombe",quartier:null,display:"Gombe, Kinshasa"},description_preview:"Support users and business systems.",compensation:"500 USD",published_at:"2026-08-12T10:00:00",status:"open",lifecycle_state:"published",public_url:"https://nihiloba.com/shida/emplois/it-support-rawbank",apply_url:"https://wa.me/46769709059?text=SHIDA%20opaque-token",apply_label:"Apply on SHIDA",deadline_label:null,relationship_capabilities:{can_save:true,save_target_type:"job",save_target_ref:"JOB_support",can_share:true,can_follow_employer:false,follow_target_type:null,follow_target_ref:null},external_application_action:null,external_verified_label:null,external_verified:false,application_available:true};
const individual:PublicJobSummary={...professional,public_ref:"JOB_home",slug:"home-helper",title:"Weekend home helper",offer_type:"individual",professional_category:null,vacancies:null,contract_type:"weekend",seniority:null,work_mode:null,work_schedule:"Saturday mornings",employer:{...employer,public_ref:"EMP_person",slug:"personal-employer",name:"Employeur particulier",profile_image:null},location:{country_code:"CD",city:"Kinshasa",area:"Lemba",commune:"Lemba",quartier:"Salongo",display:"Salongo, Lemba, Kinshasa"},compensation:"50 000 CDF"};
const detail:PublicJob={...professional,description:"Provide technical support.\nMaintain secure systems.",short_summary:"Support secure business systems.",workplace_reference:"Gombe office",start_date:"2027-01-15",benefits:"Health coverage",salary:{minimum:"500",maximum:"700",currency:"USD",period:"month"},requirements_document:{available:true,url:null},public_social_link:"https://www.linkedin.com/company/rawbank",external_source:null};
const external:PublicJob={...detail,public_ref:"JOB_airtel",slug:"network-engineer-airtel",title:"IP Network Engineer",origin:"external",capabilities:["share","save","follow_employer"],employer:{public_ref:"ORG_airtel",slug:null,name:"Airtel RDC",profile_image:null,city:"Kinshasa",area:"Gombe",identity_type:"organization_directory"},apply_url:null,apply_label:"Apply",external_verified:true,external_verified_label:"Verified external offer",external_application_action:{mode:"redirect",action:"redirect",endpoint:"/api/public/shida/jobs/JOB_airtel/external-action"},relationship_capabilities:{can_save:true,save_target_type:"job",save_target_ref:"JOB_airtel",can_share:true,can_follow_employer:true,follow_target_type:"organization_directory",follow_target_ref:"ORG_airtel"},external_source:{explanation:"Originally published by the employer. SHIDA helps people discover it.",canonical_url:"https://www.airtel.cd/careers",source_label:"View official source",application_mode:"redirect",application_instructions:null,email_assisted_available:false},requirements_document:{available:false,url:null}};

afterEach(()=>vi.unstubAllGlobals());
function collection(items:unknown[]){return {items,pagination:{page:1,page_size:12,total_items:items.length,total_pages:items.length?1:0}};}

describe("Employment Batch 1 public frontend",()=>{
  it("renders compact professional and individual offers with distinct public fields",()=>{const company=renderToStaticMarkup(<JobCard item={professional} locale="en"/>),person=renderToStaticMarkup(<JobCard item={individual} locale="en"/>);expect(company).toContain("Published on SHIDA");expect(company).toContain("RAWBANK");expect(company).toContain("Hybrid");expect(company).toContain("Full time");expect(company).toContain("Apply with SHIDA");expect(person).toContain("Individual");expect(person).toContain("Saturday mornings");expect(person).toContain("Salongo, Lemba, Kinshasa");expect(person).not.toContain("rawbank.png");});

  it("groups both offer types and keeps accessible server-backed filters and pagination",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({...collection([professional,individual]),pagination:{page:2,page_size:12,total_items:14,total_pages:2}})));vi.stubGlobal("fetch",fetchMock);const html=renderToStaticMarkup(await JobCollectionPage({locale:"en",search:{query:"support",city:"Kinshasa",page:2}}));expect(fetchMock.mock.calls[0][0]).toContain("query=support&city=Kinshasa&page=2&page_size=12");expect(html).toContain("Search filters");expect(html).toContain("Company &amp; organisation offers");expect(html).toContain("Individual offers");expect(html).toContain("Page 2 of 2");expect(html).toContain('type="search"');});

  it("keeps filters visible in empty state and provides an API retry state",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(collection([])))).mockRejectedValueOnce(new Error("offline")));const empty=renderToStaticMarkup(await JobCollectionPage({locale:"fr",search:{query:"introuvable"}})),error=renderToStaticMarkup(await JobCollectionPage({locale:"en",search:{}}));expect(empty).toContain("Aucune offre ouverte");expect(empty).toContain("Tout effacer");expect(error).toContain('role="alert"');expect(error).toContain("Try again");});

  it("renders professional detail, visible salary, benefits, dates and private PDF availability",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify(detail))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"detail"}));for(const value of ["IT Support Engineer","RAWBANK","Hybrid","Full time","Mid level","Monday to Friday","2","500–700 USD / month","Health coverage","Requirements document","Apply on SHIDA","Share","Report offer"])expect(html).toContain(value);expect(html).not.toContain("storage_path");expect(html).not.toContain("job_requirement_pdf_url");});

  it("does not duplicate the localized deadline label when no date is provided",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,application_deadline:null,deadline_label:"Date limite : Non précisée"}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"fr",slug:"sans-date"}));expect(html).toContain("Date limite : Non précisée");expect(html).not.toContain("Date limite:</strong> Date limite");});

  it("does not invent a salary or verification indicator when the backend omits them",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,salary:null,compensation:null,requirements_document:{available:false,url:null}}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"hidden-salary"}));expect(html).not.toContain("500–700");expect(html).not.toContain("Verified");expect(html).not.toContain("Requirements document");});

  it("uses backend lifecycle state instead of calculating expiration from dates",()=>{const html=renderToStaticMarkup(<JobCard item={{...professional,status:"expired",lifecycle_state:"expired",application_available:false,application_deadline:"2020-01-01",featured:true,promotion_days:30} as PublicJobSummary} locale="en"/>);expect(html).toContain("Applications closed");expect(html).not.toContain("Apply with SHIDA");expect(html).not.toContain("Featured");expect(html).not.toContain("Sponsored");});

  it("prepares authoritative 7, 14 and 30 day promotion labels without showing expired placements",()=>{const now=new Date("2026-08-30").getTime();for(const duration_days of [7,14,30] as const){const html=renderToStaticMarkup(<JobPromotionLabel locale="fr" promotion={{duration_days,starts_at:"2099-01-01",ends_at:"2099-01-30"}} applicationDeadline="2099-02-01" now={now}/>);expect(html).toContain("À la une");}const expired=renderToStaticMarkup(<JobPromotionLabel locale="en" promotion={{duration_days:7,starts_at:"2020-01-01",ends_at:"2020-01-08"}} applicationDeadline="2020-02-01" now={now}/>);expect(expired).toBe("");});

  it("never renders phone numbers, exact addresses, private email or unknown backend fields",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,recruiter_phone:"+46700000000",recruiter_email:"private@example.com",exact_address:"12 Secret Avenue",avenue:"Secret Avenue",parcel_number:"12",candidate_names:["PRIVATE"]}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"privacy"}));for(const secret of ["+46700000000","private@example.com","12 Secret Avenue","Secret Avenue","candidate_names","PRIVATE"])expect(html).not.toContain(secret);expect(html).toContain("opaque-token");});

  it("rejects unsafe apply URLs without constructing a phone-based replacement",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,apply_url:"javascript:alert(1)"}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"fr",slug:"unsafe"}));expect(html).toContain("Les candidatures ne sont pas disponibles");expect(html).not.toContain("Postuler avec SHIDA");expect(html).not.toContain("javascript:");});

  it("keeps apply tokens out of SEO metadata and canonicalizes the existing route",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify(detail))));const metadata=await jobMetadata("en","metadata"),serialized=JSON.stringify(metadata);expect(metadata.alternates?.canonical).toBe("/shida/emplois/it-support-rawbank");expect(serialized).not.toContain("opaque-token");expect(serialized).not.toContain("apply_url");});

  it("renders active external jobs with controlled application, source, save and follow continuations",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(external))).mockResolvedValueOnce(new Response(JSON.stringify({target_type:"job",public_ref:"JOB_airtel",can_save_in_shida:true,can_follow_in_shida:false,save_url:"https://api.nihiloba.com/go/save_job_opaque",follow_url:null}))).mockResolvedValueOnce(new Response(JSON.stringify({target_type:"organization_directory",public_ref:"ORG_airtel",can_save_in_shida:false,can_follow_in_shida:true,save_url:null,follow_url:"https://api.nihiloba.com/go/follow_org_opaque"})));vi.stubGlobal("fetch",fetchMock);const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"network-engineer"}));for(const value of ["Verified external offer","Apply on employer website","Originally published by the employer","View official source","Save in SHIDA","Follow on SHIDA · Airtel RDC"]){expect(html).toContain(value);}expect(html).not.toContain("Apply on SHIDA");expect(html).not.toContain("recruiter");expect(html).not.toContain("application status");});

  it("renders backend expired and archived projections without an application CTA",async()=>{for(const status of ["expired","archived","source_invalid"] as const){const historical={...external,status,lifecycle_state:status,application_available:false,external_application_action:null,application_deadline:status==="expired"?"2026-08-31":null,deadline_label:status==="expired"?null:"Deadline not provided",relationship_capabilities:{...external.relationship_capabilities,can_save:false,can_follow_employer:false,follow_target_type:null,follow_target_ref:null}};vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify(historical))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:status}));expect(html).toContain(status==="expired"?"Expired offer":"This offer is no longer active.");expect(html).not.toContain("Apply on employer website");expect(html).not.toContain("Invalid Date");expect(html).toContain("View similar jobs");}});

  it("uses the external instructions mode and hides disabled email-assisted actions",()=>{const instructions=renderToStaticMarkup(<ExternalJobAction locale="en" jobReference="JOB_airtel" action={{mode:"instructions",action:"instructions",endpoint:"/api/public/shida/jobs/JOB_airtel/external-action"}}/>),disabled=renderToStaticMarkup(<JobCard item={{...external,application_available:false,external_application_action:null}} locale="en"/>);expect(instructions).toContain("See how to apply");expect(disabled).not.toContain("Apply on employer website");});

  it("provides EN/FR collection, detail and accessible loading routes",()=>{for(const path of ["app/(default)/shida/emplois/page.tsx","app/(default)/shida/emplois/[job]/page.tsx","app/(default)/shida/emplois/loading.tsx","app/(localized)/[lang]/shida/emplois/page.tsx","app/(localized)/[lang]/shida/emplois/[job]/page.tsx","app/(localized)/[lang]/shida/emplois/loading.tsx"])expect(existsSync(resolve(path)),path).toBe(true);});
});
