import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { afterEach, describe, expect, it, vi } from "vitest";
import { JobCard, JobCollectionPage, JobDetailPage, JobEmployerPage, jobMetadata } from "../app/components/shida/jobs";
import { MarketplaceGateway } from "../app/components/shida/marketplace";
import type { PublicJobSummary } from "../app/types/shida-public";

const employer={public_ref:"EMP_rawbank",slug:"rawbank",name:"RAWBANK",profile_image:{url:"https://res.cloudinary.com/dbrxpvmzp/image/upload/shida/jobs/rawbank.png",alt:"RAWBANK"},city:"Kinshasa",area:"Gombe"};
const job:PublicJobSummary={public_ref:"JOB_support",slug:"it-support-rawbank",title:"IT Support Engineer",employer,location:{country_code:"CD",city:"Kinshasa",area:"Gombe",commune:"Gombe",quartier:null,display:"Gombe, Kinshasa"},description_preview:"Support users, devices and business systems across the organisation.",compensation:"500 USD",published_at:"2026-08-12T10:00:00",status:"open",public_url:"https://nihiloba.com/shida/emplois/it-support-rawbank",apply_url:"https://wa.me/46769709059?text=SHIDA%20opaque-token",apply_label:{fr:"Postuler sur SHIDA",en:"Apply on SHIDA"}};
const detail={...job,description:"Provide technical support.\nMaintain secure systems.",requirements_document:{available:true,url:null},public_social_link:"https://www.linkedin.com/company/rawbank"};

afterEach(()=>vi.unstubAllGlobals());

describe("public Jobs marketplace",()=>{
  it("renders a text-led job card with employer identity, image, title, location and compensation",()=>{const html=renderToStaticMarkup(<JobCard item={job} locale="en"/>);expect(html).toContain("rawbank.png");expect(html).toContain('alt="RAWBANK"');expect(html).toContain("IT Support Engineer");expect(html).toContain("Gombe, Kinshasa");expect(html).toContain("500 USD");expect(html).toContain("Support users");expect(html).toContain("View job");expect(html.indexOf("RAWBANK")).toBeLessThan(html.indexOf("IT Support Engineer"));});

  it("uses a clean employer fallback and omits missing optional fields",()=>{const html=renderToStaticMarkup(<JobCard item={{...job,employer:{...employer,name:"Jean Employeur",profile_image:null},location:{country_code:null,city:null,area:null,commune:null,quartier:null,display:null},description_preview:null,compensation:null,published_at:null}} locale="fr"/>);expect(html).toContain("JE");expect(html).toContain("Jean Employeur");expect(html).not.toContain("500 USD");expect(html).not.toContain("null");});

  it("uses backend search, compact filters, results and pagination",async()=>{const paged={items:[job,{...job,public_ref:"JOB_barista",slug:"barista-cafe",title:"Barista"}],pagination:{page:2,page_size:12,total_items:14,total_pages:2}};const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify(paged)));vi.stubGlobal("fetch",fetchMock);const html=renderToStaticMarkup(await JobCollectionPage({locale:"en",search:{query:"rawbank",city:"Kinshasa",page:2}}));expect(fetchMock.mock.calls[0][0]).toContain("query=rawbank&city=Kinshasa&page=2&page_size=12");expect(html).toContain("Search jobs or employers");expect(html).toContain("Location filters");expect(html).toContain("14 open jobs");expect(html).toContain("IT Support Engineer");expect(html).toContain("Barista");expect(html).toContain("Page 2 of 2");expect(html).toContain("Previous");});

  it("keeps filters usable when no jobs match",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({items:[],pagination:{page:1,page_size:12,total_items:0,total_pages:0}}))));const html=renderToStaticMarkup(await JobCollectionPage({locale:"fr",search:{query:"introuvable"}}));expect(html).toContain("Rechercher un poste ou un employeur");expect(html).toContain("Aucune offre ne correspond à votre recherche");expect(html).toContain("Effacer les filtres");});

  it("renders exactly two safe Apply CTAs around the meaningful job content",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,recruiter_phone:"PRIVATE",recruiter_email:"PRIVATE",poster_id:99,candidate_names:["PRIVATE"],requirements_document:{available:true,url:null,storage_path:"PRIVATE"}}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"safe-job-detail"})),firstApply=html.indexOf("Apply on SHIDA"),description=html.indexOf("About this job"),employerSection=html.lastIndexOf(">Employer<"),finalHeading=html.indexOf("Interested in this job?"),lastApply=html.lastIndexOf("Apply on SHIDA");expect(html).toContain("IT Support Engineer");expect(html).toContain("RAWBANK");expect(html).toContain("Published August 12, 2026");expect(html).toContain("Compensation:");expect(html).toContain("500 USD");expect(html).toContain("Provide technical support");expect(html).toContain("Maintain secure systems");expect(html).toContain("Additional requirements information will be provided in SHIDA");expect((html.match(/Apply on SHIDA/g)||[])).toHaveLength(2);expect((html.match(/opaque-token/g)||[])).toHaveLength(2);expect(firstApply).toBeLessThan(description);expect(description).toBeLessThan(employerSection);expect(employerSection).toBeLessThan(finalHeading);expect(finalHeading).toBeLessThan(lastApply);expect(html).not.toContain("Continue in SHIDA to submit your application securely");expect(html).not.toContain("marketplace-action-card");expect(html).toContain('target="_blank"');expect(html).toContain('rel="noopener noreferrer"');for(const privateValue of ["PRIVATE","poster_id","candidate_names","storage_path"])expect(html).not.toContain(privateValue);});

  it("localizes both remaining actions and job interface without translating authored content",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,public_ref:"JOB_french",slug:"french-job"}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"fr",slug:"french-job-detail"}));expect((html.match(/Postuler sur SHIDA/g)||[])).toHaveLength(2);for(const label of ["💼 Emplois","Publié le","À propos du poste","Employeur","Profil de l’employeur","Intéressé par cette offre ?"])expect(html).toContain(label);expect(html).toContain("Provide technical support");expect(html.indexOf("Postuler sur SHIDA")).toBeLessThan(html.indexOf("À propos du poste"));expect(html.lastIndexOf("Postuler sur SHIDA")).toBeGreaterThan(html.lastIndexOf("Profil de l’employeur"));});

  it("rejects an unsafe apply URL and never constructs or enables a replacement",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,public_ref:"JOB_unsafe",slug:"unsafe",apply_url:"javascript:alert(1)"}))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"unsafe-job-detail"}));expect((html.match(/Applications are temporarily unavailable/g)||[])).toHaveLength(1);expect(html).not.toContain("Apply on SHIDA");expect(html).not.toContain("Interested in this job?");expect(html).not.toContain("javascript:");expect(html).not.toContain("wa.me/46769709059");});

  it("keeps the employer section informational and both mobile actions prominent",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify(detail))));const html=renderToStaticMarkup(await JobDetailPage({locale:"en",slug:"employer-card-detail"})),employerStart=html.lastIndexOf("<section><h2>Employer</h2>"),finalStart=html.indexOf('<section class="job-final-action">'),employerHtml=html.slice(employerStart,finalStart),css=readFileSync("app/globals.css","utf8");expect(employerStart).toBeGreaterThan(-1);expect(finalStart).toBeGreaterThan(employerStart);expect(employerHtml).toContain("Employer profile");expect(employerHtml).not.toContain("Apply on SHIDA");expect(css).toContain(".job-hero-action .button, .job-final-action .button { width: 100%; }");});

  it("renders a clean unavailable job without an Apply action",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("missing",{status:404})));const html=renderToStaticMarkup(await JobDetailPage({locale:"fr",slug:"closed-job"}));expect(html).toContain("Cette offre n’est plus disponible");expect(html).toContain("Retour aux offres");expect(html).not.toContain("Postuler sur SHIDA");});

  it("renders employer profiles for multiple or zero open jobs without private identity data",async()=>{const profile={...employer,description:"Institution financière publique.",open_job_count:2,jobs:[job,{...job,public_ref:"JOB_accountant",slug:"accountant",title:"Accountant"}],owner_phone:"PRIVATE",business_id:8};const empty={...employer,public_ref:"EMP_empty",slug:"empty",name:"Employeur Local",profile_image:null,description:null,open_job_count:0,jobs:[]};vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(profile))).mockResolvedValueOnce(new Response(JSON.stringify(empty))));const full=renderToStaticMarkup(await JobEmployerPage({locale:"fr",slug:"employer-full"})),none=renderToStaticMarkup(await JobEmployerPage({locale:"en",slug:"employer-empty"}));expect(full).toContain("<h1");expect(full).toContain("RAWBANK");expect(full).toContain("Offres ouvertes (2)");expect(full).toContain("IT Support Engineer");expect(full).toContain("Accountant");expect(full).not.toContain("PRIVATE");expect(full).not.toContain("business_id");expect(none).toContain("Employeur Local");expect(none).toContain("has no open jobs");expect(none).toContain("EL");});

  it("keeps apply tokens out of SEO metadata and uses the canonical NIHILOBA job URL",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({...detail,public_ref:"JOB_meta",slug:"meta-job"}))));const metadata=await jobMetadata("en","job-metadata-test"),serialized=JSON.stringify(metadata);expect(metadata.alternates?.canonical).toBe("/shida/emplois/meta-job");expect(serialized).toContain("IT Support Engineer at RAWBANK");expect(serialized).toContain("rawbank.png");expect(serialized).not.toContain("opaque-token");expect(serialized).not.toContain("apply_url");});

  it("adds Jobs to the SHIDA gateway in English and French",()=>{const en=renderToStaticMarkup(<MarketplaceGateway locale="en"/>),fr=renderToStaticMarkup(<MarketplaceGateway locale="fr"/>);expect(en).toContain('href="/shida/emplois"');expect(en).toContain("💼 Jobs");expect(fr).toContain('href="/fr/shida/emplois"');expect(fr).toContain("💼 Emplois");});

  it("provides every default and localized Jobs route",()=>{for(const path of ["app/(default)/shida/emplois/page.tsx","app/(default)/shida/emplois/[job]/page.tsx","app/(default)/shida/emplois/employeurs/[employer]/page.tsx","app/(localized)/[lang]/shida/emplois/page.tsx","app/(localized)/[lang]/shida/emplois/[job]/page.tsx","app/(localized)/[lang]/shida/emplois/employeurs/[employer]/page.tsx"])expect(existsSync(resolve(path)),path).toBe(true);});
});
