import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ServiceAvailabilityPanel, serviceSlotActionUrl } from "../app/components/shida/service-availability";
import { ServiceCard, ServiceDetailPage, ServiceProviderPage, serviceAvailabilityRange, serviceDuration } from "../app/components/shida/services";
import { ImageGallery } from "../app/components/shida/image-gallery";
import type { PublicServiceSummary, ServiceAvailability } from "../app/types/shida-public";

const image={url:"https://res.cloudinary.com/dbrxpvmzp/image/upload/shida/services/work.jpg",alt:"Consultation work"};
const location={country_code:"CD",city:"Kinshasa",area:null,commune:"Gombe",quartier:"Cliniques",address_visibility:"public" as const,address:"Avenue Publique 10",landmark:"Centre"};
const summary:PublicServiceSummary={public_ref:"SVC-1",slug:"consultation",provider:{public_ref:"SVP-1",slug:"patrick",name:"Patrick Mbuyi",profile_image:{...image,url:"https://res.cloudinary.com/dbrxpvmzp/image/upload/shida/services/provider.jpg",alt:"Patrick Mbuyi"}},service_name:"Consultation générale",category:"health",short_description:"Public summary",duration_minutes:90,starting_price:{name:"Standard",duration_minutes:90,price:"50 000 CDF",currency:"USD",description:null},location,location_type:"public_place",external_intervention_available:true,availability_mode:"time_slots",rating:{average_rating:4.8,rating_count:17},image_preview:image,public_detail_url:"https://nihiloba.com/shida/services/consultation",booking_url:"https://wa.me/service"};
const fixed:ServiceAvailability={service_ref:"SVC-1",availability_mode:"time_slots",requested_time_requires_provider_confirmation:true,from:"2026-08-12",to:"2026-09-11",slots:[{date:"2026-08-12",start_time:"10:30",end_time:"11:00",is_available:true,booking_url:"https://wa.me/exact-slot"},{date:"2026-08-13",start_time:"11:00",end_time:"11:30",is_available:false,booking_url:"https://wa.me/unavailable-slot"}],booking_url:null};

afterEach(()=>vi.unstubAllGlobals());

describe("public Services marketplace",()=>{
  it("renders service work first with a smaller provider identity and actual public facts",()=>{const html=renderToStaticMarkup(<ServiceCard item={summary} locale="en"/>);expect(html).toContain("work.jpg");expect(html).toContain("provider.jpg");expect(html).toContain("Patrick Mbuyi");expect(html).toContain("Consultation générale");expect(html).toContain("Health");expect(html).toContain("Cliniques, Gombe, Kinshasa");expect(html).toContain("1 h 30");expect(html).toContain("50 000 CDF");expect(html).not.toContain("50 000 CDF USD");expect(html).toContain("4.8/5 (17)");expect(html).toContain("At provider or customer location");});
  it("uses safe fallbacks and omits absent rating, price and duration",()=>{const html=renderToStaticMarkup(<ServiceCard item={{...summary,image_preview:null,provider:{...summary.provider,profile_image:null},rating:{average_rating:null,rating_count:0},starting_price:null,duration_minutes:null}} locale="fr"/>);expect(html).toContain("Image du service indisponible");expect(html).not.toContain("0/5");expect(html).not.toContain("50 000");});
  it("handles zero, one and five work images without a heavy carousel",()=>{const none=renderToStaticMarkup(<ImageGallery images={[]} title="Service" fallback="Fallback" photosLabel="Photos"/>),one=renderToStaticMarkup(<ImageGallery images={[image]} title="Service" fallback="Fallback" photosLabel="Photos"/>),five=renderToStaticMarkup(<ImageGallery images={Array.from({length:5},(_,index)=>({...image,url:`${image.url}?v=${index}`}))} title="Service" fallback="Fallback" photosLabel="Photos"/>);expect(none).toContain("Fallback");expect(one).not.toContain("marketplace-thumbnails");expect(five).toContain("1 / 5");expect((five.match(/marketplace-thumbnail/g)||[]).length).toBeGreaterThanOrEqual(5);});
  it("keeps the availability range to exactly 31 inclusive days and preserves an explicit next range",()=>{expect(serviceAvailabilityRange(undefined,new Date("2026-08-12T12:00:00Z"))).toEqual({from:"2026-08-12",to:"2026-09-11"});expect(serviceAvailabilityRange("2026-09-12",new Date("2026-08-12T12:00:00Z"))).toEqual({from:"2026-09-12",to:"2026-10-12"});expect(serviceDuration(30)).toBe("30 min");expect(serviceDuration(90)).toBe("1 h 30");});
  it("distinguishes fixed slots, disables dates without availability and requires selection",()=>{const html=renderToStaticMarkup(<ServiceAvailabilityPanel locale="en" availability={fixed} bookingUrl={summary.booking_url} path="/shida/services/consultation"/>);expect(html).toContain("Choose a date and time");expect(html).toContain("disabled");expect(html).toContain("unavailable");expect(html).toContain("Select an available time");expect(html).toContain("The provider will confirm");expect(html).not.toContain("exact-slot");expect(serviceSlotActionUrl("https://wa.me/exact-slot")).toBe("https://wa.me/exact-slot");expect(serviceSlotActionUrl("javascript:alert(1)")).toBeNull();});
  it("renders a clear no-slots state with next-period navigation",()=>{const html=renderToStaticMarkup(<ServiceAvailabilityPanel locale="fr" availability={{...fixed,slots:[]}} bookingUrl={summary.booking_url} path="/fr/shida/services/consultation"/>);expect(html).toContain("Aucun créneau disponible pour cette période");expect(html).toContain("31 jours suivants");expect(html).toContain("from=2026-09-12");});
  it("keeps flexible availability out of the slot UI and uses the standard service URL",()=>{const flexible:ServiceAvailability={service_ref:"SVC-2",availability_mode:"flexible",requested_time_requires_provider_confirmation:true,from:null,to:null,slots:[],booking_url:"https://wa.me/flexible-service"};const html=renderToStaticMarkup(<ServiceAvailabilityPanel locale="en" availability={flexible} bookingUrl="https://wa.me/fallback" path="/shida/services/flexible"/>);expect(html).toContain("agree on a time");expect(html).toContain("provider will confirm");expect(html).toContain("https://wa.me/flexible-service");expect(html).not.toContain("service-date-grid");expect(html).not.toContain("slot=");});
  it("renders provider public addresses but never a private address",async()=>{const provider={public_ref:"SVP-1",slug:"patrick",name:"Patrick Mbuyi",profile_image:summary.provider.profile_image,location,categories:["health"],service_count:1,rating:summary.rating,services:[summary],phone:"private-phone",owner_id:77};vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(provider))).mockResolvedValueOnce(new Response(JSON.stringify({...provider,slug:"private-provider",location:{...location,address_visibility:"private",address:"SECRET HOME",landmark:"SECRET LANDMARK"},services:[]}))));const publicHtml=renderToStaticMarkup(await ServiceProviderPage({locale:"en",slug:"patrick-provider-render"})),privateHtml=renderToStaticMarkup(await ServiceProviderPage({locale:"fr",slug:"private-provider-render"}));expect(publicHtml).toContain("Avenue Publique 10");expect(publicHtml).toContain("Centre");expect(publicHtml).toContain("Consultation générale");expect(publicHtml).not.toContain("private-phone");expect(publicHtml).not.toContain("owner_id");expect(privateHtml).not.toContain("SECRET HOME");expect(privateHtml).not.toContain("SECRET LANDMARK");expect(privateHtml).toContain("Aucun service public");});
  it("renders ordered galleries, packages and safe external links while surviving availability failure",async()=>{const detail={...summary,description:"First line\nSecond line",offerings:[summary.starting_price],images:Array.from({length:5},(_,index)=>({...image,url:`https://res.cloudinary.com/dbrxpvmzp/image/upload/shida/services/${index+1}.jpg`,alt:`Work ${index+1}`})),social_link:"https://example.com/patrick",completion_mode:null,availability_endpoint:"/api/public/shida/services/consultation/availability",provider_phone:"PRIVATE",internal_schedule_id:123};vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(detail))).mockResolvedValueOnce(new Response("down",{status:503})));const html=renderToStaticMarkup(await ServiceDetailPage({locale:"en",slug:"consultation-render",from:"2026-08-12"}));expect(html).toContain("1 / 5");expect(html.indexOf("1.jpg")).toBeLessThan(html.indexOf("5.jpg"));expect(html).toContain("First line");expect(html).toContain("Second line");expect(html).toContain("Service options");expect(html).toContain("50 000 CDF");expect(html).toContain("1 h 30");expect(html).toContain("https://example.com/patrick");expect(html).toContain("Availability could not be loaded");expect(html).not.toContain("PRIVATE");expect(html).not.toContain("internal_schedule_id");});
  it("has all English and French route files",()=>{for(const path of ["app/(default)/shida/services/page.tsx","app/(default)/shida/services/[service]/page.tsx","app/(default)/shida/services/providers/[provider]/page.tsx","app/(localized)/[lang]/shida/services/page.tsx","app/(localized)/[lang]/shida/services/[service]/page.tsx","app/(localized)/[lang]/shida/services/providers/[provider]/page.tsx"])expect(existsSync(resolve(path)),path).toBe(true);});
});
