import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { ProductCard } from "../app/components/shida/wenze";
import { formatCommerceMoney } from "../app/components/shida/wenze-cart-page";
import { WenzeCartPage } from "../app/components/shida/wenze-cart-page";
import { CartProvider } from "../app/components/shida/cart-provider";
import { commerceErrorMessage, wenzeCartCopy, wenzeCartPath } from "../app/components/shida/wenze-cart-copy";
import type { WenzeProduct } from "../app/types/shida-public";
import type { CommerceCart } from "../app/types/shida-commerce";
import { metadata as englishMetadata } from "../app/(default)/shida/wenze/cart/page";
import { metadata as frenchMetadata } from "../app/(localized)/[lang]/shida/wenze/panier/page";

const product:WenzeProduct={public_ref:"WNP-FIXED",slug:"fixed",name:"Fixed product",description:null,category:null,price:"20",currency:"USD",price_negotiable:false,available_stock:2,has_variants:false,variant_type:null,variants:[],images:[],public_detail_url:"https://nihiloba.com/shida/wenze/products/fixed",buy_url:"https://wa.me/old-fixed",store:null,fulfillment:{methods:["pickup"],delivery:null}};
const cart:CommerceCart={reference:"SH-CART",status:"active",currency:"USD",version:2,item_count:3,seller_count:2,product_subtotal:"60.00",delivery_total:null,grand_total:null,expires_at:"2026-09-20T00:00:00Z",seller_groups:[{store_reference:"WNZ-A",store_name:"Store A",subtotal:"40.00",currency:"USD",fulfillment_method:null,delivery_fee:null,delivery_fee_status:null,items:[{reference:"SH-CI-A",product_reference:"WNP-A",name:"Product A",variant:null,quantity:2,unit_price:"20.00",line_total:"40.00",currency:"USD",image:null,product_url:"https://nihiloba.com/shida/wenze/products/a"}]},{store_reference:"WNZ-B",store_name:"Store B",subtotal:"20.00",currency:"USD",fulfillment_method:null,delivery_fee:null,delivery_fee_status:null,items:[{reference:"SH-CI-B",product_reference:"WNP-B",name:"Product B",variant:"Large",quantity:1,unit_price:"20.00",line_total:"20.00",currency:"USD",image:null,product_url:null}]}]};

describe("Wenze cart presentation",()=>{
  it("does not send malformed legacy prices into the fixed-price cart",()=>{const html=renderToStaticMarkup(<ProductCard p={{...product,price:"30 USD",currency:"CDF"}} l="en"/>);expect(html).toContain("30 USD");expect(html).toContain("View product");expect(html).not.toContain("Add to cart")});
  it("adds fixed products to the shared cart and keeps negotiable products on WhatsApp",()=>{const fixed=renderToStaticMarkup(<ProductCard p={product} l="en"/>),negotiable=renderToStaticMarkup(<ProductCard p={{...product,price_negotiable:true,buy_url:"https://wa.me/negotiate"}} l="fr"/>);expect(fixed).toContain("Add to cart");expect(fixed).toContain("Buy now");expect(fixed).not.toContain("old-fixed");expect(negotiable).toContain("Négocier sur WhatsApp");expect(negotiable).toContain("https://wa.me/negotiate");expect(negotiable).not.toContain("Ajouter au panier")});
  it("provides localized routes, handoff explanation, and conflict messages",()=>{expect(wenzeCartPath("en")).toBe("/shida/wenze/cart");expect(wenzeCartPath("fr")).toBe("/fr/shida/wenze/panier");expect(wenzeCartCopy.en.handoffHelp).toContain("delivery or pickup");expect(wenzeCartCopy.fr.handoffHelp).toContain("WhatsApp");expect(commerceErrorMessage("fr","insufficient_stock")).toContain("quantité")});
  it("formats backend-returned totals without calculating cart authority",()=>{expect(formatCommerceMoney("1250.00","CDF","fr")).toContain("1");expect(formatCommerceMoney("20.50","USD","en")).toContain("20.50 USD")});
  it("renders one cart grouped by multiple sellers with accessible quantity controls",()=>{const html=renderToStaticMarkup(<CartProvider initialCart={cart} restoreOnMount={false}><WenzeCartPage locale="en"/></CartProvider>);expect(html).toContain("Store A");expect(html).toContain("Store B");expect(html).toContain("Product A");expect(html).toContain("Large");expect(html).toContain('aria-label="Decrease quantity: Product A"');expect(html).toContain('aria-label="Increase quantity: Product B"');expect(html).toContain("Calculated in WhatsApp");expect(html).toContain("Continue on WhatsApp");expect(html).not.toContain("SH-CART");expect(html).not.toContain("SH-CI-A")});
  it("renders localized empty and populated cart states",()=>{const empty=renderToStaticMarkup(<CartProvider restoreOnMount={false}><WenzeCartPage locale="fr"/></CartProvider>),oneSeller=renderToStaticMarkup(<CartProvider initialCart={{...cart,item_count:2,seller_count:1,seller_groups:[cart.seller_groups[0]]}} restoreOnMount={false}><WenzeCartPage locale="fr"/></CartProvider>);expect(empty).toContain("Votre panier est vide");expect(oneSeller).toContain("Sous-total boutique");expect(oneSeller).toContain("Continuer sur WhatsApp")});
  it("keeps both private cart pages out of search indexes",()=>{expect(englishMetadata.robots).toMatchObject({index:false,follow:false});expect(frenchMetadata.robots).toMatchObject({index:false,follow:false})});
});
