import type { Metadata } from "next";
import Link from "next/link";
import type { Locale } from "../../lib/i18n";
import { safePublicActionUrl, safePublicExternalUrl, safePublicImageUrl } from "../../lib/safe-public-url";
import { getJob, getJobEmployer, getJobs, getPublicEntityActions, jobSearchQuery, ShidaApiError } from "../../services/shida/public-client";
import type { JobCollection, JobSearch, PublicJob, PublicJobEmployer, PublicJobEmployerSummary, PublicJobSalary, PublicJobSummary } from "../../types/shida-public";
import { ButtonLink } from "../button-link";
import { ExternalJobAction, JobPublicActions, JobViewTracker } from "./job-public-actions";
import { MarketplaceImage } from "./marketplace-image";
import { MarketplaceBreadcrumb, MarketplaceSectionBreadcrumb } from "./marketplace-primitives";
import { marketplacePath, MarketplaceState, publicLocation } from "./marketplace";

const copy = {
  en: { jobs:"Jobs",title:"Find work with SHIDA",intro:"Explore professional opportunities and trusted local work, then apply securely through SHIDA.",professional:"Company & organisation offers",individual:"Individual offers",professionalShort:"Professional",individualShort:"Individual",search:"Search jobs",placeholder:"Job title, organisation or keyword",city:"City",area:"Area",commune:"Commune",filters:"Search filters",applyFilters:"Show jobs",clear:"Clear all",result:"open offer",results:"open offers",empty:"No open offers match these filters.",emptyProfessional:"There are no company or organisation vacancies available right now. Please check back later or explore another SHIDA marketplace.",emptyIndividual:"There are no individual vacancies available right now. Please check back later or explore another SHIDA marketplace.",exploreMarketplaces:"Explore other SHIDA marketplaces",unavailable:"Jobs are temporarily unavailable.",retry:"Try again",details:"View offer",employer:"Organisation",location:"Location",compensation:"Compensation",published:"Published",deadline:"Apply by",closed:"Applications closed",description:"About this role",requirements:"Requirements document",requirementsDocument:"A supporting PDF is available securely during the SHIDA application journey.",apply:"Apply with SHIDA",finalApply:"Ready to apply?",actionUnavailable:"Applications are not available for this offer.",employerProfile:"View organisation offers",openJobs:"Open offers",noEmployerJobs:"This employer has no open offers right now.",employerUnavailable:"This employer profile is unavailable.",jobUnavailable:"This offer is no longer available.",back:"Back to jobs",previous:"Previous",next:"Next",page:"Page",of:"of",image:"Organisation logo unavailable",external:"Public organisation profile",contract:"Contract",experience:"Experience",schedule:"Schedule",mode:"Work mode",vacancies:"Vacancies",start:"Expected start",benefits:"Benefits",salary:"Salary",personalEmployer:"Personal employer"},
  fr: { jobs:"Emplois",title:"Trouvez un emploi avec SHIDA",intro:"Découvrez des opportunités professionnelles et des travaux locaux, puis postulez en toute sécurité via SHIDA.",professional:"Offres d’entreprises et d’organisations",individual:"Offres de particuliers",professionalShort:"Professionnel",individualShort:"Particulier",search:"Rechercher",placeholder:"Poste, organisation ou mot-clé",city:"Ville",area:"Zone",commune:"Commune",filters:"Filtres de recherche",applyFilters:"Afficher les offres",clear:"Tout effacer",result:"offre ouverte",results:"offres ouvertes",empty:"Aucune offre ouverte ne correspond à ces filtres.",emptyProfessional:"Aucune offre d’entreprise ou d’organisation n’est disponible actuellement. Revenez plus tard ou explorez un autre marché SHIDA.",emptyIndividual:"Aucune offre de particulier n’est disponible actuellement. Revenez plus tard ou explorez un autre marché SHIDA.",exploreMarketplaces:"Explorer les autres marchés SHIDA",unavailable:"Les offres sont temporairement indisponibles.",retry:"Réessayer",details:"Voir l’offre",employer:"Organisation",location:"Lieu",compensation:"Rémunération",published:"Publiée le",deadline:"Date limite",closed:"Candidatures clôturées",description:"À propos du poste",requirements:"Document des exigences",requirementsDocument:"Un PDF complémentaire est disponible de manière sécurisée pendant la candidature SHIDA.",apply:"Postuler avec SHIDA",finalApply:"Prêt à postuler ?",actionUnavailable:"Les candidatures ne sont pas disponibles pour cette offre.",employerProfile:"Voir les offres de l’organisation",openJobs:"Offres ouvertes",noEmployerJobs:"Cet employeur n’a aucune offre ouverte actuellement.",employerUnavailable:"Ce profil employeur est indisponible.",jobUnavailable:"Cette offre n’est plus disponible.",back:"Retour aux offres",previous:"Précédent",next:"Suivant",page:"Page",of:"sur",image:"Logo de l’organisation indisponible",external:"Profil public de l’organisation",contract:"Contrat",experience:"Expérience",schedule:"Horaire",mode:"Mode de travail",vacancies:"Postes",start:"Début prévu",benefits:"Avantages",salary:"Salaire",personalEmployer:"Employeur particulier"},
} as const;

const detailCopy = {
  en: { summary:"Summary",responsibilities:"Responsibilities",qualifications:"Qualifications",experience:"Experience",education:"Education and training",skills:"Skills",qualities:"Personal qualities",languages:"Languages",benefits:"Benefits",conditions:"Employment conditions",social:"Public employer link",source:"Offer source",overview:"Offer overview",years:(value:number)=>`${value} year${value===1?"":"s"} minimum` },
  fr: { summary:"Résumé",responsibilities:"Responsabilités",qualifications:"Profil recherché",experience:"Expérience",education:"Études et formation",skills:"Compétences",qualities:"Qualités personnelles",languages:"Langues",benefits:"Avantages",conditions:"Conditions d’emploi",social:"Lien public de l’employeur",source:"Source de l’offre",overview:"Aperçu de l’offre",years:(value:number)=>`${value} an${value===1?"":"s"} minimum` },
} as const;

function jobPath(locale:Locale,item:Pick<PublicJobSummary,"slug"|"public_ref">){return marketplacePath(locale,`/shida/emplois/${encodeURIComponent(item.slug||item.public_ref)}`);}
function employerPath(locale:Locale,item:Pick<PublicJobEmployerSummary,"slug"|"public_ref">){return marketplacePath(locale,`/shida/emplois/employeurs/${encodeURIComponent(item.slug||item.public_ref)}`);}
function jobLocation(item:PublicJobSummary){return item.location.display||publicLocation(item.location.quartier,item.location.commune,item.location.area,item.location.city);}
function employerLocation(item:PublicJobEmployerSummary){return publicLocation(item.area,item.city);}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]?.toUpperCase()).join("")||"SH";}
function displayDate(value:string|null,locale:Locale){if(!value)return null;const date=new Date(value);return Number.isNaN(date.getTime())?null:new Intl.DateTimeFormat(locale,{day:"numeric",month:"short",year:"numeric"}).format(date);}
function isOpen(item:PublicJobSummary){return item.application.available;}
function originLabel(item:PublicJobSummary,locale:Locale){return item.origin==="external"?(item.external_verified_label||(locale==="fr"?"Offre externe vérifiée":"Verified external offer")):(locale==="fr"?"Publié sur SHIDA":"Published on SHIDA");}
function humanize(value:string|null){return value?value.replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase()):null;}
function salaryText(salary:PublicJobSalary|null,locale:Locale){if(!salary)return null;const format=(value:string|null)=>{if(!value)return null;const number=Number(value);return Number.isFinite(number)?new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(number):value;};const min=format(salary.minimum),max=format(salary.maximum),amount=min&&max&&min!==max?`${min}–${max}`:min||max;if(!amount)return null;return `${amount}${salary.currency?` ${salary.currency}`:""}${salary.period?` / ${humanize(salary.period)?.toLocaleLowerCase(locale)}`:""}`;}
function cardCompensation(item:PublicJobSummary,locale:Locale){const structured=salaryText(item.salary,locale);if(item.offer_type==="enterprise")return structured;return structured||item.compensation;}
function cleanStructuredLines(value:string){return value.replace(/\s*;{2,}\s*/g,"\n").replace(/\r\n?/g,"\n").split("\n").map((line)=>line.trim()).filter(Boolean);}
function StructuredJobText({value}:{value:string}){const lines=cleanStructuredLines(value),isList=lines.length>1&&lines.every((line)=>/^(?:[-•*]|\d+[.)])\s+/.test(line)||line.length<=220);if(isList)return <ul className="job-structured-list">{lines.map((line,index)=><li key={`${index}-${line.slice(0,24)}`}>{line.replace(/^(?:[-•*]|\d+[.)])\s+/,"")}</li>)}</ul>;const paragraphs=value.replace(/\s*;{2,}\s*/g,"\n\n").replace(/\r\n?/g,"\n").split(/\n{2,}/).map((part)=>part.trim()).filter(Boolean);return <div className="job-structured-copy">{paragraphs.map((paragraph,index)=><p key={`${index}-${paragraph.slice(0,24)}`}>{paragraph}</p>)}</div>;}
function StructuredJobSection({title,value}:{title:string;value:string|null}){return value?.trim()?<section><h2>{title}</h2><StructuredJobText value={value}/></section>:null;}
function experienceText(item:PublicJob,locale:Locale){if(item.experience.text)return item.experience.text;if(item.experience.minimum_years!=null)return detailCopy[locale].years(item.experience.minimum_years);if(item.experience.requirement_kind==="not_required")return locale==="fr"?"Aucune expérience exigée":"No experience required";if(item.experience.requirement_kind==="preferred")return locale==="fr"?"Expérience souhaitée":"Experience preferred";return null;}
function hasSearch(search:JobSearch){return Object.entries(search).some(([key,value])=>key!=="page_size"&&key!=="view"&&value!=null&&value!=="");}
function pageHref(locale:Locale,search:JobSearch,page:number){return `${marketplacePath(locale,"/shida/emplois")}${jobSearchQuery({...search,page})}`;}
function viewHref(locale:Locale,search:JobSearch,view:"professional"|"individual"){return `${marketplacePath(locale,"/shida/emplois")}${jobSearchQuery({...search,view,page:1})}`;}

function EmployerIdentity({employer,locale,large=false,heading=false}:{employer:PublicJobEmployerSummary;locale:Locale;large?:boolean;heading?:boolean}){const image=safePublicImageUrl(employer.profile_image?.url),href=employerPath(locale,employer),location=employerLocation(employer);return <div className={large?"job-employer-identity job-employer-identity-large":"job-employer-identity"}><Link className="job-employer-image" href={href}><MarketplaceImage src={image} alt={employer.name} fallback={initials(employer.name)} sizes={large?"96px":"48px"}/></Link><div>{heading?<h1 className="job-employer-name">{employer.name}</h1>:<Link className="job-employer-name" href={href}>{employer.name}</Link>}{large&&location&&<p>{location}</p>}</div></div>;}
function JobFacts({item,locale}:{item:PublicJobSummary;locale:Locale}){const t=copy[locale],facts:Array<[string,string|number|null]>=[[t.contract,item.contract_type||item.contract_type_raw],[t.mode,item.work_mode||item.work_mode_raw],[t.experience,item.seniority],[t.schedule,item.work_schedule],[t.vacancies,item.vacancies]];return <div className="job-facts">{facts.map(([label,value])=>value!=null&&value!==""&&<span key={label}><b>{label}:</b> {typeof value==="string"?humanize(value):value}</span>)}</div>;}

export function JobCard({item,locale}:{item:PublicJobSummary;locale:Locale}){const t=copy[locale],href=jobPath(locale,item),location=jobLocation(item),published=displayDate(item.published_at,locale),salary=cardCompensation(item,locale),summary=item.summary_preview||item.description_preview,category=item.professional_category||item.category,identity=<span className={item.origin==="external"?"job-origin-label job-origin-external":"job-origin-label"}>{originLabel(item,locale)}</span>;if(item.offer_type==="individual")return <article className="job-result job-result-individual"><div className="job-result-heading"><span className="job-type-label">{t.individualShort}</span>{identity}</div><h3><Link href={href}>{item.title}</Link></h3>{location&&<p className="job-result-location">{location}</p>}<JobFacts item={item} locale={locale}/>{summary&&<p className="job-result-summary">{summary}</p>}{salary&&<p className="job-result-salary">{salary}</p>}<div className="job-result-actions"><ButtonLink href={href} variant="text">{t.details}</ButtonLink></div></article>;return <article className="job-result job-result-professional"><div className="job-result-heading"><EmployerIdentity employer={item.employer} locale={locale}/>{identity}</div><h3><Link href={href}>{item.title}</Link></h3><p className="job-organisation">{item.employer.name}</p>{location&&<p className="job-result-location">{location}</p>}{category&&<p className="job-result-category">{humanize(category)}</p>}<JobFacts item={item} locale={locale}/>{summary&&<p className="job-result-summary">{summary}</p>}<div className="job-result-footer"><div>{salary&&<strong className="job-result-salary">{salary}</strong>}{published&&<span>{t.published} {published}</span>}{item.deadline_label&&<span className={!isOpen(item)?"job-deadline-expired":""}>{item.deadline_label}</span>}</div><div className="job-result-actions"><ButtonLink href={href} variant="text">{t.details}</ButtonLink></div></div></article>;}

function JobFilters({locale,search}:{locale:Locale;search:JobSearch}){const t=copy[locale],clearHref=`${marketplacePath(locale,"/shida/emplois")}${jobSearchQuery({view:search.view})}`;return <aside className="job-filter-column"><details className="job-filter-sheet"><summary>{t.filters}</summary><form action={marketplacePath(locale,"/shida/emplois")} method="get">{search.view&&<input type="hidden" name="view" value={search.view}/>}<label>{t.search}<input type="search" name="query" defaultValue={search.query} placeholder={t.placeholder}/></label><label>{t.city}<input name="city" defaultValue={search.city}/></label><label>{t.area}<input name="area" defaultValue={search.area}/></label><label>{t.commune}<input name="commune" defaultValue={search.commune}/></label><button className="button button-primary" type="submit">{t.applyFilters}</button>{hasSearch(search)&&<Link className="job-clear-filters" href={clearHref}>{t.clear}</Link>}</form></details></aside>;}
function JobPagination({locale,search,collection}:{locale:Locale;search:JobSearch;collection:JobCollection}){const t=copy[locale],p=collection.pagination;if(p.total_pages<=1)return null;return <nav className="marketplace-pagination" aria-label={`${t.page} ${p.page} ${t.of} ${p.total_pages}`}><span>{p.page>1?<Link href={pageHref(locale,search,p.page-1)}>{t.previous}</Link>:t.previous}</span><span>{t.page} {p.page} {t.of} {p.total_pages}</span><span>{p.page<p.total_pages?<Link href={pageHref(locale,search,p.page+1)}>{t.next}</Link>:t.next}</span></nav>;}
function JobGroup({id,title,items,locale}:{id:string;title:string;items:PublicJobSummary[];locale:Locale}){if(!items.length)return null;return <section className="job-result-group" id={id}><h2>{title}<span>{items.length}</span></h2><div className="job-result-list">{items.map((item)=><JobCard key={item.public_ref} item={item} locale={locale}/>)}</div></section>;}

export async function JobCollectionPage({locale,search}:{locale:Locale;search:JobSearch}) {
  const t=copy[locale];
  let collection:JobCollection|undefined;
  try { collection=await getJobs({...search,page:search.page??1,page_size:search.page_size??12},locale); }
  catch(error){if(!(error instanceof ShidaApiError)||error.kind==="not-found")throw error;}
  const professional=collection?.items.filter((item)=>item.offer_type==="enterprise")??[];
  const individual=collection?.items.filter((item)=>item.offer_type==="individual")??[];
  const activeItems=search.view==="professional"?professional:search.view==="individual"?individual:collection?.items??[];
  const emptyMessage=search.view==="professional"?t.emptyProfessional:search.view==="individual"?t.emptyIndividual:t.empty;
  return <>
    <section className="marketplace-heading job-marketplace-heading"><div className="container">
      <MarketplaceSectionBreadcrumb locale={locale} current={t.jobs}/>
      <h1>{t.title}</h1><p>{t.intro}</p>
      <nav className="job-offer-tabs" aria-label={t.jobs}>
        <Link href={viewHref(locale,search,"professional")} className={search.view==="professional"?"job-offer-tab-active":undefined} aria-current={search.view==="professional"?"page":undefined}>{t.professional}</Link>
        <Link href={viewHref(locale,search,"individual")} className={search.view==="individual"?"job-offer-tab-active":undefined} aria-current={search.view==="individual"?"page":undefined}>{t.individual}</Link>
      </nav>
    </div></section>
    <section className="section marketplace-collection job-marketplace"><div className="container job-marketplace-layout">
      <JobFilters locale={locale} search={search}/>
      <main className="job-results" id="job-results">
        {collection?<><p className="marketplace-result-count" role="status">{search.view?activeItems.length:collection.pagination.total_items} {(search.view?activeItems.length:collection.pagination.total_items)===1?t.result:t.results}</p>
          {activeItems.length
            ? search.view==="professional"?<JobGroup id="professional-offers" title={t.professional} items={professional} locale={locale}/>
              :search.view==="individual"?<JobGroup id="individual-offers" title={t.individual} items={individual} locale={locale}/>
              :<><JobGroup id="professional-offers" title={t.professional} items={professional} locale={locale}/><JobGroup id="individual-offers" title={t.individual} items={individual} locale={locale}/></>
            :<div className="job-view-empty"><MarketplaceState>{emptyMessage}</MarketplaceState><ButtonLink href={marketplacePath(locale,"/shida")} variant="secondary">{t.exploreMarketplaces}</ButtonLink></div>}
          <JobPagination locale={locale} search={search} collection={collection}/>
        </>:<div className="job-api-error" role="alert"><MarketplaceState>{t.unavailable}</MarketplaceState><ButtonLink href={pageHref(locale,search,search.page??1)} variant="secondary">{t.retry}</ButtonLink></div>}
      </main>
    </div></section>
  </>;
}

function JobUnavailable({locale,employer=false}:{locale:Locale;employer?:boolean}){const t=copy[locale];return <section className="section"><div className="container job-unavailable"><h1>{employer?t.employerUnavailable:t.jobUnavailable}</h1><ButtonLink href={marketplacePath(locale,"/shida/emplois")} variant="secondary">{t.back}</ButtonLink></div></section>;}
function DetailItem({label,value}:{label:string;value:string|number|null}){return value!=null&&value!==""?<div><dt>{label}</dt><dd>{typeof value==="string"?humanize(value):value}</dd></div>:null;}

export async function JobDetailPage({locale,slug}:{locale:Locale;slug:string}) {
  const t=copy[locale],d=detailCopy[locale];
  let item:PublicJob|undefined;
  try { item=await getJob(slug,locale); }
  catch(error){if(error instanceof ShidaApiError&&error.kind==="not-found")return <JobUnavailable locale={locale}/>;if(!(error instanceof ShidaApiError))throw error;}
  if(!item)return <MarketplaceState>{t.unavailable}</MarketplaceState>;
  const location=jobLocation(item),published=displayDate(item.published_at,locale),deadline=displayDate(item.application_deadline,locale),deadlineLabel=item.deadline_label||(deadline?`${t.deadline}: ${deadline}`:null),start=displayDate(item.start_date,locale),social=safePublicExternalUrl(item.public_social_link),source=safePublicExternalUrl(item.external_source?.canonical_url),href=jobPath(locale,item),salary=salaryText(item.salary,locale)||(item.offer_type==="individual"?item.compensation:null),experience=experienceText(item,locale),inactive=["expired","archived","closed","source_invalid"].includes(item.lifecycle_state);
  const structuredValues=[item.short_summary,item.responsibilities,item.qualifications,experience,item.education,item.skills,item.personal_qualities,item.languages,item.benefits,item.employment_conditions],hasStructuredContent=structuredValues.some((value)=>Boolean(value?.trim())),legacyFallback=hasStructuredContent?null:item.description_fallback||item.description;
  let saveUrl:string|null=null,followUrl:string|null=null;
  try{if(item.relationship_capabilities.can_save){const actions=await getPublicEntityActions("job",item.relationship_capabilities.save_target_ref);saveUrl=safePublicActionUrl(actions.save_url);}}catch{/* Capability remains unavailable without inventing a fallback. */}
  try{if(item.relationship_capabilities.can_follow_employer&&item.relationship_capabilities.follow_target_type&&item.relationship_capabilities.follow_target_ref){const actions=await getPublicEntityActions(item.relationship_capabilities.follow_target_type,item.relationship_capabilities.follow_target_ref);followUrl=safePublicActionUrl(actions.follow_url);}}catch{/* Capability remains unavailable without inventing a fallback. */}
  const directAction=item.application.available&&item.application.capability==="shida_application"?safePublicActionUrl(item.application.apply_url):null;
  const applyButton=directAction?<ButtonLink href={directAction} external>{item.apply_label}</ButtonLink>:item.application.available&&item.application.external_action?<ExternalJobAction locale={locale} jobReference={item.public_ref} action={item.application.external_action} label={item.apply_label}/>:null;
  const stateText=inactive?(item.lifecycle_state==="expired"?(locale==="fr"?"Offre expirée":"Expired offer"):(locale==="fr"?"Cette offre n’est plus active.":"This offer is no longer active.")):null;
  const structuredData=!inactive?{"@context":"https://schema.org","@type":"JobPosting",title:item.title,description:item.short_summary||item.summary_preview||legacyFallback||undefined,datePosted:item.published_at||undefined,validThrough:item.application_deadline||undefined,employmentType:item.contract_type||item.contract_type_raw||undefined,hiringOrganization:{"@type":"Organization",name:item.employer.name},jobLocation:location?{"@type":"Place",address:{"@type":"PostalAddress",addressLocality:item.location.city||undefined,addressRegion:item.location.area||item.location.commune||undefined,addressCountry:item.location.country_code||undefined}}:undefined,url:`https://nihiloba.com${href}`}:null;
  return <>
    {item.origin==="external"&&<JobViewTracker jobReference={item.public_ref}/>} {structuredData&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replaceAll("<","\\u003c")}}/>}
    <section className="marketplace-detail-hero job-detail-hero"><div className="container">
      <MarketplaceBreadcrumb label="Breadcrumb" items={[{label:"SHIDA",href:marketplacePath(locale,"/shida")},{label:t.jobs,href:marketplacePath(locale,"/shida/emplois")},{label:item.title}]}/>
      <div className="job-detail-labels"><span className="job-type-label">{item.offer_type==="enterprise"?t.professionalShort:t.individualShort}</span><span className={item.origin==="external"?"job-origin-label job-origin-external":"job-origin-label"}>{originLabel(item,locale)}</span>{stateText&&<strong className="job-lifecycle-state" role="status">{stateText}</strong>}</div>
      <h1>{item.title}</h1>
      {item.offer_type==="enterprise"?<EmployerIdentity employer={item.employer} locale={locale} large/>:<p className="job-personal-employer">{t.personalEmployer}</p>}
      {location&&<p className="marketplace-detail-location">{location}</p>}
      {(item.professional_category||item.category)&&<p className="job-result-category">{humanize(item.professional_category||item.category)}</p>}
      <div className="job-detail-dates">{deadlineLabel&&<strong className={inactive?"job-deadline-expired":""}>{deadlineLabel}</strong>}{published&&<span>{t.published} {published}</span>}</div>
      <div className="job-detail-primary-actions">{applyButton||<p className="marketplace-action-unavailable">{t.actionUnavailable}</p>}<JobPublicActions locale={locale} jobReference={item.public_ref} title={item.title} path={href} origin={item.origin} canShare={item.relationship_capabilities.can_share} saveUrl={saveUrl} followUrl={followUrl} employerName={item.employer.name}/></div>
    </div></section>
    <section className="section"><div className="container job-detail-layout">
      <main className="job-detail-content">
        <StructuredJobSection title={d.summary} value={item.short_summary}/>
        <StructuredJobSection title={d.responsibilities} value={item.responsibilities}/>
        <StructuredJobSection title={d.qualifications} value={item.qualifications}/>
        <StructuredJobSection title={d.experience} value={experience}/>
        <StructuredJobSection title={d.education} value={item.education}/>
        <StructuredJobSection title={d.skills} value={item.skills}/>
        <StructuredJobSection title={d.languages} value={item.languages}/>
        <StructuredJobSection title={d.qualities} value={item.personal_qualities}/>
        <StructuredJobSection title={d.benefits} value={item.benefits}/>
        <StructuredJobSection title={d.conditions} value={item.employment_conditions}/>
        <StructuredJobSection title={t.description} value={legacyFallback}/>
        {item.requirements_document.available&&item.origin==="direct"&&<section className="job-document-note"><h2>{t.requirements}</h2><p>{t.requirementsDocument}</p></section>}
        {item.offer_type==="enterprise"&&<section><h2>{t.employer}</h2><EmployerIdentity employer={item.employer} locale={locale} large/><ButtonLink href={employerPath(locale,item.employer)} variant="text">{t.employerProfile}</ButtonLink></section>}
        {social&&<section><h2>{d.social}</h2><a href={social} target="_blank" rel="noopener noreferrer">{t.external}</a></section>}
        {item.origin==="external"&&item.external_source&&<section className="job-external-source"><h2>{d.source}</h2><p>{item.external_source.explanation}</p>{source&&<a href={source} target="_blank" rel="noopener noreferrer">{item.external_source.source_label}</a>}</section>}
        <section className="job-final-action"><ButtonLink href={marketplacePath(locale,"/shida/emplois")} variant="text">{inactive?(locale==="fr"?"Voir des offres similaires":"View similar jobs"):t.back}</ButtonLink></section>
      </main>
      <aside className="job-detail-summary"><h2>{d.overview}</h2><dl><DetailItem label={t.contract} value={item.contract_type||item.contract_type_raw}/><DetailItem label={t.mode} value={item.work_mode||item.work_mode_raw}/><DetailItem label={t.schedule} value={item.work_schedule}/><DetailItem label={t.vacancies} value={item.vacancies}/><DetailItem label={t.salary} value={salary}/><DetailItem label={t.start} value={start}/><DetailItem label={t.location} value={item.workplace_reference||location}/></dl></aside>
    </div></section>
  </>;
}

export async function JobEmployerPage({locale,slug}:{locale:Locale;slug:string}){const t=copy[locale];let employer:PublicJobEmployer|undefined;try{employer=await getJobEmployer(slug);}catch(error){if(error instanceof ShidaApiError&&error.kind==="not-found")return <JobUnavailable locale={locale} employer/>;if(!(error instanceof ShidaApiError))throw error;}if(!employer)return <MarketplaceState>{t.unavailable}</MarketplaceState>;let followUrl:string|null=null;try{if(employer.identity_type==="organization_directory"){const actions=await getPublicEntityActions("organization_directory",employer.public_ref);followUrl=safePublicActionUrl(actions.follow_url);}}catch{/* The employer page remains useful when continuation metadata is unavailable. */}return <><section className="marketplace-detail-hero job-employer-hero"><div className="container"><MarketplaceBreadcrumb label="Breadcrumb" items={[{label:"SHIDA",href:marketplacePath(locale,"/shida")},{label:t.jobs,href:marketplacePath(locale,"/shida/emplois")},{label:employer.name}]}/><EmployerIdentity employer={employer} locale={locale} large heading/>{employer.description&&<p className="lead-copy">{employer.description}</p>}{employer.identity_type==="organization_directory"&&<p className="job-directory-note">{locale==="fr"?"Profil public d’organisation. Cette présentation n’implique pas que l’organisation soit cliente ou partenaire de SHIDA.":"Public organization directory profile. This listing does not imply that the organization is a SHIDA customer or partner."}</p>}{followUrl&&<a className="button button-secondary" href={followUrl} target="_blank" rel="noopener noreferrer">{locale==="fr"?`Suivre ${employer.name} sur SHIDA`:`Follow ${employer.name} on SHIDA`}</a>}</div></section><section className="section"><div className="container"><h2>{t.openJobs} ({employer.open_job_count})</h2>{employer.jobs.length?<div className="job-result-list">{employer.jobs.map((item)=><JobCard key={item.public_ref} item={item} locale={locale}/>)}</div>:<MarketplaceState>{t.noEmployerJobs}</MarketplaceState>}</div></section></>;}

function metadataBase(locale:Locale,path:string,title:string,description:string|undefined,image:string|null):Metadata{const canonical=marketplacePath(locale,path);return {title,description,alternates:{canonical,languages:{en:path,fr:`/fr${path}`,"x-default":path}},openGraph:{title,description,url:canonical,images:[{url:image||"/NIHILOBA_logo.png",alt:title}]}};}
export function jobsMetadata(locale:Locale):Metadata{const t=copy[locale];return metadataBase(locale,"/shida/emplois",t.title,t.intro,null);}
export async function jobMetadata(locale:Locale,slug:string):Promise<Metadata>{try{const item=await getJob(slug,locale),location=jobLocation(item),title=`${item.title} — ${item.employer.name} | SHIDA Emploi`,description=item.origin==="external"?(locale==="fr"?`Découvrez l’offre ${item.title} publiée par ${item.employer.name} et référencée sur SHIDA Emploi${location?` à ${location}`:""}.`:`Discover the ${item.title} offer published by ${item.employer.name} and listed on SHIDA Employment${location?` in ${location}`:""}.`):([item.short_summary||item.summary_preview||item.description_fallback||item.description,location].filter(Boolean).join(" · ")||undefined),metadata=metadataBase(locale,`/shida/emplois/${item.slug||item.public_ref}`,title,description,safePublicImageUrl(item.employer.profile_image?.url));if(item.status!=="open")metadata.robots={index:false,follow:true};return metadata;}catch{return {title:copy[locale].jobUnavailable,robots:{index:false,follow:false}};}}
export async function jobEmployerMetadata(locale:Locale,slug:string):Promise<Metadata>{try{const item=await getJobEmployer(slug),location=employerLocation(item),description=locale==="fr"?`${item.open_job_count} offre${item.open_job_count===1?"":"s"} ouverte${item.open_job_count===1?"":"s"}${location?` à ${location}`:""} sur SHIDA.`:`${item.open_job_count} open job${item.open_job_count===1?"":"s"}${location?` in ${location}`:""} on SHIDA.`;return metadataBase(locale,`/shida/emplois/employeurs/${item.slug||item.public_ref}`,`${item.name} | SHIDA`,item.description||description,safePublicImageUrl(item.profile_image?.url));}catch{return {title:copy[locale].employerUnavailable,robots:{index:false,follow:false}};}}
