import type { Locale } from "../../lib/i18n";

export const marketplaceCopy = {
  en: {
    apartments: "Apartments", hotels: "Hotels", wenze: "Wenze", services: "Services", jobs: "💼 Jobs", browse: "Browse on NIHILOBA", gateway: "Explore SHIDA listings",
    gatewayText: "Browse public jobs, apartments, hotels, services and Wenze shops, then continue securely through SHIDA on WhatsApp.",
    apartmentTitle: "Available homes on SHIDA", hotelTitle: "Hotels available through SHIDA",
    apartmentIntro: "Discover currently available homes and request a visit directly through SHIDA.",
    hotelIntro: "Explore public hotels and room options, then continue to the official SHIDA booking journey.",
    details: "View details", visit: "Request a visit with SHIDA", book: "Book on WhatsApp", rooms: "rooms", perMonth: "per month",
    roomTypes: "Room options", roomPhotos: "Room photos", capacity: "Capacity", guests: "guests", availableRooms: "rooms offered", bookRoom: "Book this room on SHIDA",
    unavailable: "This marketplace is temporarily unavailable. Please try again shortly.",
    emptyApartments: "No apartments are publicly listed right now.", emptyHotels: "No hotels are publicly listed right now.",
    actionUnavailable: "The SHIDA action link is temporarily unavailable.", notFound: "This listing could not be found.",
    backApartments: "Back to apartments", backHotels: "Back to hotels", from: "From", location: "Location",
    imageUnavailable: "Image unavailable", availability: "Availability", landmark: "Landmark", price: "Price",
    breadcrumb: "Breadcrumb", home: "Home", photos: "Apartment photos", descriptionTitle: "About this apartment", detailsTitle: "Property details", visitTitle: "Interested in this apartment?", visitText: "Continue with SHIDA to request a visit through the official WhatsApp journey.",
    searchLabel: "Search listings", searchPlaceholder: "Area, city, studio, 2 bedrooms…", search: "Search",
    filters: "More filters", city: "City", area: "Area / district", propertyType: "Property type", bedrooms: "Bedrooms",
    minimumPrice: "Minimum price", maximumPrice: "Maximum price", any: "Any", applyFilters: "Apply filters", resetFilters: "Clear filters",
    result: "available home", results: "available homes", previous: "Previous", next: "Next", page: "Page", of: "of",
    noSearchResults: "No homes match your search.", publishedBy: "Published by", ownerListings: "View all homes from",
    ownerProfile: "Property profile", availableListings: "Available homes", ownerEmpty: "No homes are currently available from this profile.",
    ownerNotFound: "This property profile could not be found.", backToListings: "All available homes",
    propertyTypes: { apartment: "Apartment", house: "House", studio: "Studio", room: "Room", office: "Office", commercial: "Commercial property", land: "Land", other: "Other" },
  },
  fr: {
    apartments: "Appartements", hotels: "Hôtels", wenze: "Wenze", services: "Services", jobs: "💼 Emplois", browse: "Parcourir sur NIHILOBA", gateway: "Explorer les annonces SHIDA",
    gatewayText: "Parcourez les offres d’emploi, les appartements, les hôtels, les services et les boutiques Wenze, puis continuez en toute sécurité avec SHIDA sur WhatsApp.",
    apartmentTitle: "Logements disponibles sur SHIDA", hotelTitle: "Hôtels disponibles avec SHIDA",
    apartmentIntro: "Découvrez les logements actuellement disponibles et demandez une visite directement via SHIDA.",
    hotelIntro: "Explorez les hôtels et les chambres, puis continuez vers le parcours officiel de réservation SHIDA.",
    details: "Voir les détails", visit: "Demander une visite avec SHIDA", book: "Réserver sur WhatsApp", rooms: "pièces", perMonth: "par mois",
    roomTypes: "Options de chambre", roomPhotos: "Photos de la chambre", capacity: "Capacité", guests: "personnes", availableRooms: "chambres proposées", bookRoom: "Réserver cette chambre sur SHIDA",
    unavailable: "Ce marché est temporairement indisponible. Veuillez réessayer dans quelques instants.",
    emptyApartments: "Aucun appartement n’est publié pour le moment.", emptyHotels: "Aucun hôtel n’est publié pour le moment.",
    actionUnavailable: "Le lien d’action SHIDA est temporairement indisponible.", notFound: "Cette annonce est introuvable.",
    backApartments: "Retour aux appartements", backHotels: "Retour aux hôtels", from: "À partir de", location: "Localisation",
    imageUnavailable: "Image indisponible", availability: "Disponibilité", landmark: "Repère", price: "Prix",
    breadcrumb: "Fil d’Ariane", home: "Accueil", photos: "Photos de l’appartement", descriptionTitle: "À propos de cet appartement", detailsTitle: "Détails du logement", visitTitle: "Ce logement vous intéresse ?", visitText: "Continuez avec SHIDA pour demander une visite via le parcours WhatsApp officiel.",
    searchLabel: "Rechercher des logements", searchPlaceholder: "Gombe, Kasa-Vubu, studio, 2 chambres…", search: "Rechercher",
    filters: "Plus de filtres", city: "Ville", area: "Zone / commune", propertyType: "Type de bien", bedrooms: "Chambres",
    minimumPrice: "Prix minimum", maximumPrice: "Prix maximum", any: "Tous", applyFilters: "Appliquer les filtres", resetFilters: "Effacer les filtres",
    result: "logement disponible", results: "logements disponibles", previous: "Précédent", next: "Suivant", page: "Page", of: "sur",
    noSearchResults: "Aucun logement ne correspond à votre recherche.", publishedBy: "Publié par", ownerListings: "Voir tous les logements de",
    ownerProfile: "Profil immobilier", availableListings: "Logements disponibles", ownerEmpty: "Aucun logement n’est actuellement disponible pour ce profil.",
    ownerNotFound: "Ce profil immobilier est introuvable.", backToListings: "Tous les logements",
    propertyTypes: { apartment: "Appartement", house: "Maison", studio: "Studio", room: "Chambre", office: "Bureau", commercial: "Local commercial", land: "Terrain", other: "Autre" },
  },
} as const satisfies Record<Locale, object>;
