"use client";
import { useState } from "react";
import { checkoutCopy } from "../../lib/restaurant-checkout-copy";
import type { GuestSelections as Selections } from "../../lib/restaurant-guest-browser";
import type { RestaurantLocale, RestaurantMenuItem } from "../../services/shida/restaurants-client";

export function MenuChoice({item,locale,selections,busy,onAdd}:{item:RestaurantMenuItem;locale:RestaurantLocale;selections:Selections;busy:boolean;onAdd:(plate:number|null,quantity:number,amount:string)=>void}){
 const t=checkoutCopy[locale];const [quantity,setQuantity]=useState(1),[amount,setAmount]=useState(item.allowed_amounts[0]??item.minimum_amount??"");const [plate,setPlate]=useState<number|null>(item.presentation==="component"?-1:null);
 return <article><h3>{item.name}</h3><p>{item.pricing_model==="UNIT_PRICED"?`${item.unit_price} ${item.currency} / ${item.sale_unit_label??t.quantity}`:item.pricing_model==="AMOUNT_PRICED"?`${t.amount}: ${item.allowed_amounts.join(", ")||item.minimum_amount} ${item.currency}`:t.soldOut}</p>{item.availability!=="available"||item.pricing_model==="UNKNOWN"?<p>{t.soldOut}</p>:<><label>{item.pricing_model==="UNIT_PRICED"?t.quantity:t.amount}{item.pricing_model==="UNIT_PRICED"?<input type="number" min="1" max="1000" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/>:item.allowed_amounts.length?<select value={amount} onChange={e=>setAmount(e.target.value)}>{item.allowed_amounts.map(value=><option key={value} value={value}>{value} {item.currency}</option>)}</select>:<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} aria-describedby={`amount-${item.public_ref}`}/>}</label>{item.pricing_model==="AMOUNT_PRICED"&&<small id={`amount-${item.public_ref}`}>{t.amountHelp}</small>}{item.presentation==="component"&&<label>{t.plate}<select value={plate??-1} onChange={e=>setPlate(Number(e.target.value))}><option value={-1}>{t.addPlate}</option>{selections.plates.map((p,i)=><option value={i} key={p.key}>{t.plate} {i+1}</option>)}</select></label>}<button type="button" disabled={busy||item.pricing_model==="UNIT_PRICED"&&(!Number.isSafeInteger(quantity)||quantity<1)} onClick={()=>onAdd(plate,quantity,amount)}>{t.add}</button></>}</article>;
}
