'use client';
import { useEffect, useRef, useState } from 'react';
import type { RestaurantLocale } from '@/app/services/shida/restaurants-client';
import { request } from '@/app/lib/restaurant-seller-browser';
import { pricing, type Establishment, type Row, type Page, type Envelope } from '@/app/lib/restaurant-seller';
import { useWorkRequest, useWorkDraft } from '@/app/lib/restaurant-work';
import { workText, categorySuggestions } from '@/app/lib/restaurant-work-copy';
type Draft={key:string;name:string;pricing_model:string;unit_price:string;sale_unit_label:string;allowed_amounts:string;minimum_amount:string;choice:string;presentation:string};
const row=():Draft=>({key:crypto.randomUUID(),name:'',pricing_model:'UNIT_PRICED',unit_price:'',sale_unit_label:'',allowed_amounts:'',minimum_amount:'',choice:'',presentation:'component'});
export function RestaurantMenuBatch({path,binding,locale,onFailure}:{path:string;binding:string;locale:RestaurantLocale;onFailure:(e:unknown)=>void}){
 const alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const [validation,setValidation]=useState(false),[reloading,setReloading]=useState(true);
 const t=(k:string)=>workText(locale,k),api=useWorkRequest(binding,onFailure);
 const [parent,setParent]=useState<Establishment|null>(null),[categories,setCategories]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]),[category,setCategory]=useState(''),[name,setName]=useState(''),[currency,setCurrency]=useState('CDF'),[rows,setRows]=useState<Draft[]>([]),[review,setReview]=useState(false),[fresh,setFresh]=useState(false);
 useWorkDraft(rows.some(r=>!!r.name) || !!api.pending,t('discard'));
 async function load(){const p=await request(path,{},binding) as Establishment;const all=async(kind:string)=>{const result:Row[]=[];for(let page=1;;page++){const envelope=await request(`${path}/menu/${kind}?page=${page}&page_size=50`,{},binding) as Envelope<Page<Row>>;result.push(...envelope.result.items);if(result.length>=envelope.result.total || !envelope.result.items.length)return result;}};return {p,c:await all('categories'),i:await all('items')};}
 useEffect(()=>{let alive=true;load().then(({p,c,i})=>{if(!alive)return;setParent(p);setCategories(c);setItems(i);setCurrency(p.menu_currency ?? 'CDF');setRows([row(),row()]);setFresh(true);setReloading(false);}).catch(e=>{if(alive){setReloading(false);onFailure(e);}});const stale=()=>setFresh(false);window.addEventListener('offline',stale);document.addEventListener('visibilitychange',stale);return()=>{alive=false;window.removeEventListener('offline',stale);document.removeEventListener('visibilitychange',stale);};},[path,binding]); // eslint-disable-line react-hooks/exhaustive-deps
 function change(key:string,patch:Partial<Draft>){setValidation(false);setRows(old=>old.map(r=>r.key===key?{...r,...patch}:r));setReview(false);}
 const collisions=(r:Draft)=>items.filter(i=>i.category?.public_ref===category && i.name?.trim().toLocaleLowerCase()===r.name.trim().toLocaleLowerCase());
 const valid=rows.length>0 && rows.some(r=>r.choice!=='skip') && rows.every(r=>r.choice==='skip' || r.name.trim() && (!collisions(r).length || r.choice));
 async function save(){
  if(!parent)return;
  let entries;
  try { entries=rows.map(r=>r.choice==='skip' ? {key:r.key,skip:true} : {
   key:r.key, fields:{name:r.name,...(!r.choice.startsWith('RMI_')?{presentation:r.presentation}:{}),...pricing({...r,currency})},
   ...(r.choice==='separate'?{separate:true}:r.choice.startsWith('RMI_')?{target_ref:r.choice}:{})
  }); } catch {setReview(false);setValidation(true);return;}
  const body={operation_key:crypto.randomUUID(),expected_updated_at:parent.revision,...(category?{category_ref:category}:{category_name:name}),rows:entries};
  const result=await api.run(`${path}/menu-batches`,'POST',body);
  if(result){setRows([row()]);setReview(false);setFresh(false);}
 }

 return <form className="rst-card rst-work" onSubmit={e=>{e.preventDefault();if(review)void save();else setReview(true);}}><h2>{t('batch')}</h2><p>{t('defaults')}</p><p role="status">{validation?t('validation'):api.message && t(api.message)}</p>{(!fresh || api.conflict) && <><p>{t('stale')}</p><button type="button" disabled={api.busy || !api.online || reloading} onClick={async()=>{if(reloading)return;setReloading(true);try{const {p,c,i}=await load();if(!alive.current)return;setParent(p);setCategories(c);setItems(i);setFresh(true);if(api.conflict){setReview(false);api.reset();}}catch(e){if(alive.current)onFailure(e);}finally{if(alive.current)setReloading(false);}}}>{t('review')}</button></>}
 <fieldset disabled={api.busy || !!api.pending || api.conflict || !fresh || !api.online}><div className="rst-fields"><label>{t('category')}<select value={category} onChange={e=>{setCategory(e.target.value);setRows(old=>old.map(r=>({...r,choice:''})));setReview(false);}}><option value="">{t('custom')}</option>{categories.map(c=><option key={c.public_ref} value={c.public_ref}>{c.name}</option>)}</select></label>{!category && <label>{t('custom')}<input required maxLength={200} list="rst-category-suggestions" value={name} onChange={e=>{setName(e.target.value);setReview(false);}}/><datalist id="rst-category-suggestions">{categorySuggestions[locale].map(s=><option key={s}>{s}</option>)}</datalist></label>}<label>{t('currency')}<select value={currency} disabled={!!parent?.menu_currency} onChange={e=>{setCurrency(e.target.value);setReview(false);}}><option>CDF</option><option>USD</option></select></label></div>
 {rows.map((r,index)=><fieldset className="rst-batch-row" key={r.key}><legend>{index+1}</legend><div className="rst-fields"><label>{t('name')}<input required={r.choice!=='skip'} maxLength={200} value={r.name} onChange={e=>change(r.key,{name:e.target.value,choice:''})}/></label><label>{t('price')}<select value={r.pricing_model} onChange={e=>change(r.key,{pricing_model:e.target.value})}><option value="UNIT_PRICED">{t('unit')}</option><option value="AMOUNT_PRICED">{t('amount')}</option><option value="UNKNOWN">{t('unknown')}</option></select></label>{r.pricing_model==='UNIT_PRICED' && <><label>{t('price')}<input required={r.choice!=='skip'} inputMode="decimal" pattern="[0-9]{1,16}([.,][0-9]{1,2})?" value={r.unit_price} onChange={e=>change(r.key,{unit_price:e.target.value})}/></label><label>{t('unitLabel')}<input required={r.choice!=='skip'} maxLength={80} value={r.sale_unit_label} onChange={e=>change(r.key,{sale_unit_label:e.target.value})}/></label></>}{r.pricing_model==='AMOUNT_PRICED' && <><label>{t('options')}<input required={r.choice!=='skip'} value={r.allowed_amounts} onChange={e=>change(r.key,{allowed_amounts:e.target.value})}/></label><label>{t('minimum')}<input inputMode="decimal" value={r.minimum_amount} onChange={e=>change(r.key,{minimum_amount:e.target.value})}/></label></>}
 <label>{t('review')}<select required={collisions(r).length>0} value={r.choice} onChange={e=>change(r.key,{choice:e.target.value})}><option value="">{t('create')}</option><option value="skip">{t('skip')}</option><option value="separate">{t('separate')}</option>{collisions(r).map(i=><option value={i.public_ref} key={i.public_ref}>{t('update')} · {i.name}</option>)}</select></label><label>{t('plate')}<select value={r.presentation} onChange={e=>change(r.key,{presentation:e.target.value})}><option value="component">{t('amount')}</option><option value="fixed_dish">{t('standalone')}</option></select></label><button type="button" disabled={rows.length===1} onClick={()=>{setRows(old=>old.filter(x=>x.key!==r.key));setReview(false);}}>{t('remove')}</button></div></fieldset>)}<button type="button" disabled={rows.length>=20} onClick={()=>{setRows(old=>[...old,row()]);setReview(false);}}>{t('add')}</button></fieldset>
 {review && <div><h3>{t('review')} · {categories.find(c=>c.public_ref===category)?.name ?? name}</h3><ul>{rows.map(r=><li key={r.key}>{r.name} · {t(r.choice==='skip'?'skip':r.choice.startsWith('RMI_')?'update':r.choice==='separate'?'separate':'create')} · {r.pricing_model==='UNIT_PRICED'?`${r.unit_price} ${currency} / ${r.sale_unit_label}`:r.pricing_model==='AMOUNT_PRICED'?`${r.allowed_amounts} ${currency}`:t('unknown')}</li>)}</ul></div>}<button className="button button-primary" disabled={!valid || !fresh || !api.online || api.busy || api.conflict || reloading}>{t(api.pending?'retry':review?'confirm':'review')}</button></form>;
}
