'use client';
import { useState } from 'react';
import { useWorkRequest, dateText } from '@/app/lib/restaurant-work';
import { workText } from '@/app/lib/restaurant-work-copy';
import type { RestaurantLocale } from '@/app/services/shida/restaurants-client';
type Summary={as_of:string;coverage_from:string|null;coverage_to:string;measurement_status:string;metrics:null|{submitted_orders:number;completed_in_period:number;completed_food_value:Record<string,string>;completed_delivery_fees:Record<string,string>;status_breakdown:Record<string,number>;item_summary:{items:{item_ref:string;occurrences:number;units:number;amount:string;currency:string}[];total:number}}};
export function RestaurantActivity({path,binding,locale,timezone,onFailure}:{path:string;binding:string;locale:RestaurantLocale;timezone:string|null;onFailure:(e:unknown)=>void}){
 const t=(k:string)=>workText(locale,k),api=useWorkRequest(binding,onFailure);const [from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[summary,setSummary]=useState<Summary|null>(null),[confirm,setConfirm]=useState(false);
 async function read(p=1){setSummary(null);const s=await api.run<Summary>(`${path}/order-summary?from_date=${from}&to_date=${to}&page=${p}&page_size=20`);if(s){setSummary(s);setPage(p);}}
 return <article className="rst-card rst-work"><h2>{t('activity')}</h2><p>{t('measurementHelp')}</p><p>{t('timezone')}: {timezone}</p><form onSubmit={e=>{e.preventDefault();void read();}}><div className="rst-fields"><label>{t('from')}<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{t('to')}<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="button button-secondary" disabled={api.busy || !api.online}>{t('review')}</button></form><p role="status">{api.message && t(api.message)}</p>{summary && <><p>{t('updated')}: {dateText(summary.as_of,locale,timezone)}</p><p>{t('coverage')}: {dateText(summary.coverage_from,locale,timezone)} – {dateText(summary.coverage_to,locale,timezone)} · {t(summary.measurement_status)}</p>{summary.metrics && <><dl className="rst-details">{(['submitted_orders','completed_in_period','completed_food_value','completed_delivery_fees'] as const).map(k=><div key={k}><dt>{t(k)}</dt><dd>{typeof summary.metrics![k]==='number'?String(summary.metrics![k]):Object.entries(summary.metrics![k] as Record<string,string>).map(([c,v])=><p key={c}>{v} {c}</p>)}</dd></div>)}</dl><div>{Object.entries(summary.metrics.status_breakdown).map(([s,n])=><p key={s}>{t(s)}: {n}</p>)}</div>{summary.metrics.item_summary.items.map(i=><p key={i.item_ref+i.currency}>{i.item_ref}: {i.occurrences} · {i.units} {t('quantity')} · {i.amount} {i.currency}</p>)}<div className="rst-actions"><button type="button" disabled={page===1 || api.busy} onClick={()=>void read(page-1)}>{t('previous')}</button><button type="button" disabled={page*20>=summary.metrics.item_summary.total || api.busy} onClick={()=>void read(page+1)}>{t('next')}</button></div></>}</>}
 {!summary?.metrics && <div>{confirm && <p>{t('measurementHelp')}</p>}<button type="button" disabled={api.busy || !api.online} onClick={async()=>{if(!confirm){setConfirm(true);return;}const result=await api.run(`${path}/order-measurement`,'POST');if(result)setConfirm(false);}}>{t(confirm?'confirm':'measurement')}</button></div>}</article>;
}
