'use client';
import { useEffect, useState } from 'react';
import { request } from '@/app/lib/restaurant-seller-browser';
import { localInstant } from '@/app/lib/restaurant-seller';
import { useWorkRequest, useWorkDraft, type Configuration, type ServiceWindow, type Area } from '@/app/lib/restaurant-work';
import { workText } from '@/app/lib/restaurant-work-copy';
import type { RestaurantLocale } from '@/app/services/shida/restaurants-client';
import { LocalTime } from './restaurant-local-time';
export function RestaurantIntake({path,binding,locale,timezone,onFailure}:{path:string;binding:string;locale:RestaurantLocale;timezone:string|null;onFailure:(e:unknown)=>void}) {
 const t=(k:string)=>workText(locale,k),api=useWorkRequest(binding,onFailure);
 const [config,setConfig]=useState<Configuration|null>(null),[kind,setKind]=useState<'pickup'|'delivery'>('pickup'),[enabled,setEnabled]=useState(false),[windows,setWindows]=useState<ServiceWindow[]>([]),[areas,setAreas]=useState<Area[]>([]),[fee,setFee]=useState({amount:'',currency:'CDF'}),[review,setReview]=useState(false),[fresh,setFresh]=useState(false);
 useWorkDraft(review || !!api.pending,t('discard'));
 function fill(c:Configuration,k:typeof kind){setKind(k);setConfig(c);setEnabled(c[k]?.enabled ?? false);setWindows((c[k]?.windows ?? []).map(w=>({starts_at:localInstant(w.starts_at,timezone),ends_at:localInstant(w.ends_at,timezone)})));setAreas(c.delivery?.areas ?? []);setFee(c.delivery?.fee ?? {amount:'',currency:'CDF'});setFresh(true);setReview(false);}
 useEffect(()=>{let alive=true;request(`${path}/order-configuration`,{},binding).then(v=>{if(alive)fill(v as Configuration,'pickup');}).catch(e=>{if(alive)onFailure(e);});const stale=()=>setFresh(false);window.addEventListener('offline',stale);document.addEventListener('visibilitychange',stale);return()=>{alive=false;window.removeEventListener('offline',stale);document.removeEventListener('visibilitychange',stale);};},[path,binding]); // eslint-disable-line react-hooks/exhaustive-deps
 async function save(){if(!config)return;const result=await api.run(`${path}/${kind}-intake`,'PUT',{operation_key:crypto.randomUUID(),expected_updated_at:config.revision,enabled,windows,...(kind==='delivery'?{fee,areas}:{})});if(result){const c=await api.run<Configuration>(`${path}/order-configuration`);if(c)fill(c,kind);}}
 return <form className="rst-card rst-work" onSubmit={e=>{e.preventDefault();if(review)void save();else setReview(true);}}><h2>{t('intake')}</h2><p>{t('timezone')}: {timezone}</p><p>{t('timeHelp')}</p>{config && !config.intake_released && <p>{t('closed')}</p>}<p role="status">{api.message && t(api.message)}</p>{!fresh && <p>{t('stale')}</p>}
 {(api.conflict || !fresh) && <button type="button" disabled={api.busy || !api.online} onClick={async()=>{const c=await api.run<Configuration>(`${path}/order-configuration`);if(c){setConfig(c);setFresh(true);if(api.conflict){setReview(false);api.reset();}}}}>{t('refresh')}</button>}
 <fieldset disabled={api.busy || !!api.pending || api.conflict || !fresh || !api.online}><div className="rst-actions">{(['pickup','delivery'] as const).map(k=><button type="button" key={k} aria-pressed={kind===k} onClick={()=>config && fill(config,k)}>{t(k)}</button>)}</div><label><input type="checkbox" checked={enabled} disabled={!config?.intake_released && !enabled} onChange={e=>{setEnabled(e.target.checked);setReview(false);}}/>{t('enabled')}</label><h3>{t('windows')}</h3>{windows.map((w,i)=><div className="rst-row" key={i}>{(['starts_at','ends_at'] as const).map((k,j)=><label key={k}>{t(j?'to':'from')}<LocalTime value={w[k]} timezone={timezone} locale={locale} onChange={v=>{setWindows(old=>old.map((x,n)=>n===i?{...x,[k]:v}:x));setReview(false);}}/></label>)}<button type="button" onClick={()=>{setWindows(old=>old.filter((_,n)=>n!==i));setReview(false);}}>{t('remove')}</button></div>)}<button type="button" disabled={windows.length>=20} onClick={()=>{setWindows(old=>[...old,{starts_at:'',ends_at:''}]);setReview(false);}}>{t('add')}</button>
 {kind==='delivery' && <><h3>{t('fee')}</h3><label>{t('amount')}<input required inputMode="decimal" pattern="[0-9]{1,16}(\.[0-9]{1,2})?" value={fee.amount} onChange={e=>{setFee({...fee,amount:e.target.value});setReview(false);}}/></label><label>{t('currency')}<select value={fee.currency} onChange={e=>{setFee({...fee,currency:e.target.value});setReview(false);}}><option>CDF</option><option>USD</option></select></label><h3>{t('areas')}</h3>{areas.map((a,i)=><div className="rst-fields" key={i}>{(['country','city','commune','quartier'] as const).map(k=><label key={k}>{t(k)}<input required={k!=='quartier' || a.scope==='quartier'} maxLength={200} value={a[k] ?? ''} onChange={e=>{setAreas(old=>old.map((x,n)=>n===i?{...x,[k]:e.target.value}:x));setReview(false);}}/></label>)}<label>{t('scope')}<select value={a.scope} onChange={e=>{setAreas(old=>old.map((x,n)=>n===i?{...x,scope:e.target.value,quartier:e.target.value==='whole_commune'?null:x.quartier}:x));setReview(false);}}><option value="whole_commune">{t('whole_commune')}</option><option value="quartier">{t('quartier')}</option></select></label><button type="button" onClick={()=>{setAreas(old=>old.filter((_,n)=>n!==i));setReview(false);}}>{t('remove')}</button></div>)}<button type="button" disabled={areas.length>=100} onClick={()=>{setAreas(old=>[...old,{country:'',city:'',commune:'',quartier:null,scope:'whole_commune'}]);setReview(false);}}>{t('add')}</button></>}
 </fieldset>{review && <p>{t('review')}: {t(kind)} · {windows.length} {t('windows')} · {t('enabled')}: {String(enabled)} {kind==='delivery' && `${fee.amount} ${fee.currency} · ${areas.length} ${t('areas')}`}</p>}<button className="button button-primary" disabled={!fresh || !api.online || api.busy || api.conflict || !config || enabled && !config.intake_released && !api.pending}>{t(api.pending?'retry':review?'confirm':'review')}</button></form>;
}
