'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import type { RestaurantLocale } from '../../services/shida/restaurants-client';
import type { Envelope, Page, Row } from '../../lib/restaurant-seller';
import { request, DashboardApiError } from '../../lib/restaurant-seller-browser';
import { useWorkRequest, useWorkDraft, dateText, type Order, type Terms, type Configuration } from '../../lib/restaurant-work';
import { basicText } from '../../lib/restaurant-basic-copy';
import { workText } from '../../lib/restaurant-work-copy';
import { FoodTerms, ReceiptCard } from './restaurant-receipt';
type Basket={basket_ref:string;revision:number;quote:Terms|null;quote_ref:string|null;order_ref:string|null};
type Line={key:string;item_ref:string;name:string;amounts?:string[];flexible?:boolean;currency:string;quantity?:number;selected_amount?:string;plate:string};
export function RestaurantCounter({path,binding,locale,onFailure,pos=false,onFreeCounter}:{onFreeCounter?:()=>void;pos?:boolean;path:string;binding:string;locale:RestaurantLocale;onFailure:(e:unknown)=>void}) {
 const salesPath=pos?`${path}/pos`:path;
 const [preference,setPreference]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[recent,setRecent]=useState<Order[]>([]);
 const [accessLost,setAccessLost]=useState(false);
 const failure=useCallback((error:unknown)=>{if(pos && error instanceof DashboardApiError && [403,404].includes(error.status)){setAccessLost(true);return;}onFailure(error);},[pos,onFailure]);
 const t=(k:string)=>workText(locale,k),api=useWorkRequest(binding,failure);
 const [config,setConfig]=useState<Configuration|null>(null),[items,setItems]=useState<Row[]>([]),[menuPage,setMenuPage]=useState(1),[menuTotal,setMenuTotal]=useState(0),[basket,setBasket]=useState<Basket|null>(null),[lines,setLines]=useState<Line[]>([]),[method,setMethod]=useState('on_premise'),[order,setOrder]=useState<Order|null>(null),[plate,setPlate]=useState(''),[dirty,setDirty]=useState(true),[fresh,setFresh]=useState(false);
 useWorkDraft(!!basket || !!api.pending,t('discard'));
 useEffect(()=>{let alive=true;const controller=new AbortController();
 const load=async()=>{if(pos){const data=await request(`${salesPath}?language=${locale}`,{signal:controller.signal},binding) as {intake_released:boolean;items:Row[];recent:Order[]};if(!alive)return;setConfig({intake_released:data.intake_released} as Configuration);setItems(data.items);setRecent(data.recent);setMenuTotal(data.items.length);}
 else {const [c,m]=await Promise.all([request(`${path}/order-configuration`,{signal:controller.signal},binding),request(`${path}/menu/items?page=${menuPage}&page_size=20`,{signal:controller.signal},binding)]);if(!alive)return;setConfig(c as Configuration);const menu=m as Envelope<Page<Row>>;setItems(menu.result.items);setMenuTotal(menu.result.total);}setFresh(true);};
 void load().catch(e=>{if(alive)failure(e);});return()=>{alive=false;controller.abort();};},[path,salesPath,pos,locale,binding,menuPage,failure]);
 useEffect(()=>{const stale=()=>setFresh(false);window.addEventListener('offline',stale);document.addEventListener('visibilitychange',stale);return()=>{window.removeEventListener('offline',stale);document.removeEventListener('visibilitychange',stale);};},[]);
 const locked=api.busy || !!api.pending || api.conflict || !api.online || !fresh;
 async function validate(){if(pos){const data=await api.run<{intake_released:boolean;items:Row[];recent:Order[]}>(`${salesPath}?language=${locale}`);if(!data)return false;setConfig({intake_released:data.intake_released} as Configuration);setItems(data.items);setRecent(data.recent);}else{const c=await api.run<Configuration>(`${path}/order-configuration`);if(!c)return false;setConfig(c);}if(basket){const b=await api.run<Basket>(`${salesPath}/counter-baskets/${basket.basket_ref}`);if(!b)return false;setBasket(b);if(!api.pending)setDirty(true);}setFresh(true);return true;}

 function selections(){const line=(l:Line)=>({key:l.key,item_ref:l.item_ref,...(l.quantity!=null?{quantity:l.quantity}:{selected_amount:l.selected_amount})});return {standalone:lines.filter(l=>!l.plate).map(line),plates:[...new Set(lines.map(l=>l.plate).filter(Boolean))].map(key=>({key,components:lines.filter(l=>l.plate===key).map(line)}))};}
 async function create(){const b=await api.run<Basket>(`${salesPath}/counter-baskets`,'POST',{operation_key:crypto.randomUUID()});if(b){setBasket(b);setOrder(null);setDirty(true);}}
 async function edit(quote:boolean){if(!basket)return;const result=await api.run<{basket:Basket}>(`${salesPath}/counter-baskets/${basket.basket_ref}${quote?'/quote':''}`,quote?'POST':'PATCH',{operation_key:crypto.randomUUID(),expected_revision:basket.revision,selections:selections(),fulfillment_method:method,food_preference:preference.trim()||null});if(result){setBasket(result.basket);setDirty(!quote);}}
 async function finalize(){if(!basket)return;const result=await api.run<{current_order:Order}>(`${salesPath}/counter-baskets/${basket.basket_ref}/finalize`,'POST',{operation_key:crypto.randomUUID(),expected_revision:basket.revision,quote_ref:basket.quote_ref,confirm:true,handoff_confirmed:true,fulfillment_method:method});if(result){setOrder(result.current_order);setBasket(null);setLines([]);setPreference('');setRecent(old=>[result.current_order,...old].slice(0,20));if(pos){setFresh(false);const current=await api.run<{intake_released:boolean;items:Row[];recent:Order[]}>(`${salesPath}?language=${locale}`);if(current){setItems(current.items);setRecent(current.recent);setConfig({intake_released:current.intake_released} as Configuration);setFresh(true);}}}}
 if(accessLost)return <article className="rst-card rst-work"><p role="alert">{t('posAccessLost')}</p><button type="button" onClick={onFreeCounter}>{t('counter')}</button></article>;
 return <article className="rst-card rst-work"><h2>{t(pos?'pos':'counter')}</h2><p>{t('quoteHelp')}</p>{!fresh && <p>{t('stale')} <button type="button" disabled={api.busy || !api.online} onClick={()=>void validate()}>{t('refresh')}</button></p>}{config && !config.intake_released && <p>{t('closed')}</p>}<p role="status">{api.message && t(api.message)}</p>{api.conflict && <button type="button" disabled={api.busy || !api.online} onClick={async()=>{if(await validate()){setDirty(true);api.reset();}}}>{t('review')}</button>}
 {order && <><ReceiptCard order={order} locale={locale}/><Link prefetch={false} href={`${locale==='en'?'':`/${locale}`}/shida/seller/restaurants/${path.split('/').at(-1)}/receipts/${order.order_ref}`}>{t('receipt')}</Link></>}
 {!basket ? <button type="button" className="button button-primary" disabled={!config?.intake_released && !api.pending || api.busy || !fresh || !api.online || api.conflict} onClick={()=>void create()}>{t(api.pending?'retry':'newSale')}</button> : <>
 <fieldset disabled={locked}><label>{t('foodPreference')}<textarea maxLength={400} value={preference} onChange={e=>{setPreference(e.target.value);setDirty(true);}}/></label><p>{t('preferenceHelp')}</p>{pos && <><label>{t('posSearch')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{t('posCategory')}<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t('posCategory')}</option>{Array.from(new Map(items.filter(i=>i.category).map(i=>[i.category!.public_ref,i.category!])).values()).map(c=><option key={c.public_ref} value={c.public_ref}>{c.name}</option>)}</select></label></>}<label>{t('counter')}<select value={method} onChange={e=>{setMethod(e.target.value);setDirty(true);}}><option value="on_premise">{t('on_premise')}</option><option value="takeaway">{t('takeaway')}</option></select></label><label>{t('plate')}<input maxLength={64} value={plate} placeholder={`${t('standalone')} / ${t('plate')} 1`} onChange={e=>setPlate(e.target.value)}/></label>
 <div className="rst-menu-rows">{items.filter(item=>!pos || (!category || item.category?.public_ref===category) && (item.name??'').toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(item=><div className="rst-menu-row" key={item.public_ref}><span>{item.name}{pos && item.availability!=='available' && ` · ${t('unavailable')}`}</span><span>{item.pricing_model==='UNIT_PRICED'?`${item.unit_price} ${item.currency} / ${item.sale_unit_label}`:item.pricing_model==='AMOUNT_PRICED'?item.amount_mode==='flexible'?`${basicText(locale,'flexibleFrom')} ${item.minimum_amount} ${item.currency}`:`${(item.allowed_amounts as string[]).join('; ')} ${item.currency}`:t('unknown')}</span><button type="button" disabled={pos && item.availability!=='available' || item.pricing_model==='UNKNOWN' || !!plate && item.presentation!=='component'} onClick={()=>{setLines(old=>[...old,{key:crypto.randomUUID(),item_ref:item.public_ref,name:item.name ?? item.public_ref,currency:String(item.currency ?? ""),flexible:item.amount_mode==='flexible',amounts:item.allowed_amounts as string[]|undefined,plate,...(item.pricing_model==='UNIT_PRICED'?{quantity:1}:{selected_amount:item.amount_mode==='flexible'?String(item.minimum_amount):(item.allowed_amounts as string[])[0]})}]);setDirty(true);}}>{t('add')}</button></div>)}</div><div className="rst-actions" hidden={pos}><button type="button" disabled={menuPage===1} onClick={()=>{setFresh(false);setMenuPage(p=>p-1);}}>{t('previous')}</button><button type="button" disabled={menuPage*20>=menuTotal} onClick={()=>{setFresh(false);setMenuPage(p=>p+1);}}>{t('next')}</button></div>
 {['',...new Set(lines.map(l=>l.plate).filter(Boolean))].map(group=><section key={group}><h3>{group?`${t('plate')} · ${group}`:t('standalone')}</h3>{lines.filter(l=>l.plate===group).map(l=>{return <div className="rst-row" key={l.key}><span>{l.name} · {l.plate || t('standalone')}</span><label>{t(l.quantity!=null?'quantity':'amount')}{l.quantity!=null?<input type="number" min="1" step="1" value={l.quantity} onChange={e=>{setLines(old=>old.map(x=>x.key===l.key?{...x,quantity:Number(e.target.value)}:x));setDirty(true);}}/>:l.flexible?<input inputMode="decimal" value={l.selected_amount ?? ""} onChange={e=>{setLines(old=>old.map(x=>x.key===l.key?{...x,selected_amount:e.target.value.replace(",",".")}:x));setDirty(true);}}/>:<select value={l.selected_amount} onChange={e=>{setLines(old=>old.map(x=>x.key===l.key?{...x,selected_amount:e.target.value}:x));setDirty(true);}}>{(l.amounts ?? [l.selected_amount!]).map(a=><option key={a}>{a}</option>)}</select>}</label><button type="button" onClick={()=>{setLines(old=>old.filter(x=>x.key!==l.key));setDirty(true);}}>{t('remove')}</button></div>;})}</section>)}</fieldset>
 <div className="rst-actions"><button type="button" disabled={api.busy || api.conflict || !fresh || !api.online || !!api.pending && api.pending.method!=='PATCH'} onClick={()=>void edit(false)}>{t(api.pending?.method==='PATCH'?'retry':'save')}</button><button type="button" className="button button-primary" disabled={api.busy || api.conflict || !fresh || !api.online || !lines.length || !!api.pending && !api.pending.path.endsWith('/quote')} onClick={()=>void edit(true)}>{t(api.pending?.path.endsWith('/quote')?'retry':'quote')}</button></div>
 {basket.quote && !dirty && <><FoodTerms terms={basket.quote} locale={locale}/><p>{t(method)}</p><p>{t('payment')}</p><p>{t('confirmAction')}</p><button type="button" className="button button-primary" disabled={!config?.intake_released && !api.pending || api.busy || api.conflict || !fresh || !api.online || !!api.pending && !api.pending.path.endsWith('/finalize')} onClick={()=>void finalize()}>{t(api.pending?.path.endsWith('/finalize')?'retry':'complete')}</button></>}
 </>}
 {pos && <section><h3>{t('posRecent')}</h3>{recent.map(value=><details key={value.order_ref}><summary>{value.receipt_terms?.order_total} {value.receipt_terms?.currency} · {dateText(value.submitted_at,locale)}</summary><ReceiptCard order={value} locale={locale}/></details>)}</section>}
 </article>;
}
