import type { Locale } from "../../lib/i18n";
import { LegalCallout, LegalList, LegalPage, LegalSection } from "../legal/legal-document";

type Section = { id: string; title: string; before: readonly string[]; items?: readonly string[]; after?: readonly string[]; callout?: boolean };

const content: Record<Locale,{eyebrow:string;title:string;updated:string;reading:string;sections:readonly Section[];closingTitle:string;closing:readonly string[]}> = {
  en: {
    eyebrow:"Trust centre", title:"Data Protection & Privacy", updated:"Last updated: August 2026", reading:"7 min read",
    sections:[
      {id:"our-commitment",title:"Our Commitment",before:["At NIHILOBA, protecting personal information is a fundamental part of how we design and develop our digital products.","Although SHIDA continues to evolve, privacy and data protection are considered from the earliest stages of product development rather than being added afterwards.","Our objective is to build services that are transparent, respectful of users and aligned with internationally recognised privacy principles, including the General Data Protection Regulation where applicable."]},
      {id:"what-is-data-protection",title:"What Is Data Protection?",before:["Data protection refers to the principles, practices and safeguards used to manage personal information responsibly.","It includes decisions about:"],items:["what information is collected;","why the information is needed;","how it is used;","who may access it;","how long it is retained;","how it is protected;","how users can exercise control over it."],after:["At NIHILOBA, data protection is treated as both a product responsibility and an engineering responsibility."]},
      {id:"what-is-gdpr",title:"What Is GDPR?",before:["The General Data Protection Regulation, commonly known as GDPR, is a European privacy regulation that establishes rules for how personal information should be collected, processed and protected.","Even when GDPR is not legally required in every situation, many of its principles represent responsible product design and sound data governance.","NIHILOBA uses these principles as guidance when designing SHIDA and its future products.","Unless explicitly stated, NIHILOBA does not claim official GDPR certification."]},
      {id:"privacy-by-design",title:"Privacy by Design",before:["Privacy is not treated as a feature that is added after development.","It is considered during product design, system architecture and feature development.","Whenever new functionality is introduced, we evaluate questions such as:"],items:["Is this information genuinely necessary?","Can less information achieve the same result?","Who needs access to the information?","Can the information be shared later instead of immediately?","How can users remain in control of their information?","Could the workflow expose information unnecessarily?"],after:["This approach helps reduce unnecessary data collection and supports more trustworthy digital experiences."]},
      {id:"data-minimisation",title:"Data Minimisation",before:["SHIDA aims to collect only the information required to provide the requested service.","Examples include:"],items:["employment workflows collecting information relevant to recruitment;","housing workflows collecting information necessary for property management and visit requests;","appointment workflows collecting only the details required to organise the meeting;","service providers receiving only the information necessary to respond to a booking or service request;","transport workflows using only the information necessary to organise the requested journey."],after:["NIHILOBA continues to review its data model and workflows to avoid collecting information that is not required."]},
      {id:"purpose-limitation",title:"Purpose Limitation",before:["Personal information should be used only for the purpose for which it was collected.","Examples include:"],items:["managing appointments;","processing employment applications;","publishing professional services;","organising housing visits;","coordinating transport requests;","providing support;","protecting the platform from misuse."],after:["Information should not be reused for unrelated purposes without an appropriate legal basis or clear communication to the user."]},
      {id:"transparency",title:"Transparency",before:["Users should be able to understand:"],items:["what information is collected;","why it is collected;","how it is used;","who may receive it;","how long it may be retained;","how they can request access, correction or deletion."],after:["NIHILOBA aims to explain these practices in clear language through its Privacy Policy and related trust documentation."]},
      {id:"user-rights",title:"User Rights",before:["Depending on applicable law, users may have rights including:"],items:["requesting access to their personal information;","correcting inaccurate or incomplete information;","requesting deletion of personal information;","objecting to certain types of processing;","requesting a copy of their information where applicable;","withdrawing consent where processing relies on consent;","requesting restriction of certain processing where applicable;","submitting a complaint to a competent supervisory authority where that right exists."],after:["Requests will be reviewed in accordance with applicable legal obligations and operational requirements."]},
      {id:"data-security",title:"Data Security",before:["Protecting information requires technical and organisational measures.","SHIDA is developed using practices intended to reduce unnecessary exposure of personal information.","Examples include:"],items:["encrypted HTTPS communication;","authenticated access to administrative functions;","restricted access to operational information;","secure cloud hosting;","controlled data-sharing workflows;","continuous software maintenance;","review of new features before deployment;","monitoring and troubleshooting where appropriate."],after:["Additional measures may be introduced as the platform grows."]},
      {id:"data-sharing",title:"Data Sharing",before:["NIHILOBA does not sell personal information.","Information is shared only when necessary to provide the requested service or when required by applicable law.","Examples include:"],items:["employers receiving applications submitted to them;","service providers receiving booking requests;","housing owners receiving visit requests;","organisations receiving appointment requests;","transport participants receiving information required to organise a journey."],after:["Information is not intended to be shared publicly unless required by the specific workflow or explicitly chosen by the user."]},
      {id:"lawful-basis",title:"Lawful Basis",before:["Where GDPR or similar laws apply, personal information may be processed under one or more recognised legal bases.","Depending on the activity, these may include:"],items:["consent;","performance of a contract or steps requested before entering into a contract;","compliance with a legal obligation;","legitimate interests, where those interests do not override the rights and freedoms of the user;","protection of vital interests in exceptional circumstances;","performance of a task carried out in the public interest where applicable."],after:["The appropriate legal basis depends on the specific workflow and context.","NIHILOBA will continue refining how lawful bases are documented as the platform and its organisational structure develop."]},
      {id:"data-retention",title:"Data Retention",before:["Personal information should not be retained longer than necessary.","Retention periods may depend on:"],items:["the purpose of the processing;","the status of an account, listing, request or appointment;","legal obligations;","fraud prevention;","dispute resolution;","security and operational requirements."],after:["Users may request deletion of their personal information, subject to applicable legal and operational requirements."]},
      {id:"international-users",title:"International Users and Data Transfers",before:["Although SHIDA’s first use cases have focused on the Democratic Republic of the Congo, the platform is designed to support users internationally.","As NIHILOBA expands, information may be processed through service providers or infrastructure located in different countries.","Where applicable, NIHILOBA will consider appropriate safeguards for international data transfers and will continue adapting its practices to the laws of the countries in which it operates."]},
      {id:"childrens-data",title:"Children’s Data",before:["SHIDA is not intended for children to use independently where parental or legal guardian consent is required by applicable law.","Some services, such as school appointments, may involve information submitted by a parent or legal guardian on behalf of a child.","NIHILOBA aims to limit the collection of children’s data and to process such information only where necessary for the requested service."]},
      {id:"continuous-improvement",title:"Continuous Improvement",before:["Privacy and data protection are ongoing responsibilities.","As SHIDA introduces new capabilities, including the Business Layer, additional marketplaces and future integrations, privacy considerations will continue to be reviewed throughout product design and development.","Policies, data models and technical safeguards may evolve to reflect:"],items:["changes to the product;","changes in applicable law;","improved engineering practices;","new operational requirements;","user expectations;","security considerations."]},
      {id:"important-notice",title:"Important Notice",before:["NIHILOBA is committed to developing SHIDA in accordance with recognised privacy and data protection principles.","However, unless explicitly stated, NIHILOBA does not claim:"],items:["official GDPR certification;","ISO 27001 certification;","SOC 2 compliance;","or any other external privacy or security certification."],after:["If formal certifications or compliance programmes are completed in the future, this page will be updated accordingly."],callout:true},
      {id:"contact",title:"Contact",before:["If you have questions about privacy, data protection or the exercise of your rights, you may contact NIHILOBA at:","Email: shida.nihiloba@gmail.com","A dedicated privacy or data protection email address under @nihiloba.com will be introduced as NIHILOBA continues to grow."]},
    ],
    closingTitle:"Closing Statement",closing:["Protecting personal information is both a legal responsibility and an essential part of building technology that people can trust.","As NIHILOBA grows, we remain committed to developing products that balance accessibility, innovation and responsible data protection for individuals, professionals, businesses and institutions."],
  },
  fr: {
    eyebrow:"Centre de confiance", title:"Protection des données et de la vie privée", updated:"Dernière mise à jour : août 2026", reading:"7 min de lecture",
    sections:[
      {id:"our-commitment",title:"Notre engagement",before:["Chez NIHILOBA, la protection des données personnelles fait partie intégrante de la manière dont nous concevons et développons nos produits numériques.","Même si SHIDA continue d’évoluer, la protection de la vie privée et des données est prise en compte dès les premières étapes du développement, et non ajoutée après la conception du produit.","Notre objectif est de créer des services transparents, respectueux des utilisateurs et alignés sur des principes reconnus de protection des données, notamment ceux du Règlement général sur la protection des données lorsque celui-ci est applicable."]},
      {id:"what-is-data-protection",title:"Qu’est-ce que la protection des données ?",before:["La protection des données désigne l’ensemble des principes, pratiques et mesures utilisés pour gérer les données personnelles de manière responsable.","Elle concerne notamment les décisions relatives :"],items:["aux informations collectées ;","aux raisons pour lesquelles elles sont nécessaires ;","à la manière dont elles sont utilisées ;","aux personnes autorisées à y accéder ;","à leur durée de conservation ;","aux mesures mises en place pour les protéger ;","aux moyens permettant aux utilisateurs de garder le contrôle sur leurs informations."],after:["Chez NIHILOBA, la protection des données constitue à la fois une responsabilité liée au produit et une responsabilité d’ingénierie."]},
      {id:"what-is-gdpr",title:"Qu’est-ce que le RGPD ?",before:["Le Règlement général sur la protection des données, couramment appelé RGPD, est une réglementation européenne qui établit des règles concernant la collecte, l’utilisation et la protection des données personnelles.","Même lorsque le RGPD n’est pas juridiquement applicable dans toutes les situations, plusieurs de ses principes représentent de bonnes pratiques en matière de conception de produits et de gouvernance des données.","NIHILOBA utilise ces principes comme référence lors de la conception de SHIDA et de ses futurs produits.","Sauf indication explicite, NIHILOBA ne revendique aucune certification officielle au titre du RGPD."]},
      {id:"privacy-by-design",title:"Protection de la vie privée dès la conception",before:["La protection de la vie privée n’est pas considérée comme une fonctionnalité ajoutée à la fin du développement.","Elle est prise en compte pendant la conception du produit, l’architecture du système et le développement des fonctionnalités.","Lorsqu’une nouvelle fonctionnalité est envisagée, nous examinons notamment les questions suivantes :"],items:["Cette information est-elle réellement nécessaire ?","Le même résultat peut-il être obtenu avec moins d’informations ?","Qui doit avoir accès à cette information ?","Peut-elle être partagée plus tard plutôt qu’immédiatement ?","Comment l’utilisateur peut-il conserver le contrôle de ses informations ?","Le processus risque-t-il d’exposer inutilement certaines données ?"],after:["Cette approche permet de réduire la collecte inutile de données et de créer des expériences numériques plus dignes de confiance."]},
      {id:"data-minimisation",title:"Minimisation des données",before:["SHIDA vise à collecter uniquement les informations nécessaires à la fourniture du service demandé.","Cela peut notamment concerner :"],items:["les processus liés à l’emploi, qui collectent les informations utiles au recrutement ;","les processus liés au logement, qui collectent les informations nécessaires à la gestion des annonces et des demandes de visite ;","les rendez-vous, qui utilisent uniquement les informations nécessaires à leur organisation ;","les professionnels, qui reçoivent uniquement les informations nécessaires pour répondre à une réservation ou à une demande de service ;","les processus liés au transport, qui utilisent uniquement les informations nécessaires à l’organisation du trajet."],after:["NIHILOBA continue d’examiner son modèle de données et ses processus afin d’éviter la collecte d’informations inutiles."]},
      {id:"purpose-limitation",title:"Limitation des finalités",before:["Les données personnelles doivent être utilisées uniquement pour les finalités pour lesquelles elles ont été collectées.","Cela peut notamment inclure :"],items:["la gestion des rendez-vous ;","le traitement des candidatures ;","la publication de services professionnels ;","l’organisation de visites de logement ;","la coordination des demandes de transport ;","l’assistance aux utilisateurs ;","la protection de la plateforme contre les abus."],after:["Les informations ne doivent pas être réutilisées à des fins sans rapport avec leur collecte sans base juridique appropriée ou sans information claire de l’utilisateur."]},
      {id:"transparency",title:"Transparence",before:["Les utilisateurs doivent pouvoir comprendre :"],items:["quelles informations sont collectées ;","pourquoi elles sont collectées ;","comment elles sont utilisées ;","qui peut les recevoir ;","combien de temps elles peuvent être conservées ;","comment demander leur accès, leur correction ou leur suppression."],after:["NIHILOBA cherche à expliquer ces pratiques dans un langage clair au moyen de sa Politique de confidentialité et de ses autres documents de confiance."]},
      {id:"user-rights",title:"Droits des utilisateurs",before:["Selon la loi applicable, les utilisateurs peuvent notamment disposer du droit de :"],items:["demander l’accès à leurs données personnelles ;","corriger des données inexactes ou incomplètes ;","demander la suppression de leurs données personnelles ;","s’opposer à certains traitements ;","demander une copie de leurs informations lorsque cela est applicable ;","retirer leur consentement lorsque le traitement repose sur celui-ci ;","demander la limitation de certains traitements lorsque cela est applicable ;","déposer une réclamation auprès d’une autorité de contrôle compétente lorsque ce droit existe."],after:["Les demandes seront examinées conformément aux obligations légales et aux exigences opérationnelles applicables."]},
      {id:"data-security",title:"Sécurité des données",before:["La protection des informations nécessite des mesures techniques et organisationnelles.","SHIDA est développé au moyen de pratiques destinées à réduire l’exposition inutile des données personnelles.","Cela peut notamment inclure :"],items:["les communications chiffrées par HTTPS ;","l’accès authentifié aux fonctions administratives ;","la limitation de l’accès aux informations opérationnelles ;","un hébergement cloud sécurisé ;","des processus contrôlés de partage des informations ;","la maintenance continue du logiciel ;","l’examen des nouvelles fonctionnalités avant leur mise en production ;","la surveillance et le diagnostic lorsque cela est approprié."],after:["Des mesures supplémentaires pourront être introduites à mesure que la plateforme se développe."]},
      {id:"data-sharing",title:"Partage des données",before:["NIHILOBA ne vend pas les données personnelles.","Les informations sont partagées uniquement lorsque cela est nécessaire à la fourniture du service demandé ou lorsque la loi applicable l’exige.","Cela peut notamment concerner :"],items:["les employeurs qui reçoivent les candidatures qui leur sont adressées ;","les professionnels qui reçoivent des demandes de réservation ;","les propriétaires qui reçoivent des demandes de visite ;","les organisations qui reçoivent des demandes de rendez-vous ;","les participants à un trajet qui reçoivent les informations nécessaires à son organisation."],after:["Les informations ne sont pas destinées à être rendues publiques, sauf lorsque le processus concerné l’exige ou lorsque l’utilisateur choisit explicitement de les partager."]},
      {id:"lawful-basis",title:"Base juridique du traitement",before:["Lorsque le RGPD ou une législation similaire est applicable, les données personnelles peuvent être traitées sur la base d’un ou de plusieurs fondements juridiques reconnus.","Selon l’activité, ceux-ci peuvent notamment comprendre :"],items:["le consentement ;","l’exécution d’un contrat ou de mesures demandées avant la conclusion d’un contrat ;","le respect d’une obligation légale ;","l’intérêt légitime, lorsque celui-ci ne prévaut pas sur les droits et libertés de l’utilisateur ;","la protection des intérêts vitaux dans des circonstances exceptionnelles ;","l’exécution d’une mission d’intérêt public lorsque cela est applicable."],after:["La base juridique appropriée dépend du processus concerné et de son contexte.","NIHILOBA continuera de préciser la documentation relative aux bases juridiques à mesure que la plateforme et son organisation se développent."]},
      {id:"data-retention",title:"Conservation des données",before:["Les données personnelles ne doivent pas être conservées plus longtemps que nécessaire.","La durée de conservation peut dépendre :"],items:["de la finalité du traitement ;","du statut d’un compte, d’une annonce, d’une demande ou d’un rendez-vous ;","des obligations légales ;","de la prévention de la fraude ;","du règlement des litiges ;","des exigences de sécurité et de fonctionnement."],after:["Les utilisateurs peuvent demander la suppression de leurs données personnelles, sous réserve des obligations légales et opérationnelles applicables."]},
      {id:"international-users",title:"Utilisateurs internationaux et transferts de données",before:["Bien que les premiers cas d’utilisation de SHIDA se soient concentrés sur la République démocratique du Congo, la plateforme est conçue pour accueillir des utilisateurs dans différents pays.","À mesure que NIHILOBA se développe, certaines informations peuvent être traitées par des prestataires de services ou des infrastructures situés dans d’autres pays.","Lorsque cela est applicable, NIHILOBA examinera les garanties appropriées relatives aux transferts internationaux de données et continuera d’adapter ses pratiques aux lois des pays dans lesquels ses services sont proposés."]},
      {id:"childrens-data",title:"Données relatives aux enfants",before:["SHIDA n’est pas destiné à être utilisé de manière indépendante par des enfants lorsque le consentement d’un parent ou d’un représentant légal est requis par la loi applicable.","Certains services, notamment les rendez-vous scolaires, peuvent impliquer des informations communiquées par un parent ou un représentant légal au nom d’un enfant.","NIHILOBA vise à limiter la collecte des données relatives aux enfants et à traiter ces informations uniquement lorsqu’elles sont nécessaires au service demandé."]},
      {id:"continuous-improvement",title:"Amélioration continue",before:["La protection de la vie privée et des données constitue une responsabilité permanente.","À mesure que SHIDA introduit de nouvelles fonctionnalités, notamment la couche Business, de nouveaux marchés et de futures intégrations, les considérations liées à la protection des données continueront d’être examinées pendant la conception et le développement.","Les politiques, modèles de données et mesures techniques pourront évoluer afin de tenir compte :"],items:["des évolutions du produit ;","des modifications de la loi applicable ;","de l’amélioration des pratiques d’ingénierie ;","des nouvelles exigences opérationnelles ;","des attentes des utilisateurs ;","des considérations de sécurité."]},
      {id:"important-notice",title:"Avis important",before:["NIHILOBA s’engage à développer SHIDA conformément à des principes reconnus de protection de la vie privée et des données.","Toutefois, sauf indication explicite, NIHILOBA ne revendique pas :"],items:["de certification officielle au titre du RGPD ;","de certification ISO 27001 ;","de conformité SOC 2 ;","ni aucune autre certification externe en matière de protection des données ou de sécurité."],after:["Si des certifications formelles ou des programmes de conformité sont obtenus à l’avenir, cette page sera mise à jour."],callout:true},
      {id:"contact",title:"Contact",before:["Pour toute question concernant la protection de la vie privée, des données ou l’exercice de vos droits, vous pouvez contacter NIHILOBA à l’adresse suivante :","E-mail : shida.nihiloba@gmail.com","Une adresse dédiée à la protection des données sous le domaine @nihiloba.com sera introduite à mesure que NIHILOBA se développe."]},
    ],
    closingTitle:"Déclaration finale",closing:["La protection des données personnelles constitue à la fois une responsabilité juridique et un élément essentiel de la construction de technologies dignes de confiance.","À mesure que NIHILOBA se développe, nous restons engagés à créer des produits qui équilibrent l’accessibilité, l’innovation et une protection responsable des données pour les particuliers, les professionnels, les entreprises et les institutions."],
  },
};

export function DataProtectionPage({locale}:{locale:Locale}) {
  const c=content[locale];
  const toc=c.sections.map(({id,title})=>({id,label:title}));
  return <LegalPage locale={locale} eyebrow={c.eyebrow} title={c.title} updated={c.updated} readingTime={c.reading} toc={toc}>
    {c.sections.map((section)=>{
      const body=<>{section.before.map(p=><p key={p}>{p}</p>)}{section.items&&<LegalList items={section.items}/>} {section.after?.map(p=><p key={p}>{p}</p>)}</>;
      return <LegalSection id={section.id} title={section.title} key={section.id}>{section.callout?<LegalCallout label={section.title}>{body}</LegalCallout>:body}</LegalSection>;
    })}
    <LegalSection id="closing-statement" title={c.closingTitle}>{c.closing.map(p=><p key={p}>{p}</p>)}</LegalSection>
  </LegalPage>;
}
