import Image from "next/image";
import type { ReactNode } from "react";
import type { Locale } from "../../lib/i18n";
import { localizedPath } from "../../lib/i18n";
import { CONTACT_EMAILS, OFFICIAL_CHANNELS, SOCIAL_LINKS } from "../../lib/brand";
import { BrandLogo } from "../brand-logo";
import { ButtonLink } from "../button-link";
import { CtaSection } from "../cta-section";
import { Hero } from "../hero";
import { BookIcon, BriefcaseIcon, CarIcon, CheckIcon, HomeIcon, LightbulbIcon, MailIcon, ToolsIcon } from "../icons";
import { SectionHeading } from "../section-heading";

const copy = {
  en: {
    common: { learn: "Learn more", contact: "Contact NIHILOBA", talk: "Start a conversation", planned: "Planned initiative", available: "Available now", open: "Open SHIDA on WhatsApp" },
    home: {
      eyebrow: "Roots. Impact. Future.", title: "Creating practical digital solutions with roots and purpose.", description: "NIHILOBA develops technology that responds to real needs. Our work begins with SHIDA, a WhatsApp-based platform that connects people to opportunities, services, housing and transport.", primary: "Discover SHIDA", secondary: "Our story",
      introTitle: "Technology should feel useful from the start.", intro: "We begin with the realities of daily life: the tools people already use, the information they need and the barriers that slow them down. This approach helps us create products that are easier to reach and simpler to understand.",
      storyTitle: "A name shaped by creation and the baobab.", story: "NIHILOBA draws inspiration from creatio ex nihilo, creation from nothing, and from the symbolic power of the baobab. Together, these ideas express our belief that a grounded idea can grow into lasting, shared impact.", storyLink: "Read our story",
      productTitle: "Our first product begins on WhatsApp.", productText: "SHIDA brings employment opportunities, services, housing and transport into a familiar conversation. There is no new application to install.",
      educationTitle: "Practical learning can widen opportunity.", educationText: "NIHILOBA Education is a planned nonprofit initiative focused on digital literacy, accessible learning and useful technology skills.",
      ctaTitle: "Have a question or an idea to discuss?", ctaText: "We welcome conversations with users, communities, companies, institutions and potential partners.",
    },
    about: {
      eyebrow: "About NIHILOBA", title: "Purpose gives technology direction.", description: "NIHILOBA develops accessible digital products that respond to practical needs. We want technology to help more people participate, connect and move forward.",
      purposeTitle: "Why NIHILOBA exists", purpose: ["Access to digital tools is growing, but access to useful outcomes is still uneven. Finding work, reaching a service or learning a practical skill can remain unnecessarily difficult.", "NIHILOBA focuses on this gap. We create clear digital pathways for people, professionals and institutions. SHIDA is our first product and the beginning of that work."],
      storyTitle: "The story behind the name", story: ["NIHILOBA is inspired by creatio ex nihilo, meaning creation out of nothing, and rooted in the symbolic power of the baobab, represented by ‘BA’.", "In many Bantu cultures, the baobab is more than a tree. It represents protection, wisdom, resilience, continuity and spiritual connection. It is a place where communities gather, exchange knowledge, share stories and grow stronger together.", "NIHILOBA carries this meaning forward as a symbol of support, belonging, collective strength and the ability to create lasting impact from an idea."],
      inspirationNote: "This is the meaning and symbolism chosen for the NIHILOBA brand. It is not presented as a linguistic derivation.",
      founderTitle: "Francis Mabala", founderRole: "Founder of NIHILOBA and SHIDA", founder: ["Francis Mabala is an engineer and the founder of NIHILOBA and SHIDA. Born in the Democratic Republic of the Congo and now based in Stockholm, he created NIHILOBA to develop practical digital tools that respond to everyday realities.", "His first product, SHIDA, grew from a simple observation: access to opportunities and essential services is often made more difficult by fragmented systems, long waiting times and digital tools that do not reflect how people already communicate. By building directly on WhatsApp, Francis aims to make technology more accessible to individuals, professionals, businesses and institutions.", "His work combines engineering, product development and a long-term commitment to useful and inclusive digital transformation."],
    },
    products: { eyebrow: "Our products", title: "Start with a real need. Keep the experience simple.", description: "NIHILOBA develops products that help people reach useful information and services through accessible technology.", shida: "SHIDA is the first digital product developed by NIHILOBA. It connects people to employment, services, housing and transport through WhatsApp.", futureTitle: "What comes next", future: "We will develop new products carefully and share them when their purpose, scope and value are clear. For now, our focus is SHIDA." },
    shida: {
      eyebrow: "A product by NIHILOBA", title: "Everyday opportunities, available through WhatsApp.", description: "SHIDA connects people to employment, services, housing and transport in a familiar WhatsApp conversation. Users do not need to install a new application.",
      first: "SHIDA is the first digital product developed by NIHILOBA.", marketsTitle: "What you can explore today", marketsDesc: "SHIDA currently covers four practical areas.", employment: "Employment", employmentText: "Find and explore relevant employment opportunities.", services: "Services", servicesText: "Connect with professionals and everyday services.", housing: "Housing", housingText: "Access housing information through a direct channel.", transport: "Transport", transportText: "Explore useful transport options and information.",
      bookingTitle: "Appointments and bookings", booking: "Appointment and booking management is one of SHIDA’s capabilities. It supports professionals and organisations within a broader platform that also covers opportunities, services, housing and transport.",
      plannedTitle: "Planned developments", plannedDesc: "These ideas are part of SHIDA’s roadmap and are not currently available.", qr: "QR-based appointment confirmation", qrText: "A planned way to simplify arrival and confirmation for appointments.", pickup: "Pickup reminders", pickupText: "Planned reminders to help users keep track of scheduled pickups.", plannedNote: "Availability and timing may change as these features are developed.",
      actionTitle: "See SHIDA in action", actionIntro: "SHIDA works inside a familiar WhatsApp conversation. Users choose a marketplace, follow guided steps and complete their request without downloading another application.",
      journey: [["Choose a marketplace", "Choose employment, services, housing or transport.", "/shida-marketplace-menu.jpeg"], ["Explore a service category", "Browse categories adapted to different professional and institutional needs.", "/shida-service-categories.jpeg"], ["Create or publish an opportunity", "Review a job offer before publication.", "/shida-job-offer-summary.jpeg"], ["Configure professional availability", "Define availability for bookings and service requests.", "/shida-service-availability.jpeg"]],
      howTitle: "How SHIDA works", howSteps: ["Save the SHIDA WhatsApp number.", "Send “Hello” or “Bonjour”.", "Choose a marketplace.", "Complete the process directly in WhatsApp."],
      availableTitle: "Available today", availableIntro: "SHIDA currently supports these areas through WhatsApp. The depth of each journey continues to develop according to user and partner needs.", bookingCapability: "Appointment and booking management", bookingCapabilityText: "Manage service availability, appointments and booking requests as one capability within the wider service marketplace.",
      audienceTitle: "Who SHIDA can support", audience: "SHIDA can adapt booking, service, employment and operational flows to different sectors while keeping access within WhatsApp.", audiences: ["Individuals", "Independent professionals", "Businesses", "Schools", "Churches", "Clinics", "Hotels", "Restaurants", "Public institutions"],
      comingTitle: "Coming next", comingIntro: "The following developments are planned and are not yet available. No release dates have been announced.", businessTitle: "Business Layer", businessLabel: "Coming next", business: "The Business Layer will give businesses and institutions additional tools to manage teams, services, availability, appointments and operational activity through SHIDA.",
      roadmap: [["Diaspora Marketplace", "A future marketplace intended to connect diaspora communities with relevant services, opportunities and trusted local needs."], ["Wenze Marketplace", "A marketplace concept for local commerce, sellers and buyers operating through WhatsApp."], ["Extended hotel booking", "An extension of SHIDA’s booking capabilities for hotels and accommodation providers."], ["Restaurant food ordering", "An extension of the restaurant experience beyond table reservations to food ordering."], ["QR-based appointment confirmation", "A planned way to simplify arrival and confirmation for appointments."], ["Pickup reminders", "Planned reminders to help users keep track of scheduled pickups."]],
      plannedLabel: "Planned development", ctaTitle: "Send a message to begin.", ctaText: "Open SHIDA on WhatsApp at +46 76 970 90 59. The message “Bonjour” is ready for you.",
    },
    education: { eyebrow: "Planned nonprofit initiative", title: "Practical digital learning, made more accessible.", description: "NIHILOBA Education is a planned nonprofit initiative. It will focus on digital literacy, practical technology education and accessible learning.", visionTitle: "Learning connected to daily life", vision: ["The initiative aims to help learners use digital tools with greater confidence. Content will connect technology with study, work and practical problem-solving.", "NIHILOBA Education remains in the planning stage. There are no active programmes at this time. Confirmed details will be shared as the initiative develops."], focusTitle: "Areas of focus", literacy: "Digital literacy", literacyText: "Confidence with the tools that shape daily participation.", practical: "Practical technology", practicalText: "Learning linked to real tasks and useful outcomes.", access: "Accessible learning", accessText: "Formats that consider different contexts and starting points." },
    contact: { eyebrow: "Contact", title: "Let’s talk about what could be useful.", description: "Contact NIHILOBA to ask about SHIDA, share a relevant need or discuss a possible collaboration.", emailTitle: "Email NIHILOBA", emailText: "For product questions, general enquiries, partnerships and institutional conversations.", emailNote: `Partnership enquiries: ${CONTACT_EMAILS.partnerships}`, send: "Send an email", social: "Social channels", official: "Official" },
  },
  fr: {
    common: { learn: "En savoir plus", contact: "Contacter NIHILOBA", talk: "Démarrer une conversation", planned: "Initiative en projet", available: "Disponible maintenant", open: "Ouvrir SHIDA sur WhatsApp" },
    home: {
      eyebrow: "Racines. Impact. Avenir.", title: "Créer des solutions numériques utiles, ancrées dans une vision.", description: "NIHILOBA développe des technologies qui répondent à des besoins réels. Notre parcours commence avec SHIDA, une plateforme accessible sur WhatsApp qui relie les personnes aux opportunités, aux services, au logement et au transport.", primary: "Découvrir SHIDA", secondary: "Notre histoire",
      introTitle: "La technologie doit être utile dès le départ.", intro: "Nous partons des réalités du quotidien : les outils que les personnes utilisent déjà, les informations dont elles ont besoin et les obstacles qui les ralentissent. Cette approche nous aide à créer des produits plus accessibles et plus simples à comprendre.",
      storyTitle: "Un nom inspiré par la création et le baobab.", story: "NIHILOBA s’inspire de creatio ex nihilo, créer à partir de rien, et de la force symbolique du baobab. Ces deux idées expriment notre conviction : une idée bien ancrée peut produire un impact durable et partagé.", storyLink: "Découvrir notre histoire",
      productTitle: "Notre premier produit commence sur WhatsApp.", productText: "SHIDA rassemble les opportunités d’emploi, les services, le logement et le transport dans une conversation familière. Aucune nouvelle application n’est nécessaire.",
      educationTitle: "L’apprentissage pratique peut élargir les possibilités.", educationText: "NIHILOBA Education est une initiative à but non lucratif en projet, consacrée à la culture numérique, à l’apprentissage accessible et aux compétences technologiques utiles.",
      ctaTitle: "Une question ou une idée à partager ?", ctaText: "Nous échangeons volontiers avec les utilisateurs, les communautés, les entreprises, les institutions et les partenaires potentiels.",
    },
    about: {
      eyebrow: "À propos de NIHILOBA", title: "La vision donne une direction à la technologie.", description: "NIHILOBA développe des produits numériques accessibles qui répondent à des besoins concrets. Nous voulons aider davantage de personnes à participer, à se connecter et à avancer.",
      purposeTitle: "Pourquoi NIHILOBA existe", purpose: ["L’accès aux outils numériques progresse, mais leurs bénéfices restent inégalement répartis. Trouver un emploi, accéder à un service ou acquérir une compétence pratique peut encore être inutilement compliqué.", "NIHILOBA agit sur cet écart. Nous créons des parcours numériques clairs pour les personnes, les professionnels et les institutions. SHIDA est notre premier produit et le point de départ de ce travail."],
      storyTitle: "L’histoire derrière le nom", story: ["NIHILOBA s’inspire de l’expression latine creatio ex nihilo, qui signifie créer à partir de rien, et de la force symbolique du baobab, représentée par « BA ».", "Dans de nombreuses cultures bantoues, le baobab est bien plus qu’un arbre. Il symbolise la protection, la sagesse, la résilience, la continuité et le lien spirituel. C’est un lieu où les communautés se rassemblent, transmettent leurs connaissances, partagent leurs histoires et deviennent plus fortes ensemble.", "NIHILOBA prolonge cette symbolique en représentant le soutien, l’appartenance, la force collective et la capacité de transformer une idée en impact durable."],
      inspirationNote: "Il s’agit du sens et de la symbolique choisis pour la marque NIHILOBA. Nous ne les présentons pas comme une dérivation linguistique.",
      founderTitle: "Francis Mabala", founderRole: "Fondateur de NIHILOBA et de SHIDA", founder: ["Francis Mabala est ingénieur et fondateur de NIHILOBA et de SHIDA. Né en République démocratique du Congo et aujourd’hui basé à Stockholm, il a créé NIHILOBA afin de développer des outils numériques pratiques qui répondent aux réalités du quotidien.", "Son premier produit, SHIDA, est né d’un constat simple : l’accès aux opportunités et aux services essentiels est souvent compliqué par des systèmes fragmentés, de longues attentes et des outils numériques qui ne correspondent pas toujours aux habitudes des utilisateurs. En développant une solution directement accessible sur WhatsApp, Francis souhaite rendre la technologie plus accessible aux particuliers, aux professionnels, aux entreprises et aux institutions.", "Son travail réunit ingénierie, développement de produit et engagement à long terme en faveur d’une transformation numérique utile et inclusive."],
    },
    products: { eyebrow: "Nos produits", title: "Partir d’un besoin réel. Garder une expérience simple.", description: "NIHILOBA développe des produits qui facilitent l’accès à des informations et à des services utiles grâce à des technologies accessibles.", shida: "SHIDA est le premier produit numérique développé par NIHILOBA. Il relie les personnes à l’emploi, aux services, au logement et au transport via WhatsApp.", futureTitle: "La suite", future: "Nous développerons de nouveaux produits avec soin et les présenterons lorsque leur objectif, leur portée et leur valeur seront clairs. Pour le moment, nous nous concentrons sur SHIDA." },
    shida: {
      eyebrow: "Un produit NIHILOBA", title: "Les opportunités du quotidien, accessibles sur WhatsApp.", description: "SHIDA relie les personnes à l’emploi, aux services, au logement et au transport dans une conversation WhatsApp familière. Aucune nouvelle application n’est nécessaire.",
      first: "SHIDA est le premier produit numérique développé par NIHILOBA.", marketsTitle: "Ce que vous pouvez explorer aujourd’hui", marketsDesc: "SHIDA couvre actuellement quatre domaines pratiques.", employment: "Emploi", employmentText: "Trouvez et explorez des opportunités d’emploi pertinentes.", services: "Services", servicesText: "Entrez en contact avec des professionnels et des services du quotidien.", housing: "Logement", housingText: "Accédez à des informations sur le logement par un canal direct.", transport: "Transport", transportText: "Explorez des options et des informations utiles sur le transport.",
      bookingTitle: "Rendez-vous et réservations", booking: "La gestion des rendez-vous et des réservations est l’une des fonctions de SHIDA. Elle accompagne les professionnels et les organisations au sein d’une plateforme plus large, qui couvre aussi les opportunités, les services, le logement et le transport.",
      plannedTitle: "Développements prévus", plannedDesc: "Ces idées font partie de la feuille de route de SHIDA et ne sont pas encore disponibles.", qr: "Confirmation de rendez-vous par QR code", qrText: "Un moyen prévu pour simplifier l’arrivée et la confirmation des rendez-vous.", pickup: "Rappels de retrait", pickupText: "Des rappels prévus pour aider les utilisateurs à suivre les retraits programmés.", plannedNote: "La disponibilité et le calendrier peuvent évoluer pendant le développement.",
      actionTitle: "Découvrez SHIDA en action", actionIntro: "SHIDA fonctionne dans une conversation WhatsApp familière. Les utilisateurs choisissent un marché, suivent des étapes guidées et effectuent leur demande sans télécharger une nouvelle application.",
      journey: [["Choisissez un marché", "Choisissez entre l’emploi, les services, le logement ou le transport.", "/shida-marketplace-menu.jpeg"], ["Explorez une catégorie de services", "Parcourez des catégories adaptées aux besoins professionnels et institutionnels.", "/shida-service-categories.jpeg"], ["Créez ou publiez une opportunité", "Vérifiez une offre d’emploi avant sa publication.", "/shida-job-offer-summary.jpeg"], ["Configurez vos disponibilités professionnelles", "Définissez les disponibilités pour les rendez-vous et les demandes de service.", "/shida-service-availability.jpeg"]],
      howTitle: "Comment fonctionne SHIDA", howSteps: ["Enregistrez le numéro WhatsApp de SHIDA.", "Envoyez « Bonjour » ou « Mbote ».", "Choisissez un marché.", "Effectuez les étapes directement dans WhatsApp."],
      availableTitle: "Disponible aujourd’hui", availableIntro: "SHIDA prend actuellement en charge ces domaines via WhatsApp. La profondeur de chaque parcours continue d’évoluer selon les besoins des utilisateurs et des partenaires.", bookingCapability: "Gestion des rendez-vous et des réservations", bookingCapabilityText: "Gérez les disponibilités, les rendez-vous et les demandes de réservation comme une fonction intégrée au marché plus large des services.",
      audienceTitle: "À qui SHIDA peut servir", audience: "SHIDA peut adapter les parcours de réservation, de service, d’emploi et d’activité opérationnelle à différents secteurs, tout en restant accessible sur WhatsApp.", audiences: ["Particuliers", "Professionnels indépendants", "Entreprises", "Écoles", "Églises", "Cliniques", "Hôtels", "Restaurants", "Institutions publiques"],
      comingTitle: "Prochaines évolutions", comingIntro: "Les développements suivants sont prévus et ne sont pas encore disponibles. Aucune date de lancement n’a été annoncée.", businessTitle: "Couche Business", businessLabel: "Prochaine évolution", business: "La couche Business offrira aux entreprises et aux institutions des outils supplémentaires pour gérer les équipes, les services, les disponibilités, les rendez-vous et l’activité opérationnelle via SHIDA.",
      roadmap: [["Diaspora Marketplace", "Un futur marché destiné à relier les communautés de la diaspora à des services, des opportunités et des besoins locaux pertinents."], ["Wenze Marketplace", "Un concept de marché dédié au commerce local, aux vendeurs et aux acheteurs directement sur WhatsApp."], ["Réservation hôtelière étendue", "Une extension des fonctions de réservation de SHIDA pour les hôtels et les établissements d’hébergement."], ["Commande de repas au restaurant", "Une extension de l’expérience restaurant, au-delà de la réservation de table, vers la commande de repas."], ["Confirmation de rendez-vous par QR code", "Un moyen prévu pour simplifier l’arrivée et la confirmation des rendez-vous."], ["Rappels de retrait", "Des rappels prévus pour aider les utilisateurs à suivre les retraits programmés."]],
      plannedLabel: "Développement prévu", ctaTitle: "Envoyez un message pour commencer.", ctaText: "Ouvrez SHIDA sur WhatsApp au +46 76 970 90 59. Le message « Bonjour » est déjà préparé.",
    },
    education: { eyebrow: "Initiative à but non lucratif en projet", title: "Un apprentissage numérique pratique et plus accessible.", description: "NIHILOBA Education est une initiative à but non lucratif en projet. Elle sera consacrée à la culture numérique, à la formation technologique pratique et à l’apprentissage accessible.", visionTitle: "Un apprentissage lié à la vie quotidienne", vision: ["L’initiative vise à aider les apprenants à utiliser les outils numériques avec plus d’assurance. Les contenus relieront la technologie aux études, au travail et à la résolution de problèmes concrets.", "NIHILOBA Education est encore au stade de la planification. Aucun programme n’est actif actuellement. Les informations confirmées seront publiées au fil du développement de l’initiative."], focusTitle: "Domaines d’action", literacy: "Culture numérique", literacyText: "Mieux maîtriser les outils qui façonnent la participation quotidienne.", practical: "Technologie pratique", practicalText: "Relier l’apprentissage à des tâches réelles et à des résultats utiles.", access: "Apprentissage accessible", accessText: "Des formats adaptés à différents contextes et points de départ." },
    contact: { eyebrow: "Contact", title: "Parlons de ce qui pourrait être utile.", description: "Contactez NIHILOBA pour poser une question sur SHIDA, partager un besoin pertinent ou envisager une collaboration.", emailTitle: "Écrire à NIHILOBA", emailText: "Pour les questions sur nos produits, les demandes générales, les partenariats et les échanges institutionnels.", emailNote: `Demandes de partenariat : ${CONTACT_EMAILS.partnerships}`, send: "Envoyer un e-mail", social: "Réseaux sociaux", official: "Officiel" },
  },
} as const;

function Story({ locale, full = false }: { locale: Locale; full?: boolean }) {
  const t = copy[locale];
  const paragraphs = full ? t.about.story : [t.home.story];
  return (
    <section className="section story-section">
      <div className="container story-grid">
        <div className="story-symbol"><BrandLogo /></div>
        <div className="story-copy">
          <p className="eyebrow">{locale === "en" ? "Our name" : "Notre nom"}</p>
          <h2>{full ? t.about.storyTitle : t.home.storyTitle}</h2>
          {paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
          {full && <p className="inspiration-note">{t.about.inspirationNote}</p>}
          {!full && <ButtonLink href={localizedPath(locale,"/about")} variant="text">{t.home.storyLink}</ButtonLink>}
        </div>
        {full && <div className="name-breakdown"><div><strong>NIHILO</strong><span>{locale === "en" ? "Creation from nothing" : "Créer à partir de rien"}</span></div><div><strong>BA</strong><span>{locale === "en" ? "Baobab, roots, wisdom and collective strength" : "Baobab, racines, sagesse et force collective"}</span></div></div>}
      </div>
    </section>
  );
}

function ShidaPanel({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <article className="shida-panel"><div className="shida-logo-wrap"><BrandLogo brand="shida" /></div><div className="shida-preview-shot"><Image src="/shida-marketplace-menu.jpeg" alt={locale === "en" ? "SHIDA marketplace menu in WhatsApp" : "Menu des marchés SHIDA dans WhatsApp"} width={921} height={2048} sizes="(max-width: 700px) 72vw, 240px" /></div><div className="shida-panel-copy"><span className="availability"><span />{t.common.available}</span><p>{t.products.shida}</p><div className="preview-actions"><ButtonLink href={localizedPath(locale,"/shida")} variant="text">{t.home.primary}</ButtonLink><ButtonLink href={OFFICIAL_CHANNELS.whatsapp} variant="text" external>{t.common.open}</ButtonLink></div></div></article>;
}

export function HomePage({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <>
    <Hero eyebrow={t.home.eyebrow} title={t.home.title} description={t.home.description} primary={{href:localizedPath(locale,"/shida"),label:t.home.primary}} secondary={{href:localizedPath(locale,"/about"),label:t.home.secondary}} visual={<div className="hero-brand"><BrandLogo eager /><p>{locale === "en" ? "A technology company with a long view." : "Une entreprise technologique tournée vers l’avenir."}</p></div>} />
    <section className="section"><div className="container editorial-split"><span className="section-index">01</span><div><SectionHeading title={t.home.introTitle} /><p className="lead-copy">{t.home.intro}</p></div></div></section>
    <Story locale={locale} />
    <section className="section"><div className="container product-feature"><div><p className="eyebrow">SHIDA</p><h2>{t.home.productTitle}</h2><p>{t.home.productText}</p></div><ShidaPanel locale={locale} /></div></section>
    <section className="section education-strip"><div className="container editorial-split"><span className="planned-label">{t.common.planned}</span><div><h2>{t.home.educationTitle}</h2><p>{t.home.educationText}</p><ButtonLink href={localizedPath(locale,"/education")} variant="text">{t.common.learn}</ButtonLink></div></div></section>
    <CtaSection eyebrow={t.common.talk} title={t.home.ctaTitle} description={t.home.ctaText} href={localizedPath(locale,"/contact")} label={t.common.contact} />
  </>;
}

export function AboutPage({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <><Hero compact eyebrow={t.about.eyebrow} title={t.about.title} description={t.about.description} />
    <section className="section"><div className="container editorial-split"><span className="section-index">01</span><div><SectionHeading title={t.about.purposeTitle} />{t.about.purpose.map(p=><p className="lead-copy" key={p}>{p}</p>)}</div></div></section>
    <Story locale={locale} full />
    <section className="section founder-section"><div className="container founder-row"><figure className="founder-portrait"><Image src="/founder-francis-mabala.jpeg" alt={locale === "en" ? "Francis Mabala, founder of NIHILOBA and SHIDA" : "Francis Mabala, fondateur de NIHILOBA et de SHIDA"} width={709} height={1536} sizes="(max-width: 700px) 78vw, 380px" /></figure><div className="founder-copy"><p className="eyebrow">{locale === "en" ? "Founder" : "Fondateur"}</p><h2>{t.about.founderTitle}</h2><p className="founder-role">{t.about.founderRole}</p>{t.about.founder.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<p><a href={`mailto:${CONTACT_EMAILS.founder}`}>{CONTACT_EMAILS.founder}</a></p></div></div></section>
    <CtaSection eyebrow={t.common.talk} href={localizedPath(locale,"/contact")} label={t.common.contact} title={t.home.ctaTitle} description={t.home.ctaText} />
  </>;
}

export function ProductsPage({ locale }: { locale: Locale }) {
  const t = copy[locale];
  return <><Hero compact eyebrow={t.products.eyebrow} title={t.products.title} description={t.products.description} />
    <section className="section"><div className="container"><ShidaPanel locale={locale}/><div className="future-note"><span className="section-index">02</span><div><h2>{t.products.futureTitle}</h2><p>{t.products.future}</p></div></div></div></section>
    <CtaSection eyebrow={t.common.talk} href={localizedPath(locale,"/contact")} label={t.common.contact} title={t.home.ctaTitle} description={t.home.ctaText}/>
  </>;
}

const marketIcons: ReactNode[] = [<BriefcaseIcon key="a"/>,<ToolsIcon key="b"/>,<HomeIcon key="c"/>,<CarIcon key="d"/>];
export function ShidaPage({ locale }: { locale: Locale }) {
  const t=copy[locale]; const s=t.shida;
  const markets=[[s.employment,s.employmentText],[s.services,s.servicesText],[s.housing,s.housingText],[s.transport,s.transportText],[s.bookingCapability,s.bookingCapabilityText]];
  return <><section className="shida-hero"><div className="container shida-hero-grid"><div><p className="eyebrow">{s.eyebrow}</p><h1>{s.title}</h1><p>{s.description}</p><ButtonLink href={OFFICIAL_CHANNELS.whatsapp} external>{t.common.open}</ButtonLink></div><div className="shida-hero-logo"><BrandLogo brand="shida" eager/><p>{s.first}</p></div></div></section>
    <section className="section how-section"><div className="container"><SectionHeading eyebrow={locale==="en"?"Four simple steps":"Quatre étapes simples"} title={s.howTitle}/><ol className="how-steps">{s.howSteps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><p>{step}</p></li>)}</ol></div></section>
    <section className="section journey-section"><div className="container"><SectionHeading eyebrow={locale==="en"?"A guided WhatsApp journey":"Un parcours guidé sur WhatsApp"} title={s.actionTitle} description={s.actionIntro}/><div className="screenshot-journey">{s.journey.map(([title,caption,src],i)=><figure className="journey-step" key={title}><div className="journey-meta"><span>{locale==="en"?"Step":"Étape"} {i+1}</span><h3>{title}</h3></div><div className="screenshot-frame"><Image src={src} alt={caption} width={921} height={2048} sizes="(max-width: 700px) 86vw, 420px" /></div><figcaption>{caption}</figcaption></figure>)}</div></div></section>
    <section className="section available-section"><div className="container"><SectionHeading eyebrow={t.common.available} title={s.availableTitle} description={s.availableIntro}/><div className="available-list">{markets.map((m,i)=><article key={m[0]}><span className="available-number">{String(i+1).padStart(2,"0")}</span><div>{i<4 && <div className="feature-icon">{marketIcons[i]}</div>}<h3>{m[0]}</h3><p>{m[1]}</p></div></article>)}</div></div></section>
    <section className="section audience-section"><div className="container editorial-split"><span className="section-index">{locale==="en"?"For people and organisations":"Pour les personnes et les organisations"}</span><div><h2>{s.audienceTitle}</h2><p className="lead-copy">{s.audience}</p><div className="audience-list">{s.audiences.map(item=><span key={item}>{item}</span>)}</div></div></div></section>
    <section className="section roadmap-section"><div className="container"><SectionHeading eyebrow={locale==="en"?"Roadmap":"Feuille de route"} title={s.comingTitle} description={s.comingIntro}/><article className="business-layer"><span className="roadmap-status next">{s.businessLabel}</span><div><h3>{s.businessTitle}</h3><p>{s.business}</p></div></article><div className="roadmap-list">{s.roadmap.map(([title,description])=><article key={title}><span className="roadmap-status">{s.plannedLabel}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <CtaSection eyebrow="WhatsApp" title={s.ctaTitle} description={s.ctaText} href={OFFICIAL_CHANNELS.whatsapp} label={t.common.open}/>
  </>;
}

export function EducationPage({ locale }: { locale: Locale }) {
  const t=copy[locale], e=t.education; const areas=[[<BookIcon key="a"/>,e.literacy,e.literacyText],[<LightbulbIcon key="b"/>,e.practical,e.practicalText],[<CheckIcon key="c"/>,e.access,e.accessText]] as const;
  return <><Hero compact eyebrow={e.eyebrow} title={e.title} description={e.description}/><section className="section"><div className="container editorial-split"><span className="planned-label">{t.common.planned}</span><div><h2>{e.visionTitle}</h2>{e.vision.map(p=><p className="lead-copy" key={p}>{p}</p>)}</div></div></section><section className="section muted-section"><div className="container"><SectionHeading title={e.focusTitle}/><div className="plain-features three">{areas.map(([icon,title,text])=><article key={title}><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><CtaSection eyebrow={t.common.talk} href={localizedPath(locale,"/contact")} label={t.common.contact} title={t.home.ctaTitle} description={t.home.ctaText}/></>;
}

export function ContactPage({ locale }: { locale: Locale }) {
  const t=copy[locale], c=t.contact;
  return <><Hero compact eyebrow={c.eyebrow} title={c.title} description={c.description}/><section className="section"><div className="container contact-layout"><div className="email-block"><MailIcon/><h2>{c.emailTitle}</h2><p>{c.emailText}</p><a href={`mailto:${CONTACT_EMAILS.general}`}>{CONTACT_EMAILS.general}</a><ButtonLink href={`mailto:${CONTACT_EMAILS.general}`}>{c.send}</ButtonLink><small>{c.emailNote}</small></div><div className="social-block"><h2>{c.social}</h2>{SOCIAL_LINKS.map(({label,href})=><div key={label}><a href={href} target="_blank" rel="noopener noreferrer">{label}</a><small>{c.official}</small></div>)}</div></div></section></>;
}
