import type { Locale } from "../../lib/i18n";
import { localizedPath } from "../../lib/i18n";
import { CONTACT_EMAILS, SOCIAL_LINKS } from "../../lib/brand";
import { ButtonLink } from "../button-link";
import { CtaSection } from "../cta-section";
import { Hero } from "../hero";
import { BookIcon, CheckIcon, LightbulbIcon, MailIcon } from "../icons";
import { SectionHeading } from "../section-heading";

const copy = {
  en: {
    common: { learn: "Learn more", contact: "Contact NIHILOBA", talk: "Start a conversation", planned: "Planned initiative", available: "Available now", open: "Open SHIDA on WhatsApp" },
    home: {
      eyebrow: "Roots. Impact. Future.", title: "Creating practical digital solutions with roots and purpose.", description: "NIHILOBA develops technology that responds to real needs. Our work begins with SHIDA, a WhatsApp-based platform that connects people to opportunities, services, housing and transport.", primary: "Discover SHIDA", secondary: "Our story",
      introTitle: "Technology should feel useful from the start.", intro: "We begin with the realities of daily life: the tools people already use, the information they need and the barriers that slow them down. This approach helps us create products that are easier to reach and simpler to understand.",
      storyTitle: "A name shaped by creation and the baobab.", story: "NIHILOBA draws inspiration from creatio ex nihilo, creation from nothing, and from the symbolic power of the baobab. Together, these ideas express our belief that a grounded idea can grow into lasting, shared impact.", storyLink: "Read our story",
      productTitle: "Our first product begins on WhatsApp.", productText: "SHIDA brings employment opportunities, services, housing and transport into a familiar conversation. There is no new application to install.",
      educationTitle: "Practical learning can widen opportunity.", educationText: "NIHILOBA Education is a planned nonprofit initiative focused on digital literacy, accessible learning and useful technology skills.",
      ctaTitle: "Have a question or an idea to discuss?", ctaText: "We welcome conversations with users, communities, companies, institutions and potential partners.",
    },
    shida: {
      eyebrow: "A product by NIHILOBA", title: "Everyday opportunities, available through WhatsApp.", description: "Jobs, services, housing, transport and local commerce are accessible with SHIDA in a familiar WhatsApp conversation. Users do not need to install a new application.",
      first: "SHIDA is the first digital product developed by NIHILOBA.", marketsTitle: "What you can explore today", marketsDesc: "SHIDA currently supports practical marketplaces and booking journeys.", employment: "Employment", employmentText: "Find and explore relevant employment opportunities.", services: "Services", servicesText: "Connect with professionals and everyday services.", housing: "Housing", housingText: "Access housing information through a direct channel.", transport: "Transport", transportText: "Explore useful transport options and information.", wenze: "Wenze", wenzeText: "Discover shops and products available through SHIDA, explore their offers and continue the relevant journey with SHIDA.",
      bookingTitle: "Appointments and bookings", booking: "Appointment and booking management is one of SHIDA’s capabilities. It supports professionals and organisations within a broader platform that also covers opportunities, services, housing and transport.",
      actionTitle: "See SHIDA in action", actionIntro: "SHIDA works inside a familiar WhatsApp conversation. Users choose a marketplace, follow guided steps and complete their request without downloading another application.",
      journey: [["Choose a marketplace", "Choose employment, services, housing, transport or Wenze.", "/shida-marketplace-menu.jpeg"], ["Explore a service category", "Browse categories adapted to different professional and institutional needs.", "/shida-service-categories.jpeg"], ["Create or publish an opportunity", "Review a job offer before publication.", "/shida-job-offer-summary.jpeg"], ["Configure professional availability", "Define availability for bookings and service requests.", "/shida-service-availability.jpeg"]],
      howTitle: "How SHIDA works", howSteps: ["Save the SHIDA WhatsApp number.", "Send “Hello” or “Bonjour”.", "Choose a marketplace.", "Complete the process directly in WhatsApp."],
      availableTitle: "Available today", availableIntro: "SHIDA currently supports these areas through WhatsApp. The depth of each journey continues to develop according to user and partner needs.", bookingCapability: "Appointment and booking management", bookingCapabilityText: "Manage service availability, appointments and booking requests as one capability within the wider service marketplace.",
      qrEyebrow: "Direct entry and confirmation", qrTitle: "QR codes and direct access with SHIDA", qrIntro: "Selected listings, activities and profiles published through SHIDA can have their own link or QR code. A user can scan the QR code or open the link to enter the corresponding SHIDA flow directly.",
      qrDirectTitle: "Direct access before a transaction", qrDirectText: "A dedicated link or QR code can take a user past the general menu and into the relevant SHIDA journey. Opening it does not automatically share personal information.", qrDirectFlow: "Scan or open the link → Enter the relevant SHIDA flow → Continue on WhatsApp",
      qrExamples: [["Jobs", "Recruiters can add a SHIDA link or QR code to an announcement so candidates can enter the relevant application flow."], ["Services and profiles", "A salon, school, professor, clinic or other provider can share direct access to the corresponding service journey."], ["Housing and hotels", "An apartment or hotel listing can link directly to its SHIDA visit or booking journey."], ["Wenze", "A shop or product can provide direct access to its listing and the relevant SHIDA purchase journey."]],
      qrConfirmationTitle: "A SHIDA reference after confirmation", qrConfirmationText: "QR codes can also accompany certain confirmations generated through SHIDA. Service confirmations, hotel bookings and Wenze purchases or orders can include a QR reference to support verification or access to the corresponding transaction where available.", qrConfirmationFlow: "SHIDA confirmation → QR code → Verification or transaction access", qrSafety: "A SHIDA QR code is not an identity document and does not by itself prove payment or disclose customer information.",
      audienceTitle: "Who SHIDA can support", audience: "SHIDA can adapt booking, service, employment and operational flows to different sectors while keeping access within WhatsApp.", audiences: ["Individuals", "Independent professionals", "Businesses", "Schools", "Churches", "Clinics", "Hotels", "Restaurants", "Public institutions"],
      comingTitle: "Coming next", comingIntro: "The following developments are planned and are not yet available. No release dates have been announced.", businessTitle: "Business Layer", businessLabel: "Coming next", business: "The Business Layer will give businesses and institutions additional tools to manage teams, services, availability, appointments and operational activity through SHIDA.",
      roadmap: [["Personal SHIDA QR", "A future SHIDA account may include a reusable personal QR to help a customer connect with a SHIDA-enabled business and accelerate supported workflows. It would not replace official identification or automatically reveal personal information."], ["Payments", "SHIDA is exploring payment flows that could eventually support requesting, confirming and tracking payments linked to bookings, orders or services. SHIDA does not currently present this as a wallet or as holding customer funds."], ["Extended hotel experience", "Further tools are planned for hotels and accommodation providers beyond the currently available public booking journeys."], ["Restaurant food ordering", "A future extension of the restaurant experience beyond table reservations to food ordering."], ["Diaspora Marketplace", "A future marketplace intended to connect diaspora communities with relevant services, opportunities and trusted local needs."]],
      plannedLabel: "Planned development", ctaTitle: "Send a message to begin.", ctaText: "Open SHIDA on WhatsApp at +46 76 970 90 59. The message “Bonjour” is ready for you.",
    },
    education: { eyebrow: "Planned nonprofit initiative", title: "Practical digital learning, made more accessible.", description: "NIHILOBA Education is a planned nonprofit initiative. It will focus on digital literacy, practical technology education and accessible learning.", visionTitle: "Learning connected to daily life", vision: ["The initiative aims to help learners use digital tools with greater confidence. Content will connect technology with study, work and practical problem-solving.", "NIHILOBA Education remains in the planning stage. There are no active programmes at this time. Confirmed details will be shared as the initiative develops."], focusTitle: "Areas of focus", literacy: "Digital literacy", literacyText: "Confidence with the tools that shape daily participation.", practical: "Practical technology", practicalText: "Learning linked to real tasks and useful outcomes.", access: "Accessible learning", accessText: "Formats that consider different contexts and starting points." },
    contact: { eyebrow: "Contact", title: "Let’s talk about what could be useful.", description: "Contact NIHILOBA to ask about SHIDA, share a relevant need or discuss a possible collaboration.", emailTitle: "Email NIHILOBA", emailText: "For product questions, general enquiries, partnerships and institutional conversations.", emailNote: `Partnership enquiries: ${CONTACT_EMAILS.partnerships}`, send: "Send an email", social: "Social channels", official: "Official" },
  },
  fr: {
    common: { learn: "En savoir plus", contact: "Contacter NIHILOBA", talk: "Démarrer une conversation", planned: "Initiative en projet", available: "Disponible maintenant", open: "Ouvrir SHIDA sur WhatsApp" },
    home: {
      eyebrow: "Racines. Impact. Avenir.", title: "Créer des solutions numériques utiles, ancrées dans une vision.", description: "NIHILOBA développe des technologies qui répondent à des besoins réels. Notre parcours commence avec SHIDA, une plateforme accessible sur WhatsApp qui relie les personnes aux opportunités, aux services, au logement et au transport.", primary: "Découvrir SHIDA", secondary: "Notre histoire",
      introTitle: "La technologie doit être utile dès le départ.", intro: "Nous partons des réalités du quotidien : les outils que les personnes utilisent déjà, les informations dont elles ont besoin et les obstacles qui les ralentissent. Cette approche nous aide à créer des produits plus accessibles et plus simples à comprendre.",
      storyTitle: "Un nom inspiré par la création et le baobab.", story: "NIHILOBA s’inspire de creatio ex nihilo, créer à partir de rien, et de la force symbolique du baobab. Ces deux idées expriment notre conviction : une idée bien ancrée peut produire un impact durable et partagé.", storyLink: "Découvrir notre histoire",
      productTitle: "Notre premier produit commence sur WhatsApp.", productText: "SHIDA rassemble les opportunités d’emploi, les services, le logement et le transport dans une conversation familière. Aucune nouvelle application n’est nécessaire.",
      educationTitle: "L’apprentissage pratique peut élargir les possibilités.", educationText: "NIHILOBA Education est une initiative à but non lucratif en projet, consacrée à la culture numérique, à l’apprentissage accessible et aux compétences technologiques utiles.",
      ctaTitle: "Une question ou une idée à partager ?", ctaText: "Nous échangeons volontiers avec les utilisateurs, les communautés, les entreprises, les institutions et les partenaires potentiels.",
    },
    shida: {
      eyebrow: "Un produit NIHILOBA", title: "Les opportunités du quotidien, accessibles sur WhatsApp.", description: "L’emploi, les services, le logement, le transport et le commerce local sont accessibles avec SHIDA dans une conversation WhatsApp familière. Aucune nouvelle application n’est nécessaire.",
      first: "SHIDA est le premier produit numérique développé par NIHILOBA.", marketsTitle: "Ce que vous pouvez explorer aujourd’hui", marketsDesc: "SHIDA prend actuellement en charge des marchés pratiques et des parcours de réservation.", employment: "Emploi", employmentText: "Trouvez et explorez des opportunités d’emploi pertinentes.", services: "Services", servicesText: "Entrez en contact avec des professionnels et des services du quotidien.", housing: "Logement", housingText: "Accédez à des informations sur le logement par un canal direct.", transport: "Transport", transportText: "Explorez des options et des informations utiles sur le transport.", wenze: "Wenze", wenzeText: "Découvrez des boutiques et des produits proposés sur SHIDA, consultez les offres disponibles et poursuivez votre parcours avec SHIDA.",
      bookingTitle: "Rendez-vous et réservations", booking: "La gestion des rendez-vous et des réservations est l’une des fonctions de SHIDA. Elle accompagne les professionnels et les organisations au sein d’une plateforme plus large, qui couvre aussi les opportunités, les services, le logement et le transport.",
      actionTitle: "Découvrez SHIDA en action", actionIntro: "SHIDA fonctionne dans une conversation WhatsApp familière. Les utilisateurs choisissent un marché, suivent des étapes guidées et effectuent leur demande sans télécharger une nouvelle application.",
      journey: [["Choisissez un marché", "Choisissez entre l’emploi, les services, le logement, le transport ou Wenze.", "/shida-marketplace-menu.jpeg"], ["Explorez une catégorie de services", "Parcourez des catégories adaptées aux besoins professionnels et institutionnels.", "/shida-service-categories.jpeg"], ["Créez ou publiez une opportunité", "Vérifiez une offre d’emploi avant sa publication.", "/shida-job-offer-summary.jpeg"], ["Configurez vos disponibilités professionnelles", "Définissez les disponibilités pour les rendez-vous et les demandes de service.", "/shida-service-availability.jpeg"]],
      howTitle: "Comment fonctionne SHIDA", howSteps: ["Enregistrez le numéro WhatsApp de SHIDA.", "Envoyez « Bonjour » ou « Mbote ».", "Choisissez un marché.", "Effectuez les étapes directement dans WhatsApp."],
      availableTitle: "Disponible aujourd’hui", availableIntro: "SHIDA prend actuellement en charge ces domaines via WhatsApp. La profondeur de chaque parcours continue d’évoluer selon les besoins des utilisateurs et des partenaires.", bookingCapability: "Gestion des rendez-vous et des réservations", bookingCapabilityText: "Gérez les disponibilités, les rendez-vous et les demandes de réservation comme une fonction intégrée au marché plus large des services.",
      qrEyebrow: "Accès direct et confirmation", qrTitle: "QR codes et accès direct avec SHIDA", qrIntro: "Certaines annonces, activités et certains profils publiés sur SHIDA peuvent disposer de leur propre lien ou QR code. Une personne peut scanner le QR code ou ouvrir le lien afin d’accéder directement au parcours SHIDA correspondant.",
      qrDirectTitle: "Accès direct avant une transaction", qrDirectText: "Un lien ou QR code dédié peut conduire une personne au-delà du menu général, directement vers le parcours SHIDA concerné. Son ouverture ne partage pas automatiquement des informations personnelles.", qrDirectFlow: "Scannez ou ouvrez le lien → Accédez au bon parcours SHIDA → Continuez sur WhatsApp",
      qrExamples: [["Emploi", "Un recruteur peut ajouter un lien ou QR code SHIDA à une annonce afin que les candidats accèdent au parcours de candidature concerné."], ["Services et profils", "Un salon, une école, un professeur, une clinique ou un autre prestataire peut partager un accès direct au parcours de service correspondant."], ["Logement et hôtels", "Une annonce d’appartement ou d’hôtel peut renvoyer directement vers son parcours SHIDA de visite ou de réservation."], ["Wenze", "Une boutique ou un produit peut donner un accès direct à son annonce et au parcours d’achat SHIDA concerné."]],
      qrConfirmationTitle: "Une référence SHIDA après confirmation", qrConfirmationText: "Les QR codes peuvent également accompagner certaines confirmations générées par SHIDA. Une confirmation de service, une réservation d’hôtel ou un achat ou une commande Wenze peut inclure une référence QR afin de faciliter la vérification ou l’accès à la transaction correspondante, lorsque cette fonction est disponible.", qrConfirmationFlow: "Confirmation SHIDA → QR code → Vérification ou accès à la transaction", qrSafety: "Un QR code SHIDA n’est pas une pièce d’identité et ne prouve pas à lui seul un paiement ni ne divulgue les informations du client.",
      audienceTitle: "À qui SHIDA peut servir", audience: "SHIDA peut adapter les parcours de réservation, de service, d’emploi et d’activité opérationnelle à différents secteurs, tout en restant accessible sur WhatsApp.", audiences: ["Particuliers", "Professionnels indépendants", "Entreprises", "Écoles", "Églises", "Cliniques", "Hôtels", "Restaurants", "Institutions publiques"],
      comingTitle: "Prochaines évolutions", comingIntro: "Les développements suivants sont prévus et ne sont pas encore disponibles. Aucune date de lancement n’a été annoncée.", businessTitle: "Couche Business", businessLabel: "Prochaine évolution", business: "La couche Business offrira aux entreprises et aux institutions des outils supplémentaires pour gérer les équipes, les services, les disponibilités, les rendez-vous et l’activité opérationnelle via SHIDA.",
      roadmap: [["QR personnel SHIDA", "Un futur compte SHIDA pourra inclure un QR personnel réutilisable afin d’aider un client à se connecter à une entreprise utilisant SHIDA et d’accélérer les parcours pris en charge. Il ne remplacera pas une pièce d’identité officielle et ne révélera pas automatiquement des informations personnelles."], ["Paiements", "SHIDA explore l’intégration de parcours de paiement permettant à terme de demander, confirmer et suivre un paiement lié à une réservation, une commande ou un service. SHIDA ne présente pas actuellement cette fonction comme un portefeuille et ne détient pas les fonds des clients."], ["Expérience hôtelière étendue", "Des outils supplémentaires sont prévus pour les hôtels et les établissements d’hébergement, au-delà des parcours publics de réservation déjà disponibles."], ["Commande de repas au restaurant", "Une future extension de l’expérience restaurant, au-delà de la réservation de table, vers la commande de repas."], ["Diaspora Marketplace", "Un futur marché destiné à relier les communautés de la diaspora à des services, des opportunités et des besoins locaux pertinents."]],
      plannedLabel: "Développement prévu", ctaTitle: "Envoyez un message pour commencer.", ctaText: "Ouvrez SHIDA sur WhatsApp au +46 76 970 90 59. Le message « Bonjour » est déjà préparé.",
    },
    education: { eyebrow: "Initiative à but non lucratif en projet", title: "Un apprentissage numérique pratique et plus accessible.", description: "NIHILOBA Education est une initiative à but non lucratif en projet. Elle sera consacrée à la culture numérique, à la formation technologique pratique et à l’apprentissage accessible.", visionTitle: "Un apprentissage lié à la vie quotidienne", vision: ["L’initiative vise à aider les apprenants à utiliser les outils numériques avec plus d’assurance. Les contenus relieront la technologie aux études, au travail et à la résolution de problèmes concrets.", "NIHILOBA Education est encore au stade de la planification. Aucun programme n’est actif actuellement. Les informations confirmées seront publiées au fil du développement de l’initiative."], focusTitle: "Domaines d’action", literacy: "Culture numérique", literacyText: "Mieux maîtriser les outils qui façonnent la participation quotidienne.", practical: "Technologie pratique", practicalText: "Relier l’apprentissage à des tâches réelles et à des résultats utiles.", access: "Apprentissage accessible", accessText: "Des formats adaptés à différents contextes et points de départ." },
    contact: { eyebrow: "Contact", title: "Parlons de ce qui pourrait être utile.", description: "Contactez NIHILOBA pour poser une question sur SHIDA, partager un besoin pertinent ou envisager une collaboration.", emailTitle: "Écrire à NIHILOBA", emailText: "Pour les questions sur nos produits, les demandes générales, les partenariats et les échanges institutionnels.", emailNote: `Demandes de partenariat : ${CONTACT_EMAILS.partnerships}`, send: "Envoyer un e-mail", social: "Réseaux sociaux", official: "Officiel" },
  },
} as const;

export { HomePage } from "./home-page";

export { AboutPage } from "./about-page";

export { ProductsPage } from "./products-page";

export { ShidaPage } from "./shida-page";

export function EducationPage({ locale }: { locale: Locale }) {
  const t=copy[locale], e=t.education; const areas=[[<BookIcon key="a"/>,e.literacy,e.literacyText],[<LightbulbIcon key="b"/>,e.practical,e.practicalText],[<CheckIcon key="c"/>,e.access,e.accessText]] as const;
  return <><Hero compact eyebrow={e.eyebrow} title={e.title} description={e.description}/><section className="section"><div className="container editorial-split"><span className="planned-label">{t.common.planned}</span><div><h2>{e.visionTitle}</h2>{e.vision.map(p=><p className="lead-copy" key={p}>{p}</p>)}</div></div></section><section className="section muted-section"><div className="container"><SectionHeading title={e.focusTitle}/><div className="plain-features three">{areas.map(([icon,title,text])=><article key={title}><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><CtaSection eyebrow={t.common.talk} href={localizedPath(locale,"/contact")} label={t.common.contact} title={t.home.ctaTitle} description={t.home.ctaText}/></>;
}

export function ContactPage({ locale }: { locale: Locale }) {
  const t=copy[locale], c=t.contact;
  return <><Hero compact eyebrow={c.eyebrow} title={c.title} description={c.description}/><section className="section"><div className="container contact-layout"><div className="email-block"><MailIcon/><h2>{c.emailTitle}</h2><p>{c.emailText}</p><a href={`mailto:${CONTACT_EMAILS.general}`}>{CONTACT_EMAILS.general}</a><ButtonLink href={`mailto:${CONTACT_EMAILS.general}`}>{c.send}</ButtonLink><small>{c.emailNote}</small></div><div className="social-block"><h2>{c.social}</h2>{SOCIAL_LINKS.map(({label,href})=><div key={label}><a href={href} target="_blank" rel="noopener noreferrer">{label}</a><small>{c.official}</small></div>)}</div></div></section></>;
}
