import type { Locale } from "../../lib/i18n";
import { LegalList, LegalPage, LegalRelatedLinks, LegalSection } from "../legal/legal-document";

type Section = {
  id: string;
  title: string;
  paragraphs: readonly string[];
  items?: readonly string[];
  after?: readonly string[];
};

const content: Record<Locale, {
  title: string;
  effectiveDate: string;
  readingTime: string;
  sections: readonly Section[];
}> = {
  en: {
    title: "Terms of Use",
    effectiveDate: "Effective date: August 2026",
    readingTime: "7 min read",
    sections: [
      { id: "introduction", title: "1. Introduction", paragraphs: ["Welcome to NIHILOBA.", "These Terms of Use govern your access to and use of the NIHILOBA website, SHIDA and any other products or digital services developed by NIHILOBA.", "By accessing or using our services, you agree to comply with these Terms.", "If you do not agree with these Terms, please do not use our services."] },
      { id: "about-shida", title: "2. About SHIDA", paragraphs: ["SHIDA is a platform that operates through WhatsApp to simplify access to everyday services.", "Depending on the available features, users may:"], items: ["search for employment opportunities;", "publish employment opportunities;", "offer professional services;", "request services;", "publish housing opportunities;", "search for housing;", "organise transport requests;", "manage appointments;", "communicate with participating organisations."], after: ["Additional features may be introduced as SHIDA continues to evolve."] },
      { id: "eligibility", title: "3. Eligibility", paragraphs: ["By using SHIDA, you confirm that:"], items: ["the information you provide is accurate;", "you are authorised to use the WhatsApp account connected to SHIDA;", "you will use the platform responsibly;", "you will comply with applicable laws."], after: ["Where required by applicable law, children should use SHIDA only with the involvement of a parent or legal guardian."] },
      { id: "user-responsibilities", title: "4. User Responsibilities", paragraphs: ["Users are responsible for:"], items: ["keeping their information reasonably accurate;", "respecting other users;", "communicating honestly;", "using SHIDA only for legitimate purposes;", "reviewing information before submitting requests."], after: ["Users remain responsible for the content they publish through SHIDA."] },
      { id: "acceptable-use", title: "5. Prohibited Activities", paragraphs: ["Users must not use SHIDA to:"], items: ["publish fraudulent information;", "impersonate another individual or organisation;", "distribute illegal content;", "harass, threaten or abuse other users;", "interfere with the operation of the platform;", "attempt unauthorised access to systems or accounts;", "distribute malware or harmful software;", "use SHIDA for activities prohibited by applicable law."], after: ["NIHILOBA reserves the right to suspend or remove accounts that violate these Terms."] },
      { id: "marketplace-content", title: "6. Marketplace Content", paragraphs: ["Users remain responsible for the information they publish.", "Examples include:"], items: ["employment opportunities;", "service descriptions;", "housing listings;", "transport requests;", "appointment information."], after: ["NIHILOBA does not guarantee that information published by users is complete, accurate or current.", "Users should exercise appropriate judgement before entering into any agreement."] },
      { id: "appointments-and-requests", title: "7. Appointments and Requests", paragraphs: ["SHIDA facilitates communication and appointment management.", "The platform helps organise requests between users and participating organisations.", "Unless explicitly stated, NIHILOBA is not a party to agreements concluded between users.", "Examples include:"], items: ["employment discussions;", "service bookings;", "housing visits;", "restaurant reservations;", "appointments with institutions."], after: ["Responsibility for fulfilling those agreements remains with the participating parties."] },
      { id: "availability-of-services", title: "8. Availability of Services", paragraphs: ["NIHILOBA continuously improves SHIDA.", "Features may:"], items: ["change;", "be updated;", "become unavailable temporarily;", "be replaced by improved alternatives."], after: ["Although we aim to provide reliable services, uninterrupted availability cannot be guaranteed.", "Scheduled maintenance or unexpected technical issues may occasionally affect the platform."] },
      { id: "future-features", title: "9. Future Features", paragraphs: ["Some sections of the website describe planned developments.", "Examples may include:"], items: ["Business Layer;", "Diaspora Marketplace;", "Wenze Marketplace;", "hotel booking;", "restaurant food ordering;", "QR appointment confirmation;", "pickup reminders."], after: ["These descriptions represent the current product roadmap.", "Planned features should not be interpreted as guarantees regarding future availability or release dates."] },
      { id: "intellectual-property", title: "10. Intellectual Property", paragraphs: ["Unless otherwise stated, the NIHILOBA name, SHIDA name, logos, website design, software, documentation and original content are the intellectual property of NIHILOBA.", "Users may not copy, reproduce or distribute substantial parts of the platform without prior permission except where permitted by applicable law."] },
      { id: "third-party-services", title: "11. Third-Party Services", paragraphs: ["SHIDA relies on third-party services to operate.", "Examples may include:"], items: ["WhatsApp;", "cloud hosting providers;", "mapping services;", "future payment providers."], after: ["These services remain subject to their own terms and privacy policies.", "NIHILOBA is not responsible for the independent operation of third-party services."] },
      { id: "limitation-of-liability", title: "12. Limitation of Liability", paragraphs: ["NIHILOBA provides SHIDA as a digital platform designed to facilitate communication, appointments and access to opportunities.", "To the extent permitted by applicable law, NIHILOBA is not responsible for:"], items: ["agreements made between users;", "employment decisions;", "housing transactions;", "service quality provided by independent professionals;", "business decisions made by organisations using SHIDA;", "indirect or consequential losses arising from use of the platform."], after: ["Nothing in these Terms limits rights that cannot legally be excluded under applicable law."] },
      { id: "account-suspension", title: "13. Account Suspension", paragraphs: ["NIHILOBA may suspend or terminate access where necessary to:"], items: ["protect users;", "investigate abuse;", "maintain platform security;", "comply with legal obligations."], after: ["Whenever reasonably possible, appropriate explanations will be provided."] },
      { id: "changes-to-terms", title: "14. Changes to These Terms", paragraphs: ["As SHIDA evolves, these Terms may be updated.", "The effective date at the top of this page indicates the latest version.", "Continued use of the platform following updates constitutes acceptance of the revised Terms."] },
      { id: "governing-law", title: "15. Governing Law", paragraphs: ["These Terms are intended to comply with applicable laws.", "As NIHILOBA expands internationally, specific legal requirements may vary depending on the country in which services are offered.", "Where required, additional country-specific terms may be introduced."] },
      { id: "contact", title: "16. Contact", paragraphs: ["Questions regarding these Terms may be sent to:", "Email:", "shida.nihiloba@gmail.com", "A dedicated legal contact under @nihiloba.com will be introduced as NIHILOBA continues to grow."] },
      { id: "closing-statement", title: "Closing Statement", paragraphs: ["NIHILOBA was created to develop practical technology that makes everyday services easier to access.", "These Terms are intended to establish a clear and fair relationship between NIHILOBA and every individual, professional, business and institution using our services.", "As our products continue to evolve, these Terms will evolve with them while remaining guided by the same principles of transparency, responsibility and respect."] },
    ],
  },
  fr: {
    title: "Conditions d’utilisation",
    effectiveDate: "Date d’entrée en vigueur : août 2026",
    readingTime: "7 min de lecture",
    sections: [
      { id: "introduction", title: "1. Introduction", paragraphs: ["Bienvenue chez NIHILOBA.", "Les présentes Conditions d’utilisation régissent votre accès au site internet de NIHILOBA, à SHIDA ainsi qu’à tout autre produit ou service numérique développé par NIHILOBA, et leur utilisation.", "En accédant à nos services ou en les utilisant, vous acceptez de respecter les présentes Conditions.", "Si vous n’acceptez pas ces Conditions, veuillez ne pas utiliser nos services."] },
      { id: "a-propos-de-shida", title: "2. À propos de SHIDA", paragraphs: ["SHIDA est une plateforme accessible via WhatsApp qui simplifie l’accès aux services du quotidien.", "Selon les fonctionnalités disponibles, les utilisateurs peuvent :"], items: ["rechercher des opportunités d’emploi ;", "publier des opportunités d’emploi ;", "proposer des services professionnels ;", "demander des services ;", "publier des offres de logement ;", "rechercher un logement ;", "organiser des demandes de transport ;", "gérer des rendez-vous ;", "communiquer avec les organisations participantes."], after: ["Des fonctionnalités supplémentaires pourront être introduites à mesure que SHIDA évolue."] },
      { id: "admissibilite", title: "3. Admissibilité", paragraphs: ["En utilisant SHIDA, vous confirmez que :"], items: ["les informations que vous fournissez sont exactes ;", "vous êtes autorisé à utiliser le compte WhatsApp associé à SHIDA ;", "vous utiliserez la plateforme de manière responsable ;", "vous respecterez les lois applicables."], after: ["Lorsque la loi applicable l’exige, les enfants ne doivent utiliser SHIDA qu’avec la participation d’un parent ou d’un représentant légal."] },
      { id: "responsabilites-utilisateurs", title: "4. Responsabilités des utilisateurs", paragraphs: ["Les utilisateurs sont responsables de :"], items: ["maintenir leurs informations raisonnablement exactes ;", "respecter les autres utilisateurs ;", "communiquer honnêtement ;", "utiliser SHIDA uniquement à des fins légitimes ;", "vérifier les informations avant d’envoyer des demandes."], after: ["Les utilisateurs restent responsables du contenu qu’ils publient par l’intermédiaire de SHIDA."] },
      { id: "acceptable-use", title: "5. Activités interdites", paragraphs: ["Les utilisateurs ne doivent pas utiliser SHIDA pour :"], items: ["publier des informations frauduleuses ;", "usurper l’identité d’une autre personne ou organisation ;", "diffuser du contenu illégal ;", "harceler, menacer ou maltraiter d’autres utilisateurs ;", "perturber le fonctionnement de la plateforme ;", "tenter d’accéder sans autorisation à des systèmes ou à des comptes ;", "diffuser des logiciels malveillants ou nuisibles ;", "utiliser SHIDA pour des activités interdites par la loi applicable."], after: ["NIHILOBA se réserve le droit de suspendre ou de supprimer les comptes qui enfreignent les présentes Conditions."] },
      { id: "contenu-place-de-marche", title: "6. Contenu de la place de marché", paragraphs: ["Les utilisateurs restent responsables des informations qu’ils publient.", "Cela peut notamment inclure :"], items: ["des opportunités d’emploi ;", "des descriptions de services ;", "des annonces de logement ;", "des demandes de transport ;", "des informations relatives aux rendez-vous."], after: ["NIHILOBA ne garantit pas que les informations publiées par les utilisateurs sont complètes, exactes ou à jour.", "Les utilisateurs doivent faire preuve de discernement avant de conclure tout accord."] },
      { id: "rendez-vous-demandes", title: "7. Rendez-vous et demandes", paragraphs: ["SHIDA facilite la communication et la gestion des rendez-vous.", "La plateforme aide à organiser les demandes entre les utilisateurs et les organisations participantes.", "Sauf indication explicite, NIHILOBA n’est pas partie aux accords conclus entre les utilisateurs.", "Cela peut notamment inclure :"], items: ["les échanges relatifs à l’emploi ;", "les réservations de services ;", "les visites de logements ;", "les réservations de restaurants ;", "les rendez-vous avec des institutions."], after: ["La responsabilité de l’exécution de ces accords incombe aux parties participantes."] },
      { id: "disponibilite-services", title: "8. Disponibilité des services", paragraphs: ["NIHILOBA améliore continuellement SHIDA.", "Les fonctionnalités peuvent :"], items: ["changer ;", "être mises à jour ;", "devenir temporairement indisponibles ;", "être remplacées par de meilleures solutions."], after: ["Bien que nous nous efforcions de fournir des services fiables, leur disponibilité ininterrompue ne peut être garantie.", "Une maintenance programmée ou des problèmes techniques imprévus peuvent occasionnellement affecter la plateforme."] },
      { id: "fonctionnalites-futures", title: "9. Fonctionnalités futures", paragraphs: ["Certaines sections du site internet décrivent des développements prévus.", "Cela peut notamment inclure :"], items: ["la couche Business ;", "Diaspora Marketplace ;", "Wenze Marketplace ;", "la réservation d’hôtels ;", "la commande de repas au restaurant ;", "la confirmation de rendez-vous par code QR ;", "les rappels de retrait."], after: ["Ces descriptions représentent la feuille de route actuelle du produit.", "Les fonctionnalités prévues ne doivent pas être interprétées comme des garanties quant à leur disponibilité future ou à leur date de lancement."] },
      { id: "propriete-intellectuelle", title: "10. Propriété intellectuelle", paragraphs: ["Sauf indication contraire, le nom NIHILOBA, le nom SHIDA, les logos, la conception du site internet, les logiciels, la documentation et le contenu original sont la propriété intellectuelle de NIHILOBA.", "Les utilisateurs ne peuvent copier, reproduire ou distribuer des parties substantielles de la plateforme sans autorisation préalable, sauf lorsque la loi applicable le permet."] },
      { id: "services-tiers", title: "11. Services tiers", paragraphs: ["Le fonctionnement de SHIDA repose sur des services tiers.", "Cela peut notamment inclure :"], items: ["WhatsApp ;", "des fournisseurs d’hébergement cloud ;", "des services de cartographie ;", "de futurs prestataires de paiement."], after: ["Ces services restent soumis à leurs propres conditions et politiques de confidentialité.", "NIHILOBA n’est pas responsable du fonctionnement indépendant des services tiers."] },
      { id: "limitation-responsabilite", title: "12. Limitation de responsabilité", paragraphs: ["NIHILOBA fournit SHIDA en tant que plateforme numérique conçue pour faciliter la communication, les rendez-vous et l’accès aux opportunités.", "Dans la mesure permise par la loi applicable, NIHILOBA n’est pas responsable :"], items: ["des accords conclus entre les utilisateurs ;", "des décisions relatives à l’emploi ;", "des transactions immobilières ;", "de la qualité des services fournis par des professionnels indépendants ;", "des décisions commerciales prises par les organisations utilisant SHIDA ;", "des pertes indirectes ou consécutives résultant de l’utilisation de la plateforme."], after: ["Aucune disposition des présentes Conditions ne limite les droits qui ne peuvent légalement être exclus en vertu de la loi applicable."] },
      { id: "suspension-compte", title: "13. Suspension du compte", paragraphs: ["NIHILOBA peut suspendre ou résilier l’accès lorsque cela est nécessaire pour :"], items: ["protéger les utilisateurs ;", "enquêter sur des abus ;", "maintenir la sécurité de la plateforme ;", "respecter des obligations légales."], after: ["Dans la mesure du raisonnable, des explications appropriées seront fournies."] },
      { id: "modifications-conditions", title: "14. Modifications des présentes Conditions", paragraphs: ["À mesure que SHIDA évolue, les présentes Conditions pourront être mises à jour.", "La date d’entrée en vigueur indiquée en haut de cette page correspond à la version la plus récente.", "La poursuite de l’utilisation de la plateforme après une mise à jour vaut acceptation des Conditions révisées."] },
      { id: "droit-applicable", title: "15. Droit applicable", paragraphs: ["Les présentes Conditions sont destinées à respecter les lois applicables.", "À mesure que NIHILOBA se développe à l’international, les exigences juridiques particulières peuvent varier selon le pays dans lequel les services sont proposés.", "Lorsque cela est nécessaire, des conditions supplémentaires propres à certains pays pourront être introduites."] },
      { id: "contact", title: "16. Contact", paragraphs: ["Les questions relatives aux présentes Conditions peuvent être envoyées à :", "E-mail :", "shida.nihiloba@gmail.com", "Une adresse de contact juridique dédiée sous le domaine @nihiloba.com sera introduite à mesure que NIHILOBA se développe."] },
      { id: "declaration-finale", title: "Déclaration finale", paragraphs: ["NIHILOBA a été créé afin de développer des technologies pratiques qui facilitent l’accès aux services du quotidien.", "Les présentes Conditions visent à établir une relation claire et équitable entre NIHILOBA et chaque particulier, professionnel, entreprise et institution utilisant nos services.", "À mesure que nos produits continuent d’évoluer, les présentes Conditions évolueront avec eux tout en restant guidées par les mêmes principes de transparence, de responsabilité et de respect."] },
    ],
  },
};

export function TermsOfUsePage({ locale }: { locale: Locale }) {
  const page = content[locale];
  const toc = page.sections.map(({ id, title }) => ({ id, label: title.replace(/^\d+\.\s*/, "") }));

  return (
    <LegalPage locale={locale} eyebrow={locale === "en" ? "Trust Center" : "Centre de confiance"} title={page.title} updated={page.effectiveDate} readingTime={page.readingTime} toc={toc} related={false}>
      {page.sections.map((section) => <LegalSection id={section.id} title={section.title} key={section.id}>
        {section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
        {section.items && <LegalList items={section.items} />}
        {section.after?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
      </LegalSection>)}
      <LegalRelatedLinks locale={locale} current="terms" />
    </LegalPage>
  );
}
